// Code generated from API definition by Databricks SDK Generator. DO NOT EDIT.


import {Temporal} from '@js-temporal/polyfill';
import {z} from 'zod';

export interface CreateCustomOAuthAppIntegration {
  accountId?: string | undefined;
  /** List of OAuth redirect urls */
  redirectUrls?: string[] | undefined;
  /** Name of the custom OAuth app */
  name?: string | undefined;
  /** This field indicates whether an OAuth client secret is required to authenticate this client. */
  confidential?: boolean | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  /**
   * OAuth scopes granted to the application.
   * Supported scopes: all-apis, sql, offline_access, openid, profile, email.
   */
  scopes?: string[] | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
}

export interface CreatePublishedOAuthAppIntegration {
  accountId?: string | undefined;
  /**
   * App id of the OAuth published app integration.
   * For example power-bi, tableau-deskop
   */
  appId?: string | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface CreatePublishedOAuthAppIntegration_Response {
  /** Unique integration id for the published OAuth app */
  integrationId?: string | undefined;
}

export interface CustomOAuthAppIntegration {
  /** ID of this custom app */
  integrationId?: string | undefined;
  /** The client id of the custom OAuth app */
  clientId?: string | undefined;
  /** List of OAuth redirect urls */
  redirectUrls?: string[] | undefined;
  /** The display name of the custom OAuth app */
  name?: string | undefined;
  /** This field indicates whether an OAuth client secret is required to authenticate this client. */
  confidential?: boolean | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  scopes?: string[] | undefined;
  createdBy?: number | undefined;
  createTime?: string | undefined;
  creatorUsername?: string | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
  /** The principal id of the service principal associated with this OAuth app. */
  principalId?: number | undefined;
}

export interface CustomOAuthAppIntegrationSecret {
  /** Unique integration id for the custom OAuth app */
  integrationId?: string | undefined;
  /** OAuth client-id generated by the <Databricks> */
  clientId?: string | undefined;
  /**
   * OAuth client-secret generated by the <Databricks>.
   * If this is a confidential OAuth app client-secret will be generated.
   */
  clientSecret?: string | undefined;
  /** The principal id of the service principal associated with this OAuth app. */
  principalId?: number | undefined;
  /**
   * The expiration time of the client secret.
   * If not present, the secret does not expire.
   */
  clientSecretExpireTime?: Temporal.Instant | undefined;
}

export interface DeleteCustomOAuthAppIntegration {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention, @typescript-eslint/no-empty-object-type -- Proto-style nested message name.
export interface DeleteCustomOAuthAppIntegration_Response {}

export interface DeletePublishedOAuthAppIntegration {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention, @typescript-eslint/no-empty-object-type -- Proto-style nested message name.
export interface DeletePublishedOAuthAppIntegration_Response {}

export interface GetCustomOAuthAppIntegration {
  /** The account ID. */
  accountId?: string | undefined;
  /** The OAuth app integration ID. */
  integrationId?: string | undefined;
}

export interface GetPublishedOAuthAppIntegration {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

export interface ListCustomOAuthAppIntegrations {
  accountId?: string | undefined;
  pageToken?: string | undefined;
  pageSize?: number | undefined;
  includeCreatorUsername?: boolean | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface ListCustomOAuthAppIntegrations_Response {
  /** List of Custom OAuth App Integrations defined for the account. */
  apps?: CustomOAuthAppIntegration[] | undefined;
  nextPageToken?: string | undefined;
}

export interface ListPublishedOAuthAppIntegrations {
  accountId?: string | undefined;
  pageToken?: string | undefined;
  pageSize?: number | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface ListPublishedOAuthAppIntegrations_Response {
  /** List of Published OAuth App Integrations defined for the account. */
  apps?: PublishedOAuthAppIntegration[] | undefined;
  nextPageToken?: string | undefined;
}

export interface PublishedOAuthAppIntegration {
  /** App-id of the published app integration */
  appId?: string | undefined;
  /** Unique integration id for the published OAuth app */
  integrationId?: string | undefined;
  /** Display name of the published OAuth app */
  name?: string | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  createdBy?: number | undefined;
  createTime?: string | undefined;
}

export interface TokenAccessPolicy {
  /** access token time to live in minutes */
  accessTokenTtlInMinutes?: number | undefined;
  /**
   * Refresh token time to live in minutes.
   * When single-use refresh tokens are enabled, this represents the TTL of an individual refresh token.
   * If the refresh token is used before it expires, a new one is issued with a renewed individual TTL.
   */
  refreshTokenTtlInMinutes?: number | undefined;
  /**
   * Whether to enable single-use refresh tokens (refresh token rotation).
   * If this feature is enabled, upon successfully getting a new access token using a refresh token, <Databricks> will
   * issue a new refresh token along with the access token in the response and invalidate the old refresh token.
   * The client should use the new refresh token to get access tokens in future requests.
   */
  enableSingleUseRefreshTokens?: boolean | undefined;
  /**
   * Absolute OAuth session TTL in minutes. Effective only when the single-use refresh token feature is enabled.
   * This is the absolute TTL of all refresh tokens issued in one OAuth session. When a new refresh token is issued
   * during refresh token rotation, it will inherit the same absolute TTL as the old refresh token.
   * In other words, this represents the maximum amount of time a user can stay logged in without re-authenticating.
   */
  absoluteSessionLifetimeInMinutes?: number | undefined;
}

export interface UpdateCustomOAuthAppIntegration {
  accountId?: string | undefined;
  integrationId?: string | undefined;
  /** List of OAuth redirect urls to be updated in the custom OAuth app integration */
  redirectUrls?: string[] | undefined;
  /** Token access policy to be updated in the custom OAuth app integration */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  /**
   * List of OAuth scopes to be updated in the custom OAuth app integration, similar to redirect URIs this will fully
   * replace the existing values instead of appending
   */
  scopes?: string[] | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention, @typescript-eslint/no-empty-object-type -- Proto-style nested message name.
export interface UpdateCustomOAuthAppIntegration_Response {}

export interface UpdatePublishedOAuthAppIntegration {
  accountId?: string | undefined;
  integrationId?: string | undefined;
  /** Token access policy to be updated in the published OAuth app integration */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention, @typescript-eslint/no-empty-object-type -- Proto-style nested message name.
export interface UpdatePublishedOAuthAppIntegration_Response {}

export const unmarshalCreateCustomOAuthAppIntegrationSchema: z.ZodType<CreateCustomOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    redirect_urls: z.array(z.string()).optional(),
    name: z.string().optional(),
    confidential: z.boolean().optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    user_authorized_scopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    redirectUrls: d.redirect_urls,
    name: d.name,
    confidential: d.confidential,
    tokenAccessPolicy: d.token_access_policy,
    scopes: d.scopes,
    userAuthorizedScopes: d.user_authorized_scopes,
  }));

export const unmarshalCreatePublishedOAuthAppIntegrationSchema: z.ZodType<CreatePublishedOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    app_id: z.string().optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    appId: d.app_id,
    tokenAccessPolicy: d.token_access_policy,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalCreatePublishedOAuthAppIntegration_ResponseSchema: z.ZodType<CreatePublishedOAuthAppIntegration_Response> = z
  .object({
    integration_id: z.string().optional(),
  })
  .transform(d => ({
    integrationId: d.integration_id,
  }));

export const unmarshalCustomOAuthAppIntegrationSchema: z.ZodType<CustomOAuthAppIntegration> = z
  .object({
    integration_id: z.string().optional(),
    client_id: z.string().optional(),
    redirect_urls: z.array(z.string()).optional(),
    name: z.string().optional(),
    confidential: z.boolean().optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    created_by: z.number().optional(),
    create_time: z.string().optional(),
    creator_username: z.string().optional(),
    user_authorized_scopes: z.array(z.string()).optional(),
    principal_id: z.number().optional(),
  })
  .transform(d => ({
    integrationId: d.integration_id,
    clientId: d.client_id,
    redirectUrls: d.redirect_urls,
    name: d.name,
    confidential: d.confidential,
    tokenAccessPolicy: d.token_access_policy,
    scopes: d.scopes,
    createdBy: d.created_by,
    createTime: d.create_time,
    creatorUsername: d.creator_username,
    userAuthorizedScopes: d.user_authorized_scopes,
    principalId: d.principal_id,
  }));

export const unmarshalCustomOAuthAppIntegrationSecretSchema: z.ZodType<CustomOAuthAppIntegrationSecret> = z
  .object({
    integration_id: z.string().optional(),
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    principal_id: z.number().optional(),
    client_secret_expire_time: z.string().transform(s => Temporal.Instant.from(s)).optional(),
  })
  .transform(d => ({
    integrationId: d.integration_id,
    clientId: d.client_id,
    clientSecret: d.client_secret,
    principalId: d.principal_id,
    clientSecretExpireTime: d.client_secret_expire_time,
  }));

export const unmarshalDeleteCustomOAuthAppIntegrationSchema: z.ZodType<DeleteCustomOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalDeleteCustomOAuthAppIntegration_ResponseSchema: z.ZodType<DeleteCustomOAuthAppIntegration_Response> = z
  .object({
  });

export const unmarshalDeletePublishedOAuthAppIntegrationSchema: z.ZodType<DeletePublishedOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalDeletePublishedOAuthAppIntegration_ResponseSchema: z.ZodType<DeletePublishedOAuthAppIntegration_Response> = z
  .object({
  });

export const unmarshalGetCustomOAuthAppIntegrationSchema: z.ZodType<GetCustomOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
  }));

export const unmarshalGetPublishedOAuthAppIntegrationSchema: z.ZodType<GetPublishedOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
  }));

export const unmarshalListCustomOAuthAppIntegrationsSchema: z.ZodType<ListCustomOAuthAppIntegrations> = z
  .object({
    account_id: z.string().optional(),
    page_token: z.string().optional(),
    page_size: z.number().optional(),
    include_creator_username: z.boolean().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    pageToken: d.page_token,
    pageSize: d.page_size,
    includeCreatorUsername: d.include_creator_username,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalListCustomOAuthAppIntegrations_ResponseSchema: z.ZodType<ListCustomOAuthAppIntegrations_Response> = z
  .object({
    apps: z.array(z.lazy(() => unmarshalCustomOAuthAppIntegrationSchema)).optional(),
    next_page_token: z.string().optional(),
  })
  .transform(d => ({
    apps: d.apps,
    nextPageToken: d.next_page_token,
  }));

export const unmarshalListPublishedOAuthAppIntegrationsSchema: z.ZodType<ListPublishedOAuthAppIntegrations> = z
  .object({
    account_id: z.string().optional(),
    page_token: z.string().optional(),
    page_size: z.number().optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    pageToken: d.page_token,
    pageSize: d.page_size,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalListPublishedOAuthAppIntegrations_ResponseSchema: z.ZodType<ListPublishedOAuthAppIntegrations_Response> = z
  .object({
    apps: z.array(z.lazy(() => unmarshalPublishedOAuthAppIntegrationSchema)).optional(),
    next_page_token: z.string().optional(),
  })
  .transform(d => ({
    apps: d.apps,
    nextPageToken: d.next_page_token,
  }));

export const unmarshalPublishedOAuthAppIntegrationSchema: z.ZodType<PublishedOAuthAppIntegration> = z
  .object({
    app_id: z.string().optional(),
    integration_id: z.string().optional(),
    name: z.string().optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
    created_by: z.number().optional(),
    create_time: z.string().optional(),
  })
  .transform(d => ({
    appId: d.app_id,
    integrationId: d.integration_id,
    name: d.name,
    tokenAccessPolicy: d.token_access_policy,
    createdBy: d.created_by,
    createTime: d.create_time,
  }));

export const unmarshalTokenAccessPolicySchema: z.ZodType<TokenAccessPolicy> = z
  .object({
    access_token_ttl_in_minutes: z.number().optional(),
    refresh_token_ttl_in_minutes: z.number().optional(),
    enable_single_use_refresh_tokens: z.boolean().optional(),
    absolute_session_lifetime_in_minutes: z.number().optional(),
  })
  .transform(d => ({
    accessTokenTtlInMinutes: d.access_token_ttl_in_minutes,
    refreshTokenTtlInMinutes: d.refresh_token_ttl_in_minutes,
    enableSingleUseRefreshTokens: d.enable_single_use_refresh_tokens,
    absoluteSessionLifetimeInMinutes: d.absolute_session_lifetime_in_minutes,
  }));

export const unmarshalUpdateCustomOAuthAppIntegrationSchema: z.ZodType<UpdateCustomOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
    redirect_urls: z.array(z.string()).optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    user_authorized_scopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
    redirectUrls: d.redirect_urls,
    tokenAccessPolicy: d.token_access_policy,
    scopes: d.scopes,
    userAuthorizedScopes: d.user_authorized_scopes,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalUpdateCustomOAuthAppIntegration_ResponseSchema: z.ZodType<UpdateCustomOAuthAppIntegration_Response> = z
  .object({
  });

export const unmarshalUpdatePublishedOAuthAppIntegrationSchema: z.ZodType<UpdatePublishedOAuthAppIntegration> = z
  .object({
    account_id: z.string().optional(),
    integration_id: z.string().optional(),
    token_access_policy: z.lazy(() => unmarshalTokenAccessPolicySchema).optional(),
  })
  .transform(d => ({
    accountId: d.account_id,
    integrationId: d.integration_id,
    tokenAccessPolicy: d.token_access_policy,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const unmarshalUpdatePublishedOAuthAppIntegration_ResponseSchema: z.ZodType<UpdatePublishedOAuthAppIntegration_Response> = z
  .object({
  });

export const marshalCreateCustomOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    redirectUrls: z.array(z.string()).optional(),
    name: z.string().optional(),
    confidential: z.boolean().optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    userAuthorizedScopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    redirect_urls: d.redirectUrls,
    name: d.name,
    confidential: d.confidential,
    token_access_policy: d.tokenAccessPolicy,
    scopes: d.scopes,
    user_authorized_scopes: d.userAuthorizedScopes,
  }));

export const marshalCreatePublishedOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    appId: z.string().optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    app_id: d.appId,
    token_access_policy: d.tokenAccessPolicy,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalCreatePublishedOAuthAppIntegration_ResponseSchema: z.ZodType = z
  .object({
    integrationId: z.string().optional(),
  })
  .transform(d => ({
    integration_id: d.integrationId,
  }));

export const marshalCustomOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    integrationId: z.string().optional(),
    clientId: z.string().optional(),
    redirectUrls: z.array(z.string()).optional(),
    name: z.string().optional(),
    confidential: z.boolean().optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    createdBy: z.number().optional(),
    createTime: z.string().optional(),
    creatorUsername: z.string().optional(),
    userAuthorizedScopes: z.array(z.string()).optional(),
    principalId: z.number().optional(),
  })
  .transform(d => ({
    integration_id: d.integrationId,
    client_id: d.clientId,
    redirect_urls: d.redirectUrls,
    name: d.name,
    confidential: d.confidential,
    token_access_policy: d.tokenAccessPolicy,
    scopes: d.scopes,
    created_by: d.createdBy,
    create_time: d.createTime,
    creator_username: d.creatorUsername,
    user_authorized_scopes: d.userAuthorizedScopes,
    principal_id: d.principalId,
  }));

export const marshalCustomOAuthAppIntegrationSecretSchema: z.ZodType = z
  .object({
    integrationId: z.string().optional(),
    clientId: z.string().optional(),
    clientSecret: z.string().optional(),
    principalId: z.number().optional(),
    clientSecretExpireTime: z.any().transform((d: Temporal.Instant) => d.toString()).optional(),
  })
  .transform(d => ({
    integration_id: d.integrationId,
    client_id: d.clientId,
    client_secret: d.clientSecret,
    principal_id: d.principalId,
    client_secret_expire_time: d.clientSecretExpireTime,
  }));

export const marshalDeleteCustomOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalDeleteCustomOAuthAppIntegration_ResponseSchema: z.ZodType = z
  .object({
  });

export const marshalDeletePublishedOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalDeletePublishedOAuthAppIntegration_ResponseSchema: z.ZodType = z
  .object({
  });

export const marshalGetCustomOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
  }));

export const marshalGetPublishedOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
  }));

export const marshalListCustomOAuthAppIntegrationsSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    pageToken: z.string().optional(),
    pageSize: z.number().optional(),
    includeCreatorUsername: z.boolean().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    page_token: d.pageToken,
    page_size: d.pageSize,
    include_creator_username: d.includeCreatorUsername,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalListCustomOAuthAppIntegrations_ResponseSchema: z.ZodType = z
  .object({
    apps: z.array(z.lazy(() => marshalCustomOAuthAppIntegrationSchema)).optional(),
    nextPageToken: z.string().optional(),
  })
  .transform(d => ({
    apps: d.apps,
    next_page_token: d.nextPageToken,
  }));

export const marshalListPublishedOAuthAppIntegrationsSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    pageToken: z.string().optional(),
    pageSize: z.number().optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    page_token: d.pageToken,
    page_size: d.pageSize,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalListPublishedOAuthAppIntegrations_ResponseSchema: z.ZodType = z
  .object({
    apps: z.array(z.lazy(() => marshalPublishedOAuthAppIntegrationSchema)).optional(),
    nextPageToken: z.string().optional(),
  })
  .transform(d => ({
    apps: d.apps,
    next_page_token: d.nextPageToken,
  }));

export const marshalPublishedOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    appId: z.string().optional(),
    integrationId: z.string().optional(),
    name: z.string().optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
    createdBy: z.number().optional(),
    createTime: z.string().optional(),
  })
  .transform(d => ({
    app_id: d.appId,
    integration_id: d.integrationId,
    name: d.name,
    token_access_policy: d.tokenAccessPolicy,
    created_by: d.createdBy,
    create_time: d.createTime,
  }));

export const marshalTokenAccessPolicySchema: z.ZodType = z
  .object({
    accessTokenTtlInMinutes: z.number().optional(),
    refreshTokenTtlInMinutes: z.number().optional(),
    enableSingleUseRefreshTokens: z.boolean().optional(),
    absoluteSessionLifetimeInMinutes: z.number().optional(),
  })
  .transform(d => ({
    access_token_ttl_in_minutes: d.accessTokenTtlInMinutes,
    refresh_token_ttl_in_minutes: d.refreshTokenTtlInMinutes,
    enable_single_use_refresh_tokens: d.enableSingleUseRefreshTokens,
    absolute_session_lifetime_in_minutes: d.absoluteSessionLifetimeInMinutes,
  }));

export const marshalUpdateCustomOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
    redirectUrls: z.array(z.string()).optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
    scopes: z.array(z.string()).optional(),
    userAuthorizedScopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
    redirect_urls: d.redirectUrls,
    token_access_policy: d.tokenAccessPolicy,
    scopes: d.scopes,
    user_authorized_scopes: d.userAuthorizedScopes,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalUpdateCustomOAuthAppIntegration_ResponseSchema: z.ZodType = z
  .object({
  });

export const marshalUpdatePublishedOAuthAppIntegrationSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
    tokenAccessPolicy: z.lazy(() => marshalTokenAccessPolicySchema).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
    token_access_policy: d.tokenAccessPolicy,
  }));

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export const marshalUpdatePublishedOAuthAppIntegration_ResponseSchema: z.ZodType = z
  .object({
  });
