// Code generated by genkit. DO NOT EDIT.

/** The compute endpoint type. Either `read_write` or `read_only`. */
export enum EndpointType {
  /** Default value, not used */
  ENDPOINT_TYPE_UNSPECIFIED = 'ENDPOINT_TYPE_UNSPECIFIED',
  ENDPOINT_TYPE_READ_WRITE = 'ENDPOINT_TYPE_READ_WRITE',
  ENDPOINT_TYPE_READ_ONLY = 'ENDPOINT_TYPE_READ_ONLY',
}

/** Error codes returned by Databricks APIs to indicate specific failure conditions. */
export enum ErrorCode {
  /**
   * Unknown error. This error generally should not be returned explicitly, but will be used
   * as a fallback if the error enum is missing from the message for some reason.
   * 
   * It's assigned tag 0 to follow the best practice from
   * https://developers.google.com/protocol-buffers/docs/style#enums
   * 
   * TODO(PLAT-55898): Add custom option to declare HTTP and gRPC mappings.
   * Maps to:
   * - google.rpc.Code: UNKNOWN = 2;
   * - HTTP code: 500 Internal Server Error
   */
  UNKNOWN = 'UNKNOWN',
  /**
   * Internal error. This means that some invariants expected by the underlying system have been
   * broken. This error code is reserved for serious errors, which generally cannot be resolved
   * by the user.
   * 
   * Prefer this over all kinds of detailed error messages (e.g IO_ERROR), unless there's some
   * automation that relies on the custom error code.
   * 
   * Maps to:
   * - google.rpc.Code: INTERNAL = 13;
   * - HTTP code: 500 Internal Server Error
   */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  /**
   * The service is currently unavailable. This is most likely a transient condition, which can be
   * corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent
   * operations.
   * 
   * Prefer this over SERVICE_UNDER_MAINTENANCE, WORKSPACE_TEMPORARILY_UNAVAILABLE.
   * 
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on how to pick this vs RESOURCE_EXHAUSTED.
   * 
   * Maps to:
   * - google.rpc.Code: UNAVAILABLE = 14;
   * - HTTP code: 503 Service Unavailable
   */
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Indicates that an IOException has been internally thrown.
   */
  IO_ERROR = 'IO_ERROR',
  /**
   * The request is invalid. Prefer more specific error code whenever possible.
   * Also see similar recommendation for the google.rpc.Code.FAILED_PRECONDITION.
   * 
   * Prefer this error code over MALFORMED_REQUEST, INVALID_STATE, UNPARSEABLE_HTTP_ERROR.
   * 
   * Maps to:
   * - google.rpc.Code: FAILED_PRECONDITION = 9;
   * - HTTP code: 400 Bad Request
   */
  BAD_REQUEST = 'BAD_REQUEST',
  /**
   * An external service is unavailable temporarily as it is being updated/re-deployed. Indicates
   * gateway proxy to safely retry the request.
   */
  SERVICE_UNDER_MAINTENANCE = 'SERVICE_UNDER_MAINTENANCE',
  /** A workspace is temporarily unavailable as the workspace is being re-assigned. */
  WORKSPACE_TEMPORARILY_UNAVAILABLE = 'WORKSPACE_TEMPORARILY_UNAVAILABLE',
  /**
   * The deadline expired before the operation could complete. For operations that change the state
   * of the system, this error may be returned even if the operation has completed successfully.
   * For example, a successful response from a server could have been delayed long enough for
   * the deadline to expire. When possible - implementations should make sure further processing of
   * the request is aborted, e.g. by throwing an exception instead of making the RPC request,
   * making the database query, etc.
   * 
   * Maps to:
   * - google.rpc.Code: DEADLINE_EXCEEDED = 4;
   * - HTTP code: 504 Gateway Timeout
   */
  DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED',
  /**
   * The operation was canceled by the caller. An example - client closed the connection without
   * waiting for a response.
   * 
   * Maps to:
   * - google.rpc.Code: CANCELLED = 1;
   * - HTTP code: 499 Client Closed Request
   */
  CANCELLED = 'CANCELLED',
  /**
   * The operation is rejected because of either rate limiting or resource quota,
   * such as the client has sent too many requests recently or the client has allocated too many
   * resources.
   * 
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on how to pick this vs TEMPORARILY_UNAVAILABLE.
   * 
   * Maps to:
   * - google.rpc.Code: RESOURCE_EXHAUSTED = 8;
   * - HTTP code: 429 Too Many Requests
   */
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  /**
   * The operation was aborted, typically due to a concurrency issue such as a sequencer
   * check failure, transaction abort, or transaction conflict.
   * 
   * Maps to:
   * - google.rpc.Code: ABORTED = 10;
   * - HTTP code: 409 Conflict
   */
  ABORTED = 'ABORTED',
  /**
   * Operation was performed on a resource that does not exist,
   * e.g. file or directory was not found.
   * 
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  NOT_FOUND = 'NOT_FOUND',
  /**
   * Operation was rejected due a conflict with an existing resource, e.g. attempted to create
   * file or directory that already exists.
   * 
   * Prefer this over RESOURCE_CONFLICT.
   * 
   * Maps to:
   * - google.rpc.Code: ALREADY_EXISTS = 6;
   * - HTTP code: 409 Conflict
   */
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  /**
   * The request does not have valid authentication (AuthN) credentials for the operation.
   * 
   * Prefer this over CUSTOMER_UNAUTHORIZED, unless you need to keep consistent behavior with legacy
   * code.
   * For authorization (AuthZ) errors use PERMISSION_DENIED.
   * 
   * Maps to:
   * - google.rpc.Code: UNAUTHENTICATED = 16;
   * - HTTP code: 401 Unauthorized
   */
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  /**
   * The service is currently unavailable. Please note that the unavailability may or may not be transient.
   * That means if this is a non-transient condition, retrying it does not work. If the unavailability
   * is certainly a transient condition, pleases use `TEMPORARILY_UNAVAILABLE` which signals its transient
   * nature explicitly.
   * An example of this error code’s use case is that when DNS resolution fails, the DNS resolver does
   * not know whether it is because the domain name is completely wrong (non-transient situation) or
   * the domain name is valid but the DNS server does not have an entry for this domain name yet (transient
   * situation). Hence, `UNAVAILABLE`  is suitable for this case.
   * 
   * Maps to:
   * - google.rpc.Code: UNAVAILABLE = 14;
   * - HTTP code: 503 Service Unavailable
   */
  UNAVAILABLE = 'UNAVAILABLE',
  /**
   * Supplied value for a parameter was invalid (e.g., giving a number for a string parameter).
   * 
   * Maps to:
   * - google.rpc.Code: INVALID_ARGUMENT = 3;
   * - HTTP code: 400 Bad Request
   */
  INVALID_PARAMETER_VALUE = 'INVALID_PARAMETER_VALUE',
  /**
   * Indicates that the given API endpoint does not exist. Legacy, when possible - NOT_IMPLEMENTED
   * should be used instead to indicate that API doesn't exist.
   * 
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND',
  /** Indicates that the given API request was malformed. */
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * If one or more of the inputs to a given RPC are not in a valid state for the action.
   */
  INVALID_STATE = 'INVALID_STATE',
  /**
   * The caller does not have permission to execute the specified operation.
   * PERMISSION_DENIED must not be used for rejections caused by exhausting some resource,
   * use RESOURCE_EXHAUSTED instead for those errors.
   * PERMISSION_DENIED must not be used if the caller can not be identified,
   * use CUSTOMER_UNAUTHORIZED instead for those errors.
   * This error code does not imply the request is valid or the requested entity exists or
   * satisfies other pre-conditions.
   * 
   * Maps to:
   * - google.rpc.Code: PERMISSION_DENIED = 7;
   * - HTTP code: 403 Forbidden
   */
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  /**
   * NOTE: Deprecated due to inconsistent mapping in legacy code, see
   * https://docs.google.com/document/d/17TZIKX_Y39cJMBr333lc-d5dTvvBLSu3DPUyGU5eMJg/edit?disco=AAAAzVGt6FA.
   * Prefer using NOT_FOUND or PERMISSION_DENIED.
   * 
   * If a given user/entity is trying to use a feature which has been disabled.
   * 
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  /**
   * The request does not have valid authentication (AuthN) credentials for the operation.
   * 
   * For authentication (AuthN) errors prefer using UNAUTHENTICATED, unless you need to keep
   * consistent behavior with legacy code.
   * For authorization (AuthZ) errors use PERMISSION_DENIED.
   * 
   * Important: name is confusing, this error code is for authentication (AuthN) errors, not
   * authorization (AuthZ) errors. It maps to 401 Unauthorized and suffers from the same confusing
   * naming. See https://datatracker.ietf.org/doc/html/rfc7235#section-3.1 - "[...] status code
   * indicates that the request has not been applied because it lacks valid authentication
   * credentials for the target resource. [...] If the request included authentication credentials,
   * then the 401 response indicates that authorization has been refused for those credentials."
   * 
   * Also, see https://stackoverflow.com/a/6937030/16352922, it covers it pretty well.
   * 
   * Maps to:
   * - google.rpc.Code: UNAUTHENTICATED = 16;
   * - HTTP code: 401 Unauthorized
   */
  CUSTOMER_UNAUTHORIZED = 'CUSTOMER_UNAUTHORIZED',
  /**
   * The operation is rejected because of request rate limit, for example rate limiting applied to
   * users, workspaces, IP addresses, etc.
   * 
   * Prefer a more generic RESOURCE_EXHAUSTED for the new use cases.
   * 
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on the rate limiting vs throttling.
   * 
   * Maps to:
   * - google.rpc.Code: RESOURCE_EXHAUSTED = 8;
   * - HTTP code: 429 Too Many Requests
   */
  REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED',
  /** Indicates API request was rejected due a conflict with an existing resource. */
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Indicates that the HTTP response cannot be correctly deserialized.
   * This currently is only used in DUST test clients, and not by any real service code.
   */
  UNPARSEABLE_HTTP_ERROR = 'UNPARSEABLE_HTTP_ERROR',
  /**
   * The operation is not implemented or is not supported/enabled in this service.
   * 
   * Maps to:
   * - google.rpc.Code: UNIMPLEMENTED = 12;
   * - HTTP code: 501 Not Implemented
   */
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  /**
   * Unrecoverable data loss or corruption.
   * 
   * One of the major use cases is to indicate that server failed to validate the integrity of
   * the request. This error can occur when the checksum specified in the `X-Databricks-Checksum`
   * request header (or trailer) doesn't match the actual request content checksum.
   * 
   * Note, in case of the severe corruption that results in a malformed request, the server may
   * send a generic `400 Bad Request` response rather than sending this error code.
   * 
   * Maps to:
   * - google.rpc.Code: DATA_LOSS = 15;
   * - HTTP code: 500 Internal Server Error
   */
  DATA_LOSS = 'DATA_LOSS',
  /** If the user attempts to perform an invalid state transition on a shard. */
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Unable to perform the operation because the shard was locked by some other operation.
   */
  COULD_NOT_ACQUIRE_LOCK = 'COULD_NOT_ACQUIRE_LOCK',
  /**
   * NOTE: Deprecated, prefer using ALREADY_EXISTS.
   * Unlike ALREADY_EXISTS - this maps to HTTP code 400 Bad Request due to legacy reasons,
   * remapping will be a backwards incompatible change.
   * 
   * Operation was performed on a resource that already exists.
   */
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated, prefer using NOT_FOUND - see the note for the RESOURCE_ALREADY_EXISTS,
   * because this pair of codes is related and RESOURCE_ALREADY_EXISTS has bad mapping to the HTTP
   * codes we added new error codes NOT_FOUND and ALREADY_EXISTS, and recommend to use them instead.
   * 
   * Operation was performed on a resource that does not exist.
   */
  RESOURCE_DOES_NOT_EXIST = 'RESOURCE_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_BLOCK_SIZE_EXCEEDED = 'MAX_BLOCK_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_READ_SIZE_EXCEEDED = 'MAX_READ_SIZE_EXCEEDED',
  PARTIAL_DELETE = 'PARTIAL_DELETE',
  MAX_LIST_SIZE_EXCEEDED = 'MAX_LIST_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DRY_RUN_FAILED = 'DRY_RUN_FAILED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Cluster request was rejected because it would exceed a resource limit.
   */
  RESOURCE_LIMIT_EXCEEDED = 'RESOURCE_LIMIT_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DIRECTORY_NOT_EMPTY = 'DIRECTORY_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DIRECTORY_PROTECTED = 'DIRECTORY_PROTECTED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_NOTEBOOK_SIZE_EXCEEDED = 'MAX_NOTEBOOK_SIZE_EXCEEDED',
  MAX_CHILD_NODE_SIZE_EXCEEDED = 'MAX_CHILD_NODE_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SEARCH_QUERY_TOO_LONG = 'SEARCH_QUERY_TOO_LONG',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SEARCH_QUERY_TOO_SHORT = 'SEARCH_QUERY_TOO_SHORT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST = 'MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PERMISSION_NOT_PROPAGATED = 'PERMISSION_NOT_PROPAGATED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DEPLOYMENT_TIMEOUT = 'DEPLOYMENT_TIMEOUT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_CONFLICT = 'GIT_CONFLICT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_UNKNOWN_REF = 'GIT_UNKNOWN_REF',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_SENSITIVE_TOKEN_DETECTED = 'GIT_SENSITIVE_TOKEN_DETECTED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_URL_NOT_ON_ALLOW_LIST = 'GIT_URL_NOT_ON_ALLOW_LIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_REMOTE_ERROR = 'GIT_REMOTE_ERROR',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROJECTS_OPERATION_TIMEOUT = 'PROJECTS_OPERATION_TIMEOUT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  IPYNB_FILE_IN_REPO = 'IPYNB_FILE_IN_REPO',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  INSECURE_PARTNER_RESPONSE = 'INSECURE_PARTNER_RESPONSE',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MALFORMED_PARTNER_RESPONSE = 'MALFORMED_PARTNER_RESPONSE',
  METASTORE_DOES_NOT_EXIST = 'METASTORE_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DAC_DOES_NOT_EXIST = 'DAC_DOES_NOT_EXIST',
  CATALOG_DOES_NOT_EXIST = 'CATALOG_DOES_NOT_EXIST',
  SCHEMA_DOES_NOT_EXIST = 'SCHEMA_DOES_NOT_EXIST',
  TABLE_DOES_NOT_EXIST = 'TABLE_DOES_NOT_EXIST',
  SHARE_DOES_NOT_EXIST = 'SHARE_DOES_NOT_EXIST',
  RECIPIENT_DOES_NOT_EXIST = 'RECIPIENT_DOES_NOT_EXIST',
  STORAGE_CREDENTIAL_DOES_NOT_EXIST = 'STORAGE_CREDENTIAL_DOES_NOT_EXIST',
  EXTERNAL_LOCATION_DOES_NOT_EXIST = 'EXTERNAL_LOCATION_DOES_NOT_EXIST',
  PRINCIPAL_DOES_NOT_EXIST = 'PRINCIPAL_DOES_NOT_EXIST',
  PROVIDER_DOES_NOT_EXIST = 'PROVIDER_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  METASTORE_ALREADY_EXISTS = 'METASTORE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DAC_ALREADY_EXISTS = 'DAC_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  CATALOG_ALREADY_EXISTS = 'CATALOG_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SCHEMA_ALREADY_EXISTS = 'SCHEMA_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  TABLE_ALREADY_EXISTS = 'TABLE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SHARE_ALREADY_EXISTS = 'SHARE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  RECIPIENT_ALREADY_EXISTS = 'RECIPIENT_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  STORAGE_CREDENTIAL_ALREADY_EXISTS = 'STORAGE_CREDENTIAL_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  EXTERNAL_LOCATION_ALREADY_EXISTS = 'EXTERNAL_LOCATION_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROVIDER_ALREADY_EXISTS = 'PROVIDER_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  CATALOG_NOT_EMPTY = 'CATALOG_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SCHEMA_NOT_EMPTY = 'SCHEMA_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  METASTORE_NOT_EMPTY = 'METASTORE_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROVIDER_SHARE_NOT_ACCESSIBLE = 'PROVIDER_SHARE_NOT_ACCESSIBLE',
}

/** Copied from database_table_statuses.proto to decouple SDK packages. */
export enum ProvisioningPhase {
  /** The default phase. It should not be reported by any synced tables. */
  PROVISIONING_PHASE_UNSPECIFIED = 'PROVISIONING_PHASE_UNSPECIFIED',
  /** Ingestion phase of the synced table. This is when the synced table is ingesting data from the delta table. */
  PROVISIONING_PHASE_MAIN = 'PROVISIONING_PHASE_MAIN',
  /** Index scan phase of the synced table. This is when the synced table is creating indexes on the ingested data. */
  PROVISIONING_PHASE_INDEX_SCAN = 'PROVISIONING_PHASE_INDEX_SCAN',
  /** Index sort phase of the synced table. This is when the synced table is creating indexes on the ingested data. */
  PROVISIONING_PHASE_INDEX_SORT = 'PROVISIONING_PHASE_INDEX_SORT',
}

/**
 * The state of a synced table.
 * Copied from database_table_statuses.proto to decouple SDK packages.
 */
export enum SyncedTableState {
  /** The default state. It should not be reported by any synced tables. */
  SYNCED_TABLE_STATE_UNSPECIFIED = 'SYNCED_TABLE_STATE_UNSPECIFIED',
  /**
   * The synced table has just been created and resources are being provisioned. This is also the
   * catch-all state if there is not a more suitable state to report for the synced table.
   */
  SYNCED_TABLE_PROVISIONING = 'SYNCED_TABLE_PROVISIONING',
  /** The synced table is provisioning resources for the data synchronization pipeline. */
  SYNCED_TABLE_PROVISIONING_PIPELINE_RESOURCES = 'SYNCED_TABLE_PROVISIONING_PIPELINE_RESOURCES',
  /** The synced table is executing the initial data synchronization. */
  SYNCED_TABLE_PROVISIONING_INITIAL_SNAPSHOT = 'SYNCED_TABLE_PROVISIONING_INITIAL_SNAPSHOT',
  /** The synced table is ready to serve data. */
  SYNCED_TABLE_ONLINE = 'SYNCED_TABLE_ONLINE',
  /**
   * The synced table is ready to serve data and is continuously updating. Only shown for synced
   * tables using the "Continuous" sync mode.
   */
  SYNCED_TABLE_ONLINE_CONTINUOUS_UPDATE = 'SYNCED_TABLE_ONLINE_CONTINUOUS_UPDATE',
  /**
   * The synced table is ready to serve data and an active update is in progress. Only shown for
   * synced tables using the "Triggered" sync mode.
   */
  SYNCED_TABLE_ONLINE_TRIGGERED_UPDATE = 'SYNCED_TABLE_ONLINE_TRIGGERED_UPDATE',
  /**
   * The synced table is ready to serve data and there are no active updates. Only shown for synced
   * tables using the "Triggered" sync mode.
   */
  SYNCED_TABLE_ONLINE_NO_PENDING_UPDATE = 'SYNCED_TABLE_ONLINE_NO_PENDING_UPDATE',
  /** The synced table has encountered an internal error and is not available for serving. */
  SYNCED_TABLE_OFFLINE = 'SYNCED_TABLE_OFFLINE',
  /**
   * The synced table is not available for serving because the data synchronization pipeline has
   * failed. Please review the pipeline event logs to troubleshoot.
   */
  SYNCED_TABLE_OFFLINE_FAILED = 'SYNCED_TABLE_OFFLINE_FAILED',
  /**
   * The data synchronization pipeline has encountered an error but the synced table is still
   * available for serving (potentially stale) data. Please review the pipeline event logs to
   * troubleshoot.
   */
  SYNCED_TABLE_ONLINE_PIPELINE_FAILED = 'SYNCED_TABLE_ONLINE_PIPELINE_FAILED',
  /**
   * The synced table is available for serving, and is provisioning resources for a newly started
   * data synchronization pipeline.
   */
  SYNCED_TABLE_ONLINE_UPDATING_PIPELINE_RESOURCES = 'SYNCED_TABLE_ONLINE_UPDATING_PIPELINE_RESOURCES',
}

/** The state of the branch. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum BranchStatus_State {
  /** Default value, not used. */
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  /** The branch is being created but is not yet available for querying. */
  INIT = 'INIT',
  /** The branch is being imported and is not yet available for querying. */
  IMPORTING = 'IMPORTING',
  /** The branch is being reset to a specific point in time or LSN and is not yet available for querying. */
  RESETTING = 'RESETTING',
  /** The branch is fully operational and ready for querying. */
  READY = 'READY',
  /** The branch is stored in cost-effective archival storage. Expect slow query response times. */
  ARCHIVED = 'ARCHIVED',
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum ComputeInstance_ComputeState {
  COMPUTE_STATE_UNSPECIFIED = 'COMPUTE_STATE_UNSPECIFIED',
  INIT = 'INIT',
  IDLE = 'IDLE',
  ACTIVE = 'ACTIVE',
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum ComputeInstance_ComputeType {
  COMPUTE_TYPE_UNSPECIFIED = 'COMPUTE_TYPE_UNSPECIFIED',
  /**
   * Indicates the compute is serving read-write traffic as part of a read-write endpoint. There will only be 1
   * Read-Write compute per endpoint.
   */
  READ_WRITE = 'READ_WRITE',
  /**
   * Indicates the compute is serving read-only traffic; either as part of a read-only endpoint, or as a read-replica
   * of a read-write endpoint. There can be multiple read-only computes per endpoint.
   */
  READ_ONLY = 'READ_ONLY',
  /**
   * Indicates the compute is a hot standby for a read-write endpoint, ready to be promoted to read-write if needed.
   * There can be multiple hot standbys per read-write endpoint and they do not serve traffic unless promoted.
   */
  HOT_STANDBY = 'HOT_STANDBY',
}

/** The state of the compute endpoint. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum EndpointStatus_State {
  /** Default value, not used */
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  INIT = 'INIT',
  ACTIVE = 'ACTIVE',
  IDLE = 'IDLE',
  DEGRADED = 'DEGRADED',
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum ProvisioningInfo_State {
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  PROVISIONING = 'PROVISIONING',
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
  DELETING = 'DELETING',
  UPDATING = 'UPDATING',
  DEGRADED = 'DEGRADED',
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum RequestedClaims_PermissionSet {
  PERMISSION_SET_UNSPECIFIED = 'PERMISSION_SET_UNSPECIFIED',
  READ_ONLY = 'READ_ONLY',
}

/** How the role is authenticated when connecting to Postgres. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum Role_AuthMethod {
  AUTH_METHOD_UNSPECIFIED = 'AUTH_METHOD_UNSPECIFIED',
  /** NO_LOGIN means this role cannot be used for interactive access */
  NO_LOGIN = 'NO_LOGIN',
  /** PG_PASSWORD_SCRAM_SHA_256 is a password-based authentication */
  PG_PASSWORD_SCRAM_SHA_256 = 'PG_PASSWORD_SCRAM_SHA_256',
  /**
   * LAKEBASE_OAUTH_V1 is for logging in with the managed identities like
   * the <Databricks> service principal or <Databricks> user.
   */
  LAKEBASE_OAUTH_V1 = 'LAKEBASE_OAUTH_V1',
}

/**
 * The type of the <Databricks> managed identity that this Role represents.
 * Leave empty if you wish to create a regular Postgres role not associated with a <Databricks> identity.
 */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum Role_IdentityType {
  /** Default value, not used */
  IDENTITY_TYPE_UNSPECIFIED = 'IDENTITY_TYPE_UNSPECIFIED',
  /** A user in a <Databricks> workspace. */
  USER = 'USER',
  /** A service principal in a <Databricks> workspace. */
  SERVICE_PRINCIPAL = 'SERVICE_PRINCIPAL',
  /** A group in a <Databricks> workspace. */
  GROUP = 'GROUP',
}

/** Roles that the DatabaseInstanceRole can be a member of. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum Role_MembershipRole {
  /** Indicates that the DatabaseInstanceRole is not a member of any standard, managed roles. */
  MEMBERSHIP_ROLE_UNSPECIFIED = 'MEMBERSHIP_ROLE_UNSPECIFIED',
  /** Indicates membership in DATABRICKS_SUPERUSER, the highest set of privileges exposed to customers. */
  DATABRICKS_SUPERUSER = 'DATABRICKS_SUPERUSER',
}

/** Scheduling policy of the synced table's underlying pipeline. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum SyncedTable_SyncedTableSpec_SyncedTableSchedulingPolicy {
  SYNCED_TABLE_SCHEDULING_POLICY_UNSPECIFIED = 'SYNCED_TABLE_SCHEDULING_POLICY_UNSPECIFIED',
  /**
   * Pipeline runs continuously after generating the initial data.
   * Requires the source table to have Change Data Feed (CDF) enabled.
   */
  CONTINUOUS = 'CONTINUOUS',
  /**
   * Pipeline stops after generating the initial data and can be triggered later (manually, through a cron job or through data triggers).
   * Requires the source table to have Change Data Feed (CDF) enabled.
   */
  TRIGGERED = 'TRIGGERED',
  /**
   * Pipeline stops after generating the initial data and can be triggered later (manually, through a cron job or through data triggers).
   * Successive updates always perform a full copy of the source table data (no incremental updates).
   * Does not require the source table to have Change Data Feed (CDF) enabled.
   */
  SNAPSHOT = 'SNAPSHOT',
}

export interface Branch {
  /**
   * Output only. The full resource path of the branch.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  name?: string | undefined;
  /** System-generated unique ID for the branch. */
  uid?: string | undefined;
  /**
   * The project containing this branch (API resource hierarchy).
   * Format: projects/{project_id}
   * 
   * Note: This field indicates where the branch exists in the resource hierarchy.
   * For point-in-time branching from another branch, see `status.source_branch`.
   */
  parent?: string | undefined;
  /** A timestamp indicating when the branch was created. */
  createTime?: string | undefined;
  /** A timestamp indicating when the branch was last updated. */
  updateTime?: string | undefined;
  /** The spec contains the branch configuration. */
  spec?: BranchSpec | undefined;
  /** The current status of a Branch. */
  status?: BranchStatus | undefined;
}

export interface BranchSpec {
  /**
   * The name of the source branch from which this branch was created (data lineage for point-in-time recovery).
   * If not specified, defaults to the project's default branch.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  sourceBranch?: string | undefined;
  /** The Log Sequence Number (LSN) on the source branch from which this branch was created. */
  sourceBranchLsn?: string | undefined;
  /** The point in time on the source branch from which this branch was created. */
  sourceBranchTime?: string | undefined;
  /** When set to true, protects the branch from deletion and reset. Associated compute endpoints and the project cannot be deleted while the branch is protected. */
  isProtected?: boolean | undefined;
  /** Absolute expiration timestamp. When set, the branch will expire at this time. */
  expireTime?: string | undefined;
  /** Relative time-to-live duration. When set, the branch will expire at creation_time + ttl. */
  ttl?: string | undefined;
  /**
   * Explicitly disable expiration. When set to true, the branch will not expire.
   * If set to false, the request is invalid; provide either ttl or expire_time instead.
   */
  noExpiry?: boolean | undefined;
}

export interface BranchStatus {
  /**
   * The name of the source branch from which this branch was created.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  sourceBranch?: string | undefined;
  /** The Log Sequence Number (LSN) on the source branch from which this branch was created. */
  sourceBranchLsn?: string | undefined;
  /** The point in time on the source branch from which this branch was created. */
  sourceBranchTime?: string | undefined;
  /** Whether the branch is the project's default branch. */
  default?: boolean | undefined;
  /** Whether the branch is protected. */
  isProtected?: boolean | undefined;
  /** The branch's state, indicating if it is initializing, ready for use, or archived. */
  currentState?: State | undefined;
  /** The pending state of the branch, if a state transition is in progress. */
  pendingState?: State | undefined;
  /** A timestamp indicating when the `current_state` began. */
  stateChangeTime?: string | undefined;
  /** The logical size of the branch. */
  logicalSizeBytes?: number | undefined;
  /** Absolute expiration time for the branch. Empty if expiration is disabled. */
  expireTime?: string | undefined;
  /**
   * The short identifier of the branch, suitable for showing to the users.
   * For a branch with name `projects/my-project/branches/my-branch`, the branch_id is `my-branch`.
   * 
   * Use this field when building UI components that display branches to users (e.g., a drop-down
   * selector). Prefer showing `branch_id` instead of the full resource name from `Branch.name`,
   * which follows the `projects/{project_id}/branches/{branch_id}` format and is not user-friendly.
   */
  branchId?: string | undefined;
}

export interface Catalog {
  /**
   * The full resource path of the catalog.
   * 
   * Format: "catalogs/{catalog_id}".
   */
  name?: string | undefined;
  /** System-generated unique identifier for the catalog. */
  uid?: string | undefined;
  /** The desired state of the Catalog. */
  spec?: CatalogSpec | undefined;
  /** The observed state of the Catalog. */
  status?: CatalogStatus | undefined;
  /** A timestamp indicating when the catalog was created. */
  createTime?: string | undefined;
  /** A timestamp indicating when the catalog was last updated. */
  updateTime?: string | undefined;
}

/** The desired state of the Catalog. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Catalog_CatalogSpec {
  /**
   * The name of the Postgres database inside the specified Lakebase project and branch to be associated with the UC catalog.
   * This database must already exist, unless create_database_if_missing is set to true on creation.
   * 
   * A database can only be registered with one UC catalog at a time.
   * To re-register a database with a different catalog, the existing catalog must be deleted first.
   * 
   * A child branch inherits the fact of parent's registration. This means the same-named database
   * in a child branch cannot be registered with a second catalog
   * while the parent's registration exists. To allow registering the database of a child branch,
   * drop and recreate the database on the child branch.
   * This removes the fact of parent's registration from this branch only.
   * 
   * Doing Point In Time Restore (PITR) prior to the moment before the Postgres DB was registered
   * in the Catalog drops the fact of registration of the database. So the user should avoid doing so.
   */
  postgresDatabase?: string | undefined;
  /**
   * If set to true, the specified postgres_database is created on behalf of the calling user
   * if it does not already exist. In this case, the calling user has a role created for
   * them in Postgres if they do not already have one.
   * 
   * Defaults to false, meaning that the request fails if the specified postgres_database does not already exist.
   */
  createDatabaseIfMissing?: boolean | undefined;
  /**
   * The resource path of the branch associated with the catalog.
   * 
   * Format: projects/{project_id}/branches/{branch_id}.
   */
  branch?: string | undefined;
}

/** The observed state of the Catalog. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Catalog_CatalogStatus {
  /** The name of the Postgres database associated with the catalog. */
  postgresDatabase?: string | undefined;
  /**
   * The resource path of the project associated with the catalog.
   * 
   * Format: projects/{project_id}.
   */
  project?: string | undefined;
  /**
   * The resource path of the branch associated with the catalog.
   * 
   * Format: projects/{project_id}/branches/{branch_id}.
   */
  branch?: string | undefined;
}

export interface ComputeInstance {
  /**
   * The fully qualified name for this compute instance.
   * Format: projects/*/branches/*/endpoints/*/compute-instances/*
   */
  name?: string | undefined;
  /** The unique ID for this compute. */
  computeInstanceId?: string | undefined;
  /** The current state of the compute. */
  currentState?: ComputeState | undefined;
  /** The desired pending state of the compute, if a state transition is in progress. */
  pendingState?: ComputeState | undefined;
  /** The role of this compute within the endpoint. */
  role?: ComputeType | undefined;
  /** A host scoped directly to the enclosing compute. This host is guaranteed to resolve to the specific compute instance. */
  computeHost?: string | undefined;
  /** A timestamp indicating when the compute was last started. */
  startTime?: string | undefined;
  /** A timestamp indicating when the compute was last suspended. */
  suspendTime?: string | undefined;
}

export interface CreateBranchRequest {
  /**
   * The Project where this Branch will be created.
   * Format: projects/{project_id}
   */
  parent?: string | undefined;
  /**
   * The ID to use for the Branch. This becomes the final component of the branch's resource name.
   * The ID is required and must be 1-63 characters long, start with a lowercase letter, and contain only lowercase letters, numbers, and hyphens.
   * For example, `development` becomes `projects/my-app/branches/development`.
   */
  branchId?: string | undefined;
  /** The Branch to create. */
  branch?: Branch | undefined;
}

export interface CreateCatalogRequest {
  catalog?: Catalog | undefined;
}

export interface CreateDatabaseRequest {
  /**
   * The Branch where this Database will be created.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /**
   * The ID to use for the Database, which will become the final component of
   * the database's resource name.
   * This ID becomes the database name in postgres.
   * 
   * This value should be 4-63 characters, and only use characters available in DNS names,
   * as defined by RFC-1123
   * 
   * If database_id is not specified in the request, it is generated automatically.
   */
  databaseId?: string | undefined;
  /** The desired specification of a Database. */
  database?: Database | undefined;
}

export interface CreateEndpointRequest {
  /**
   * The Branch where this Endpoint will be created.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /**
   * The ID to use for the Endpoint. This becomes the final component of the endpoint's resource name.
   * The ID is required and must be 1-63 characters long, start with a lowercase letter, and contain only lowercase letters, numbers, and hyphens.
   * For example, `primary` becomes `projects/my-app/branches/development/endpoints/primary`.
   */
  endpointId?: string | undefined;
  /** The Endpoint to create. */
  endpoint?: Endpoint | undefined;
}

export interface CreateProjectRequest {
  /**
   * The ID to use for the Project. This becomes the final component of the project's resource name.
   * The ID is required and must be 1-63 characters long, start with a lowercase letter, and contain only lowercase letters, numbers, and hyphens.
   * For example, `my-app` becomes `projects/my-app`.
   */
  projectId?: string | undefined;
  /** The Project to create. */
  project?: Project | undefined;
}

export interface CreateRoleRequest {
  /**
   * The Branch where this Role is created.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /**
   * The ID to use for the Role, which will become the final component of
   * the role's resource name.
   * This ID becomes the role in Postgres.
   * 
   * This value should be 4-63 characters, and valid characters
   * are lowercase letters, numbers, and hyphens, as defined by RFC 1123.
   * 
   * If role_id is not specified in the request, it is generated automatically.
   */
  roleId?: string | undefined;
  /** The desired specification of a Role. */
  role?: Role | undefined;
}

export interface CreateSyncedTableRequest {
  syncedTable?: SyncedTable | undefined;
}

export interface CreateTableRequest {
  table?: Table | undefined;
}

/** Database represents a Postgres database within a Branch. */
export interface Database {
  /**
   * The resource name of the database.
   * Format: projects/{project_id}/branches/{branch_id}/databases/{database_id}
   */
  name?: string | undefined;
  /**
   * The branch containing this database.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** A timestamp indicating when the database was created. */
  createTime?: string | undefined;
  /** A timestamp indicating when the database was last updated. */
  updateTime?: string | undefined;
  /** The desired state of the Database. */
  spec?: DatabaseSpec | undefined;
  /** The observed state of the Database. */
  status?: DatabaseStatus | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Database_DatabaseSpec {
  /**
   * The name of the role that owns the database.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   * 
   * To change the owner, pass valid existing Role name when updating the Database
   * 
   * A database always has an owner.
   */
  role?: string | undefined;
  /**
   * The name of the Postgres database.
   * 
   * This expects a valid Postgres identifier as specified in the link below.
   * https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
   * Required when creating the Database.
   * 
   * To rename, pass a valid postgres identifier when updating the Database.
   */
  postgresDatabase?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Database_DatabaseStatus {
  /**
   * The name of the role that owns the database.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   */
  role?: string | undefined;
  /** The name of the Postgres database. */
  postgresDatabase?: string | undefined;
}

export interface DatabaseCredential {
  /** The OAuth token that can be used as a password when connecting to a database. */
  token?: string | undefined;
  /** Timestamp in UTC of when this credential expires. */
  expireTime?: string | undefined;
}

/** Databricks Error that is returned by all Databricks APIs. */
export interface DatabricksServiceExceptionWithDetailsProto {
  errorCode?: ErrorCode | undefined;
  message?: string | undefined;
  stackTrace?: string | undefined;
  details?: Record<string, unknown>[] | undefined;
}

export interface DeleteBranchRequest {
  /**
   * The full resource path of the branch to delete.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  name?: string | undefined;
}

export interface DeleteCatalogRequest {
  /**
   * The full resource path of the catalog to delete.
   * 
   * Format: "catalogs/{catalog_id}".
   */
  name?: string | undefined;
}

export interface DeleteDatabaseRequest {
  /**
   * The resource name of the postgres database.
   * Format: projects/{project_id}/branches/{branch_id}/databases/{database_id}
   */
  name?: string | undefined;
}

export interface DeleteEndpointRequest {
  /**
   * The full resource path of the endpoint to delete.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}
   */
  name?: string | undefined;
}

export interface DeleteProjectRequest {
  /**
   * The full resource path of the project to delete.
   * Format: projects/{project_id}
   */
  name?: string | undefined;
}

export interface DeleteRoleRequest {
  /**
   * The full resource path of the role to delete.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   */
  name?: string | undefined;
  /**
   * Reassign objects. If this is set, all objects owned by the role are
   * reassigned to the role specified in this parameter.
   * 
   * NOTE: setting this requires spinning up a compute to succeed, since it involves running
   * SQL queries.
   */
  reassignOwnedTo?: string | undefined;
}

export interface DeleteSyncedTableRequest {
  /**
   * The Full resource name of the synced table, of the format "synced_tables/{catalog}.{schema}.{table}",
   * where (catalog, schema, table) are the UC entity names.
   */
  name?: string | undefined;
}

export interface DeleteTableRequest {
  /** Full three-part (catalog, schema, table) name of the table. */
  name?: string | undefined;
}

export interface DeltaTableSyncInfo {
  /** The Delta Lake commit version that was last successfully synced. */
  deltaCommitVersion?: number | undefined;
  /**
   * The timestamp when the above Delta version was committed in the source Delta table.
   * Note: This is the Delta commit time, not the time the data was written to the synced table.
   */
  deltaCommitTime?: string | undefined;
}

/** Request to disable Forward ETL */
export interface DisableForwardEtlRequest {
  /**
   * The Branch to disable Forward ETL for.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Tenant ID (dashless UUID format). */
  tenantId?: string | undefined;
  /** Timeline ID (dashless UUID format). */
  timelineId?: string | undefined;
  /** PostgreSQL database OID to disable. */
  pgDatabaseOid?: number | undefined;
  /** PostgreSQL schema OID to disable. */
  pgSchemaOid?: number | undefined;
}

/** Response to disable Forward ETL */
export interface DisableForwardEtlResponse {
  /** Whether Forward ETL was successfully disabled. */
  disabled?: boolean | undefined;
}

export interface Endpoint {
  /**
   * Output only. The full resource path of the endpoint.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}
   */
  name?: string | undefined;
  /** System-generated unique ID for the endpoint. */
  uid?: string | undefined;
  /**
   * The branch containing this endpoint (API resource hierarchy).
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** A timestamp indicating when the compute endpoint was created. */
  createTime?: string | undefined;
  /** A timestamp indicating when the compute endpoint was last updated. */
  updateTime?: string | undefined;
  /** The spec contains the compute endpoint configuration, including autoscaling limits, suspend timeout, and disabled state. */
  spec?: EndpointSpec | undefined;
  /** Current operational status of the compute endpoint. */
  status?: EndpointStatus | undefined;
}

export interface EndpointGroupSpec {
  /**
   * The minimum number of computes in the endpoint group. Currently, this must be equal to max. This must be greater
   * than or equal to 1.
   */
  min?: number | undefined;
  /**
   * The maximum number of computes in the endpoint group. Currently, this must be equal to min. Set to 1 for single
   * compute endpoints, to disable HA. To manually suspend all computes in an endpoint group, set disabled to
   * true on the EndpointSpec.
   */
  max?: number | undefined;
  /**
   * Whether to allow read-only connections to read-write endpoints. Only relevant for read-write endpoints where
   * size.max > 1.
   */
  enableReadableSecondaries?: boolean | undefined;
}

export interface EndpointGroupStatus {
  /**
   * The minimum number of computes in the endpoint group. Currently, this must be equal to max. This must be greater
   * than or equal to 1.
   */
  min?: number | undefined;
  /**
   * The maximum number of computes in the endpoint group. Currently, this must be equal to min. Set to 1 for single
   * compute endpoints, to disable HA. To manually suspend all computes in an endpoint group, set disabled to
   * true on the EndpointSpec.
   */
  max?: number | undefined;
  /**
   * Whether read-only connections to read-write endpoints are allowed. Only relevant if read replicas are configured
   * by specifying size.max > 1.
   */
  enableReadableSecondaries?: boolean | undefined;
}

/** Encapsulates various hostnames (r/w or r/o, pooled or not) for an endpoint. */
export interface EndpointHosts {
  /**
   * The hostname to connect to this endpoint. For read-write endpoints, this is a read-write hostname which connects
   * to the primary compute. For read-only endpoints, this is a read-only hostname which allows read-only operations.
   */
  host?: string | undefined;
  /**
   * An optionally defined read-only host for the endpoint, without pooling. For read-only endpoints,
   * this attribute is always defined and is equivalent to host. For read-write endpoints, this attribute is defined
   * if the enclosing endpoint is a group with greater than 1 computes configured, and has readable secondaries enabled.
   */
  readOnlyHost?: string | undefined;
  /** The read-write hostname of the compute endpoint, with pooling. This attribute is only defined for read-write endpoints. */
  readWritePooledHost?: string | undefined;
  /**
   * The read-only hostname of the compute endpoint, with pooling. This attribute is always defined for read-only endpoints,
   * and may be defined for read-write endpoints if configured with read replicas and allow read-only connections.
   */
  readOnlyPooledHost?: string | undefined;
}

/** A collection of settings for a compute endpoint. */
export interface EndpointSettings {
  /** A raw representation of Postgres settings. */
  pgSettings?: Record<string, string> | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface EndpointSettings_PgSettingsEntry {
  key?: string | undefined;
  value?: string | undefined;
}

export interface EndpointSpec {
  /** The endpoint type. A branch can only have one READ_WRITE endpoint. */
  endpointType?: EndpointType | undefined;
  /** The minimum number of Compute Units. Minimum value is 0.5. */
  autoscalingLimitMinCu?: number | undefined;
  /** The maximum number of Compute Units. Minimum value is 0.5. */
  autoscalingLimitMaxCu?: number | undefined;
  /**
   * Whether to restrict connections to the compute endpoint.
   * Enabling this option schedules a suspend compute operation.
   * A disabled compute endpoint cannot be enabled by a connection or
   * console action.
   */
  disabled?: boolean | undefined;
  /**
   * Duration of inactivity after which the compute endpoint is automatically suspended.
   * If specified should be between 60s and 604800s (1 minute to 1 week).
   */
  suspendTimeoutDuration?: string | undefined;
  /**
   * When set to true, explicitly disables automatic suspension (never suspend).
   * Should be set to true when provided.
   */
  noSuspension?: boolean | undefined;
  settings?: EndpointSettings | undefined;
  /**
   * Settings for optional HA configuration of the endpoint. If unspecified, the endpoint defaults
   * to non HA settings, with a single compute backing the endpoint (and no readable secondaries
   * for Read/Write endpoints).
   */
  group?: EndpointGroupSpec | undefined;
}

export interface EndpointStatus {
  /** The endpoint type. A branch can only have one READ_WRITE endpoint. */
  endpointType?: EndpointType | undefined;
  /** Contains host information for connecting to the endpoint. */
  hosts?: EndpointHosts | undefined;
  /** A timestamp indicating when the compute endpoint was last active. */
  lastActiveTime?: string | undefined;
  /** The minimum number of Compute Units. */
  autoscalingLimitMinCu?: number | undefined;
  /** The maximum number of Compute Units. */
  autoscalingLimitMaxCu?: number | undefined;
  currentState?: State | undefined;
  pendingState?: State | undefined;
  /**
   * Whether to restrict connections to the compute endpoint.
   * Enabling this option schedules a suspend compute operation.
   * A disabled compute endpoint cannot be enabled by a connection or
   * console action.
   */
  disabled?: boolean | undefined;
  /** Duration of inactivity after which the compute endpoint is automatically suspended. */
  suspendTimeoutDuration?: string | undefined;
  settings?: EndpointSettings | undefined;
  /** Details on the HA configuration of the endpoint. */
  group?: EndpointGroupStatus | undefined;
}

/** Forward ETL configuration */
export interface ForwardEtlConfig {
  /** Workspace ID. */
  workspaceId?: number | undefined;
  /** Tenant ID (dashless UUID format). */
  tenantId?: string | undefined;
  /** Timeline ID (dashless UUID format). */
  timelineId?: string | undefined;
  /** PostgreSQL database OID. */
  pgDatabaseOid?: number | undefined;
  /** PostgreSQL schema OID. */
  pgSchemaOid?: number | undefined;
  /** Unity Catalog catalog ID. */
  ucCatalogId?: string | undefined;
  /** Unity Catalog schema ID. */
  ucSchemaId?: string | undefined;
  /** Whether Forward ETL is enabled. */
  enabled?: boolean | undefined;
  /** Configuration creation timestamp in milliseconds since epoch. */
  createTimeMillis?: number | undefined;
  /** Configuration last update timestamp in milliseconds since epoch. */
  updateTimeMillis?: number | undefined;
}

/** Database metadata */
export interface ForwardEtlDatabase {
  /** Database name. */
  name?: string | undefined;
  /** PostgreSQL database OID. */
  oid?: number | undefined;
}

/** Forward ETL metadata response */
export interface ForwardEtlMetadata {
  /** List of databases with their PostgreSQL OIDs. */
  databases?: ForwardEtlDatabase[] | undefined;
  /** List of schemas with their PostgreSQL OIDs. */
  schemas?: ForwardEtlSchema[] | undefined;
}

/** Schema metadata */
export interface ForwardEtlSchema {
  /** Schema name. */
  name?: string | undefined;
  /** PostgreSQL schema OID. */
  oid?: number | undefined;
}

/** Forward ETL status response */
export interface ForwardEtlStatus {
  /** List of Forward ETL configurations. */
  configurations?: ForwardEtlConfig[] | undefined;
  /** Per-table replication mappings. */
  tableMappings?: ForwardEtlTableMapping[] | undefined;
}

/** Per-table replication mapping */
export interface ForwardEtlTableMapping {
  /** PostgreSQL table OID. */
  pgTableOid?: number | undefined;
  /** Unity Catalog table ID. */
  ucTableId?: string | undefined;
  /** Last synced LSN (Log Sequence Number) for this table. */
  lastSyncedLsn?: string | undefined;
  /** PostgreSQL table name. */
  pgTableName?: string | undefined;
  /** Unity Catalog table name. */
  ucTableName?: string | undefined;
  /** Whether replication is enabled for this table. */
  enabled?: boolean | undefined;
}

export interface GenerateDatabaseCredentialRequest {
  /** The returned token will be scoped to UC tables with the specified permissions. */
  claims?: RequestedClaims[] | undefined;
  /**
   * This field is not yet supported.
   * The endpoint for which this credential will be generated.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}
   */
  endpoint?: string | undefined;
  /**
   * <Databricks> workspace group name. When provided, credentials are generated
   * with permissions scoped to this group.
   */
  groupName?: string | undefined;
  /**
   * The requested time-to-live for the generated credential token.
   * Maximum allowed duration is 1 hour.
   */
  ttl?: string | undefined;
  /**
   * Timestamp in UTC of when this credential should expire.
   * Expire time should be within 1 hour of the current time.
   */
  expireTime?: string | undefined;
}

export interface GetBranchRequest {
  /**
   * The full resource path of the branch to retrieve.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  name?: string | undefined;
}

export interface GetCatalogRequest {
  name?: string | undefined;
}

export interface GetComputeInstanceRequest {
  /**
   * The full resource path of the compute instance to retrieve.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}/compute-instances/{compute_instance_id}
   */
  name?: string | undefined;
}

export interface GetDatabaseRequest {
  /**
   * The name of the Database to retrieve.
   * Format: projects/{project_id}/branches/{branch_id}/databases/{database_id}
   */
  name?: string | undefined;
}

export interface GetEndpointRequest {
  /**
   * The full resource path of the endpoint to retrieve.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}
   */
  name?: string | undefined;
}

/** Request to get Forward ETL metadata */
export interface GetForwardEtlMetadataRequest {
  /**
   * The Branch to get metadata for.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Tenant ID (dashless UUID format). */
  tenantId?: string | undefined;
  /** Timeline ID (dashless UUID format). */
  timelineId?: string | undefined;
}

/** Request to get Forward ETL status */
export interface GetForwardEtlStatusRequest {
  /**
   * The Branch to get Forward ETL status for.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Tenant ID (dashless UUID format). */
  tenantId?: string | undefined;
  /** Timeline ID (dashless UUID format). */
  timelineId?: string | undefined;
}

/** The request message for `GetOperation` method. */
export interface GetOperationRequest {
  /** The name of the operation resource. */
  name?: string | undefined;
}

export interface GetProjectRequest {
  /**
   * The full resource path of the project to retrieve.
   * Format: projects/{project_id}
   */
  name?: string | undefined;
}

export interface GetRoleRequest {
  /**
   * The full resource path of the role to retrieve.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   */
  name?: string | undefined;
}

export interface GetSyncedTableRequest {
  /**
   * The Full resource name of the synced table, of the format "synced_tables/{catalog}.{schema}.{table}",
   * where (catalog, schema, table) are the UC entity names.
   */
  name?: string | undefined;
}

export interface GetTableRequest {
  /** Full three-part (catalog, schema, table) name of the table. */
  name?: string | undefined;
}

export interface InitialEndpointSpec {
  /** Settings for HA configuration of the endpoint */
  group?: EndpointGroupSpec | undefined;
}

export interface ListBranchesRequest {
  /**
   * The Project that owns this collection of branches.
   * Format: projects/{project_id}
   */
  parent?: string | undefined;
  /** Page token from a previous response. If not provided, returns the first page. */
  pageToken?: string | undefined;
  /** Upper bound for items returned. Cannot be negative. */
  pageSize?: number | undefined;
}

export interface ListBranchesResponse {
  /** List of branches in the project. */
  branches?: Branch[] | undefined;
  /** Token to request the next page of branches. */
  nextPageToken?: string | undefined;
}

export interface ListComputeInstancesRequest {
  /** The parent, which owns the compute instances. */
  parent?: string | undefined;
  /**
   * The maximum number of compute instances to return. The service may
   * return fewer than this value.
   * 
   * If unspecified, at most 50 compute instances will be returned.
   * The maximum value is 1000; values above 1000 will be coerced to 1000.
   */
  pageSize?: number | undefined;
  /**
   * A page token, received from a previous `ListInstances` call.
   * Provide this to retrieve the subsequent page.
   * 
   * When paginating, all other parameters provided to `ListInstances` must
   * match the call that provided the page token.
   */
  pageToken?: string | undefined;
}

export interface ListComputeInstancesResponse {
  /** The compute instances from the specified endpoint. */
  computeInstances?: ComputeInstance[] | undefined;
  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
}

/** List Databases. */
export interface ListDatabasesRequest {
  /**
   * The Branch that owns this collection of databases.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Pagination token to go to the next page of Databases. Requests first page if absent. */
  pageToken?: string | undefined;
  /** Upper bound for items returned. */
  pageSize?: number | undefined;
}

export interface ListDatabasesResponse {
  /** List of databases. */
  databases?: Database[] | undefined;
  /** Pagination token to request the next page of databases. */
  nextPageToken?: string | undefined;
}

export interface ListEndpointsRequest {
  /**
   * The Branch that owns this collection of endpoints.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Page token from a previous response. If not provided, returns the first page. */
  pageToken?: string | undefined;
  /** Upper bound for items returned. Cannot be negative. */
  pageSize?: number | undefined;
}

export interface ListEndpointsResponse {
  /** List of compute endpoints in the branch. */
  endpoints?: Endpoint[] | undefined;
  /** Token to request the next page of compute endpoints. */
  nextPageToken?: string | undefined;
}

export interface ListProjectsRequest {
  /** Page token from a previous response. If not provided, returns the first page. */
  pageToken?: string | undefined;
  /** Upper bound for items returned. Cannot be negative. The maximum value is 100. */
  pageSize?: number | undefined;
}

export interface ListProjectsResponse {
  /** List of all projects in the workspace that the user has permission to access. */
  projects?: Project[] | undefined;
  /** Token to request the next page of projects. */
  nextPageToken?: string | undefined;
}

export interface ListRolesRequest {
  /**
   * The Branch that owns this collection of roles.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  /** Page token from a previous response. If not provided, returns the first page. */
  pageToken?: string | undefined;
  /** Upper bound for items returned. Cannot be negative. */
  pageSize?: number | undefined;
}

export interface ListRolesResponse {
  /** List of Postgres roles in the branch. */
  roles?: Role[] | undefined;
  /** Token to request the next page of Postgres roles. */
  nextPageToken?: string | undefined;
}

export interface NewPipelineSpec {
  /**
   * UC catalog for the pipeline to store intermediate files (checkpoints, event logs etc).
   * This needs to be a standard catalog where the user has permissions to create Delta tables.
   */
  storageCatalog?: string | undefined;
  /**
   * UC schema for the pipeline to store intermediate files (checkpoints, event logs etc).
   * This needs to be in the standard catalog where the user has permissions to create Delta tables.
   */
  storageSchema?: string | undefined;
  /** Budget policy to set on the newly created pipeline. */
  budgetPolicyId?: string | undefined;
}

/**
 * This resource represents a long-running operation that is the result of a
 * network API call.
 */
export interface Operation {
  /**
   * The server-assigned name, which is only unique within the same service that
   * originally returns it. If you use the default HTTP mapping, the
   * `name` should be a resource name ending with `operations/{unique_id}`.
   */
  name?: string | undefined;
  /**
   * Service-specific metadata associated with the operation.  It typically
   * contains progress information and common metadata such as create time.
   * Some services might not provide such metadata.
   */
  metadata?: Record<string, unknown> | undefined;
  /**
   * If the value is `false`, it means the operation is still in progress.
   * If `true`, the operation is completed, and either `error` or `response` is
   * available.
   */
  done?: boolean | undefined;
  /** The error result of the operation in case of failure or cancellation. */
  error?: DatabricksServiceExceptionWithDetailsProto | undefined;
  /** The normal, successful response of the operation. */
  response?: Record<string, unknown> | undefined;
}

export interface Project {
  /**
   * Output only. The full resource path of the project.
   * Format: projects/{project_id}
   */
  name?: string | undefined;
  /** System-generated unique ID for the project. */
  uid?: string | undefined;
  /** A timestamp indicating when the project was created. */
  createTime?: string | undefined;
  /** A timestamp indicating when the project was last updated. */
  updateTime?: string | undefined;
  /** The spec contains the project configuration, including display_name, pg_version (Postgres version), history_retention_duration, and default_endpoint_settings. */
  spec?: ProjectSpec | undefined;
  /** The current status of a Project. */
  status?: ProjectStatus | undefined;
  /**
   * Configuration settings for the initial Read/Write endpoint created inside the default branch for a newly
   * created project. If omitted, the initial endpoint created will have default settings, without high availability
   * configured. This field does not apply to any endpoints created after project creation. Use
   * spec.default_endpoint_settings to configure default settings for endpoints created after project creation.
   */
  initialEndpointSpec?: InitialEndpointSpec | undefined;
}

export interface ProjectCustomTag {
  /** The key of the custom tag. */
  key?: string | undefined;
  /** The value of the custom tag. */
  value?: string | undefined;
}

/** A collection of settings for a compute endpoint. */
export interface ProjectDefaultEndpointSettings {
  /** The minimum number of Compute Units. Minimum value is 0.5. */
  autoscalingLimitMinCu?: number | undefined;
  /** The maximum number of Compute Units. Minimum value is 0.5. */
  autoscalingLimitMaxCu?: number | undefined;
  /**
   * Duration of inactivity after which the compute endpoint is automatically suspended.
   * If specified should be between 60s and 604800s (1 minute to 1 week).
   */
  suspendTimeoutDuration?: string | undefined;
  /**
   * When set to true, explicitly disables automatic suspension (never suspend).
   * Should be set to true when provided.
   */
  noSuspension?: boolean | undefined;
  /** A raw representation of Postgres settings. */
  pgSettings?: Record<string, string> | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface ProjectDefaultEndpointSettings_PgSettingsEntry {
  key?: string | undefined;
  value?: string | undefined;
}

export interface ProjectSpec {
  /** Human-readable project name. Length should be between 1 and 256 characters. */
  displayName?: string | undefined;
  /** The major Postgres version number. Supported versions are 16 and 17. */
  pgVersion?: number | undefined;
  /** The number of seconds to retain the shared history for point in time recovery for all branches in this project. Value should be between 172800s (2 days) and 2592000s (30 days). */
  historyRetentionDuration?: string | undefined;
  defaultEndpointSettings?: ProjectDefaultEndpointSettings | undefined;
  /**
   * The desired budget policy to associate with the project.
   * See status.budget_policy_id for the policy that is actually applied to the project.
   */
  budgetPolicyId?: string | undefined;
  /**
   * Custom tags to associate with the project. Forwarded to LBM for billing and cost tracking.
   * To update tags, provide the new tag list and include "spec.custom_tags" in the update_mask.
   * To clear all tags, provide an empty list and include "spec.custom_tags" in the update_mask.
   * To preserve existing tags, omit this field from the update_mask (or use wildcard "*" which auto-excludes empty tags).
   */
  customTags?: ProjectCustomTag[] | undefined;
  /**
   * Indicates if this project should be created with workspace-scoped customer managed key (CMK) encryption enabled.
   * Since we need to do an end to end perf bench using BSS API to A/B test the performance impact of CMK encryption,
   * we need to be able to control this flag in the API. This flag will be removed once we find a better way to
   * separate the tenants or enforce workspace-level CMK encryption or migrate everyone to CMK.
   */
  workspaceKeyEncrypted?: boolean | undefined;
  /** Whether to enable PG native password login on all endpoints in this project. Defaults to true. */
  enablePgNativeLogin?: boolean | undefined;
  /**
   * The full resource path for the default branch of the project
   * Format: projects/{project_id}/branches/{branch_id}
   */
  defaultBranch?: string | undefined;
}

export interface ProjectStatus {
  /** The effective human-readable project name. */
  displayName?: string | undefined;
  /** The effective major Postgres version number. */
  pgVersion?: number | undefined;
  /** The effective number of seconds to retain the shared history for point in time recovery. */
  historyRetentionDuration?: string | undefined;
  /** The effective default endpoint settings. */
  defaultEndpointSettings?: ProjectDefaultEndpointSettings | undefined;
  /** The logical size limit for a branch. */
  branchLogicalSizeLimitBytes?: number | undefined;
  /** The current space occupied by the project in storage. */
  syntheticStorageSizeBytes?: number | undefined;
  /** The most recent time when any endpoint of this project was active. */
  computeLastActiveTime?: string | undefined;
  /** The budget policy that is applied to the project. */
  budgetPolicyId?: string | undefined;
  /** The effective custom tags associated with the project. */
  customTags?: ProjectCustomTag[] | undefined;
  /** The email of the project owner. */
  owner?: string | undefined;
  /** Whether to enable PG native password login on all endpoints in this project. */
  enablePgNativeLogin?: boolean | undefined;
  /** The full resource path of the default branch of the project */
  defaultBranch?: string | undefined;
}

/** The provisioning state of a resource in Unity Catalog. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ProvisioningInfo {}

export interface RequestedClaims {
  permissionSet?: PermissionSet | undefined;
  resources?: RequestedResource[] | undefined;
}

export interface RequestedResource {
  unspecifiedResourceName?: string | undefined;
  tableName?: string | undefined;
}

/** Role represents a Postgres role within a Branch. */
export interface Role {
  /**
   * Output only. The full resource path of the role.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   */
  name?: string | undefined;
  /**
   * The Branch where this Role exists.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  parent?: string | undefined;
  createTime?: string | undefined;
  updateTime?: string | undefined;
  /** The spec contains the role configuration, including identity type, authentication method, and role attributes. */
  spec?: RoleSpec | undefined;
  /** Current status of the role, including its identity type, authentication method, and role attributes. */
  status?: RoleStatus | undefined;
}

/**
 * Attributes that can be granted to a Postgres role. We are only implementing a subset for now, see xref:
 * https://www.postgresql.org/docs/16/sql-createrole.html
 * The values follow Postgres keyword naming e.g. CREATEDB, BYPASSRLS, etc. which is why they don't include typical
 * underscores between words.
 */
// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Role_Attributes {
  createdb?: boolean | undefined;
  createrole?: boolean | undefined;
  bypassrls?: boolean | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Role_RoleSpec {
  /** An enum value for a standard role that this role is a member of. */
  membershipRoles?: MembershipRole[] | undefined;
  /**
   * The type of role.
   * When specifying a managed-identity, the chosen role_id must be a valid:
   * 
   * * application ID for SERVICE_PRINCIPAL
   * * user email for USER
   * * group name for GROUP
   */
  identityType?: IdentityType | undefined;
  /** The desired API-exposed Postgres role attribute to associate with the role. Optional. */
  attributes?: Attributes | undefined;
  /**
   * If auth_method is left unspecified, a meaningful authentication method is derived from the identity_type:
   * * For the managed identities, OAUTH is used.
   * * For the regular postgres roles, authentication based on postgres passwords is used.
   * 
   * NOTE: this is ignored for the <Databricks> identity type GROUP,
   * and NO_LOGIN is implicitly assumed instead for the GROUP identity type.
   */
  authMethod?: AuthMethod | undefined;
  /**
   * The name of the Postgres role.
   * 
   * This expects a valid Postgres identifier as specified in the link below.
   * https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
   * 
   * Required when creating the Role.
   * 
   * If you wish to create a Postgres Role backed by a managed <Databricks> identity, then postgres_role
   * must be one of the following:
   * 
   * 1. user email for IdentityType.USER
   * 2. app ID for IdentityType.SERVICE_PRINCIPAL
   * 2. group name for IdentityType.GROUP
   */
  postgresRole?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface Role_RoleStatus {
  /** An enum value for a standard role that this role is a member of. */
  membershipRoles?: MembershipRole[] | undefined;
  /** The type of the role. */
  identityType?: IdentityType | undefined;
  /** The PG role attributes associated with the role. */
  attributes?: Attributes | undefined;
  authMethod?: AuthMethod | undefined;
  /** The name of the Postgres role. */
  postgresRole?: string | undefined;
}

export interface SyncedTable {
  /**
   * The Full resource name of the synced table
   * where (catalog, schema, table) are the UC entity names.
   * 
   * Format "synced_tables/{catalog}.{schema}.{table}",
   */
  name?: string | undefined;
  uid?: string | undefined;
  /**
   * Configuration details of the synced table, such as the source table, scheduling policy, etc.
   * This attribute is specified at creation time and most fields are returned as is on subsequent queries.
   */
  spec?: SyncedTableSpec | undefined;
  /** Synced Table data synchronization status. */
  status?: SyncedTableStatus | undefined;
  createTime?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface SyncedTable_SyncedTableSpec {
  /**
   * The Postgres database name where the synced table will be created in.
   * 
   * If this synced table is created inside a Lakebase Catalog, this attribute can be omitted on creation and is inferred
   * from the postgres_database associated with the Lakebase Catalog. If specified when inside a Lakebase Catalog, the value must match.
   * 
   * A value must be specified when creating a synced table inside a Standard Catalog.
   */
  postgresDatabase?: string | undefined;
  /**
   * The full resource name of the project associated with the table.
   * 
   * Format: "projects/{project_id}".
   */
  project?: string | undefined;
  /**
   * The full resource name the branch associated with the table.
   * 
   * Format: "projects/{project_id}/branches/{branch_id}".
   */
  branch?: string | undefined;
  /** Scheduling policy of the underlying pipeline. */
  schedulingPolicy?: SyncedTableSchedulingPolicy | undefined;
  /** Three-part (catalog, schema, table) name of the source Delta table. */
  sourceTableFullName?: string | undefined;
  /** Primary Key columns to be used for data insert/update in the destination. */
  primaryKeyColumns?: string[] | undefined;
  /** Time series key to deduplicate (tie-break) rows with the same primary key. */
  timeseriesKey?: string | undefined;
  /**
   * ID of an existing pipeline to bin-pack this synced table into.
   * At most one of existing_pipeline_id and new_pipeline_spec should be defined.
   * 
   * The pipeline used for the synced table is returned via the top level pipeline_id attribute.
   */
  existingPipelineId?: string | undefined;
  /**
   * If true, the synced table's logical database and schema resources in PG
   * will be created if they do not already exist.
   * The request will fail if this is false and the database/schema do not exist.
   * 
   * Defaults to true if omitted.
   */
  createDatabaseObjectsIfMissing?: boolean | undefined;
  /**
   * Specification for creating a new pipeline.
   * At most one of existing_pipeline_id and new_pipeline_spec should be defined.
   * 
   * The pipeline used for the synced table is returned via the top level pipeline_id attribute.
   */
  newPipelineSpec?: NewPipelineSpec | undefined;
  /**
   * When true, enables accelerated sync mode for the initial data load.
   * This significantly improves performance for large tables.
   * Requires workspace-level enablement through Lakebase Accelerated Sync preview.
   */
  acceleratedSync?: boolean | undefined;
}

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested message name.
export interface SyncedTable_SyncedTableStatus {
  /** A text description of the current state of the synced table. */
  message?: string | undefined;
  /** The state of the synced table. */
  detailedState?: SyncedTableState | undefined;
  /** Summary of the last successful synchronization from source to destination. */
  lastSync?: SyncedTablePosition | undefined;
  ongoingSyncProgress?: SyncedTablePipelineProgress | undefined;
  /** The current phase of the data synchronization pipeline. */
  provisioningPhase?: ProvisioningPhase | undefined;
  /** The last source table Delta version that was successfully synced to the synced table. */
  lastProcessedCommitVersion?: number | undefined;
  /**
   * The end timestamp of the last time any data was synchronized from the source table to the synced
   * table. This is when the data is available in the synced table.
   */
  lastSyncTime?: string | undefined;
  /** ID of the associated pipeline. */
  pipelineId?: string | undefined;
  /** The provisioning state of the synced table entity in Unity Catalog. */
  unityCatalogProvisioningState?: State | undefined;
}

/** Progress information of the Synced Table data synchronization pipeline. */
export interface SyncedTablePipelineProgress {
  /**
   * The source table Delta version that was last processed by the pipeline. The pipeline may not
   * have completely processed this version yet.
   */
  latestVersionCurrentlyProcessing?: number | undefined;
  /** The number of rows that have been synced in this update. */
  syncedRowCount?: number | undefined;
  /** The total number of rows that need to be synced in this update. This number may be an estimate. */
  totalRowCount?: number | undefined;
  /** The completion ratio of this update. This is a number between 0 and 1. */
  syncProgressCompletion?: number | undefined;
  /** The estimated time remaining to complete this update in seconds. */
  estimatedCompletionTimeSeconds?: number | undefined;
}

export interface SyncedTablePosition {
  /**
   * The starting timestamp of the most recent successful synchronization from the source table
   * to the destination (synced) table.
   * Note this is the starting timestamp of the sync operation, not the end time.
   * E.g., for a batch, this is the time when the sync operation started.
   */
  syncStartTime?: string | undefined;
  /**
   * The end timestamp of the most recent successful synchronization.
   * This is the time when the data is available in the synced table.
   */
  syncEndTime?: string | undefined;
  deltaTableSyncInfo?: DeltaTableSyncInfo | undefined;
}

/**
 * Table represents a non-synced database table in a Lakebase project.
 * Unlike SyncedTable, this does not have a data synchronization pipeline.
 */
export interface Table {
  /** Full three-part (catalog, schema, table) name of the table. */
  name?: string | undefined;
  /**
   * The project and branch scoped database to which this table belongs. Of the format:
   * projects/{project_id}/branches/{branch_id}/databases/{database_id}
   * where database_id is the name of the logical database in Postgres.
   */
  database?: string | undefined;
  /** The id of the database project associated with the table. Of the format projects/{project_id}. */
  project?: string | undefined;
  /** The id of the database branch associated with the table. Of the format projects/{project_id}/branches/{branch_id}. */
  branch?: string | undefined;
  /** REST API URL for serving data from this table. */
  tableServingUrl?: string | undefined;
}

export interface UpdateBranchRequest {
  /**
   * The Branch to update.
   * 
   * The branch's `name` field is used to identify the branch to update.
   * Format: projects/{project_id}/branches/{branch_id}
   */
  branch?: Branch | undefined;
  /** The list of fields to update. If unspecified, all fields will be updated when possible. */
  updateMask?: string | undefined;
}

export interface UpdateDatabaseRequest {
  /**
   * The Database to update.
   * 
   * The database's `name` field is used to identify the database to update.
   * Format: projects/{project_id}/branches/{branch_id}/databases/{database_id}
   */
  database?: Database | undefined;
  /** The list of fields to update. If unspecified, all fields will be updated when possible. */
  updateMask?: string | undefined;
}

export interface UpdateEndpointRequest {
  /**
   * The Endpoint to update.
   * 
   * The endpoint's `name` field is used to identify the endpoint to update.
   * Format: projects/{project_id}/branches/{branch_id}/endpoints/{endpoint_id}
   */
  endpoint?: Endpoint | undefined;
  /** The list of fields to update. If unspecified, all fields will be updated when possible. */
  updateMask?: string | undefined;
}

export interface UpdateProjectRequest {
  /**
   * The Project to update.
   * 
   * The project's `name` field is used to identify the project to update.
   * Format: projects/{project_id}
   */
  project?: Project | undefined;
  /** The list of fields to update. If unspecified, all fields will be updated when possible. */
  updateMask?: string | undefined;
}

export interface UpdateRoleRequest {
  /**
   * The Postgres Role to update.
   * 
   * The role's `name` field is used to identify the role to update.
   * Format: projects/{project_id}/branches/{branch_id}/roles/{role_id}
   */
  role?: Role | undefined;
  /**
   * The list of fields to update in Postgres Role.
   * If unspecified, all fields will be updated when possible.
   */
  updateMask?: string | undefined;
}
