// Code generated by genkit. DO NOT EDIT.

/** The compute endpoint type. Either `read_write` or `read_only`. */
enum EndpointType {
  /** Default value, not used */
  ENDPOINT_TYPE_UNSPECIFIED = 'ENDPOINT_TYPE_UNSPECIFIED',
  ENDPOINT_TYPE_READ_WRITE = 'ENDPOINT_TYPE_READ_WRITE',
  ENDPOINT_TYPE_READ_ONLY = 'ENDPOINT_TYPE_READ_ONLY',
}

/** Error codes returned by Databricks APIs to indicate specific failure conditions. */
enum ErrorCode {
  /**
   * Unknown error. This error generally should not be returned explicitly, but will be used
   * as a fallback if the error enum is missing from the message for some reason.
   *
   * It's assigned tag 0 to follow the best practice from
   * https://developers.google.com/protocol-buffers/docs/style#enums
   *
   * TODO(PLAT-55898): Add custom option to declare HTTP and gRPC mappings.
   * Maps to:
   * - google.rpc.Code: UNKNOWN = 2;
   * - HTTP code: 500 Internal Server Error
   */
  UNKNOWN = 'UNKNOWN',
  /**
   * Internal error. This means that some invariants expected by the underlying system have been
   * broken. This error code is reserved for serious errors, which generally cannot be resolved
   * by the user.
   *
   * Prefer this over all kinds of detailed error messages (e.g IO_ERROR), unless there's some
   * automation that relies on the custom error code.
   *
   * Maps to:
   * - google.rpc.Code: INTERNAL = 13;
   * - HTTP code: 500 Internal Server Error
   */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  /**
   * The service is currently unavailable. This is most likely a transient condition, which can be
   * corrected by retrying with a backoff. Note that it is not always safe to retry non-idempotent
   * operations.
   *
   * Prefer this over SERVICE_UNDER_MAINTENANCE, WORKSPACE_TEMPORARILY_UNAVAILABLE.
   *
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on how to pick this vs RESOURCE_EXHAUSTED.
   *
   * Maps to:
   * - google.rpc.Code: UNAVAILABLE = 14;
   * - HTTP code: 503 Service Unavailable
   */
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Indicates that an IOException has been internally thrown.
   */
  IO_ERROR = 'IO_ERROR',
  /**
   * The request is invalid. Prefer more specific error code whenever possible.
   * Also see similar recommendation for the google.rpc.Code.FAILED_PRECONDITION.
   *
   * Prefer this error code over MALFORMED_REQUEST, INVALID_STATE, UNPARSEABLE_HTTP_ERROR.
   *
   * Maps to:
   * - google.rpc.Code: FAILED_PRECONDITION = 9;
   * - HTTP code: 400 Bad Request
   */
  BAD_REQUEST = 'BAD_REQUEST',
  /**
   * An external service is unavailable temporarily as it is being updated/re-deployed. Indicates
   * gateway proxy to safely retry the request.
   */
  SERVICE_UNDER_MAINTENANCE = 'SERVICE_UNDER_MAINTENANCE',
  /** A workspace is temporarily unavailable as the workspace is being re-assigned. */
  WORKSPACE_TEMPORARILY_UNAVAILABLE = 'WORKSPACE_TEMPORARILY_UNAVAILABLE',
  /**
   * The deadline expired before the operation could complete. For operations that change the state
   * of the system, this error may be returned even if the operation has completed successfully.
   * For example, a successful response from a server could have been delayed long enough for
   * the deadline to expire. When possible - implementations should make sure further processing of
   * the request is aborted, e.g. by throwing an exception instead of making the RPC request,
   * making the database query, etc.
   *
   * Maps to:
   * - google.rpc.Code: DEADLINE_EXCEEDED = 4;
   * - HTTP code: 504 Gateway Timeout
   */
  DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED',
  /**
   * The operation was canceled by the caller. An example - client closed the connection without
   * waiting for a response.
   *
   * Maps to:
   * - google.rpc.Code: CANCELLED = 1;
   * - HTTP code: 499 Client Closed Request
   */
  CANCELLED = 'CANCELLED',
  /**
   * The operation is rejected because of either rate limiting or resource quota,
   * such as the client has sent too many requests recently or the client has allocated too many
   * resources.
   *
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on how to pick this vs TEMPORARILY_UNAVAILABLE.
   *
   * Maps to:
   * - google.rpc.Code: RESOURCE_EXHAUSTED = 8;
   * - HTTP code: 429 Too Many Requests
   */
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  /**
   * The operation was aborted, typically due to a concurrency issue such as a sequencer
   * check failure, transaction abort, or transaction conflict.
   *
   * Maps to:
   * - google.rpc.Code: ABORTED = 10;
   * - HTTP code: 409 Conflict
   */
  ABORTED = 'ABORTED',
  /**
   * Operation was performed on a resource that does not exist,
   * e.g. file or directory was not found.
   *
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  NOT_FOUND = 'NOT_FOUND',
  /**
   * Operation was rejected due a conflict with an existing resource, e.g. attempted to create
   * file or directory that already exists.
   *
   * Prefer this over RESOURCE_CONFLICT.
   *
   * Maps to:
   * - google.rpc.Code: ALREADY_EXISTS = 6;
   * - HTTP code: 409 Conflict
   */
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  /**
   * The request does not have valid authentication (AuthN) credentials for the operation.
   *
   * Prefer this over CUSTOMER_UNAUTHORIZED, unless you need to keep consistent behavior with legacy
   * code.
   * For authorization (AuthZ) errors use PERMISSION_DENIED.
   *
   * Maps to:
   * - google.rpc.Code: UNAUTHENTICATED = 16;
   * - HTTP code: 401 Unauthorized
   */
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  /**
   * The service is currently unavailable. Please note that the unavailability may or may not be transient.
   * That means if this is a non-transient condition, retrying it does not work. If the unavailability
   * is certainly a transient condition, pleases use `TEMPORARILY_UNAVAILABLE` which signals its transient
   * nature explicitly.
   * An example of this error code’s use case is that when DNS resolution fails, the DNS resolver does
   * not know whether it is because the domain name is completely wrong (non-transient situation) or
   * the domain name is valid but the DNS server does not have an entry for this domain name yet (transient
   * situation). Hence, `UNAVAILABLE`  is suitable for this case.
   *
   * Maps to:
   * - google.rpc.Code: UNAVAILABLE = 14;
   * - HTTP code: 503 Service Unavailable
   */
  UNAVAILABLE = 'UNAVAILABLE',
  /**
   * Supplied value for a parameter was invalid (e.g., giving a number for a string parameter).
   *
   * Maps to:
   * - google.rpc.Code: INVALID_ARGUMENT = 3;
   * - HTTP code: 400 Bad Request
   */
  INVALID_PARAMETER_VALUE = 'INVALID_PARAMETER_VALUE',
  /**
   * Indicates that the given API endpoint does not exist. Legacy, when possible - NOT_IMPLEMENTED
   * should be used instead to indicate that API doesn't exist.
   *
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND',
  /** Indicates that the given API request was malformed. */
  MALFORMED_REQUEST = 'MALFORMED_REQUEST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * If one or more of the inputs to a given RPC are not in a valid state for the action.
   */
  INVALID_STATE = 'INVALID_STATE',
  /**
   * The caller does not have permission to execute the specified operation.
   * PERMISSION_DENIED must not be used for rejections caused by exhausting some resource,
   * use RESOURCE_EXHAUSTED instead for those errors.
   * PERMISSION_DENIED must not be used if the caller can not be identified,
   * use CUSTOMER_UNAUTHORIZED instead for those errors.
   * This error code does not imply the request is valid or the requested entity exists or
   * satisfies other pre-conditions.
   *
   * Maps to:
   * - google.rpc.Code: PERMISSION_DENIED = 7;
   * - HTTP code: 403 Forbidden
   */
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  /**
   * NOTE: Deprecated due to inconsistent mapping in legacy code, see
   * https://docs.google.com/document/d/17TZIKX_Y39cJMBr333lc-d5dTvvBLSu3DPUyGU5eMJg/edit?disco=AAAAzVGt6FA.
   * Prefer using NOT_FOUND or PERMISSION_DENIED.
   *
   * If a given user/entity is trying to use a feature which has been disabled.
   *
   * Maps to:
   * - google.rpc.Code: NOT_FOUND = 5;
   * - HTTP code: 404 Not Found
   */
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  /**
   * The request does not have valid authentication (AuthN) credentials for the operation.
   *
   * For authentication (AuthN) errors prefer using UNAUTHENTICATED, unless you need to keep
   * consistent behavior with legacy code.
   * For authorization (AuthZ) errors use PERMISSION_DENIED.
   *
   * Important: name is confusing, this error code is for authentication (AuthN) errors, not
   * authorization (AuthZ) errors. It maps to 401 Unauthorized and suffers from the same confusing
   * naming. See https://datatracker.ietf.org/doc/html/rfc7235#section-3.1 - "[...] status code
   * indicates that the request has not been applied because it lacks valid authentication
   * credentials for the target resource. [...] If the request included authentication credentials,
   * then the 401 response indicates that authorization has been refused for those credentials."
   *
   * Also, see https://stackoverflow.com/a/6937030/16352922, it covers it pretty well.
   *
   * Maps to:
   * - google.rpc.Code: UNAUTHENTICATED = 16;
   * - HTTP code: 401 Unauthorized
   */
  CUSTOMER_UNAUTHORIZED = 'CUSTOMER_UNAUTHORIZED',
  /**
   * The operation is rejected because of request rate limit, for example rate limiting applied to
   * users, workspaces, IP addresses, etc.
   *
   * Prefer a more generic RESOURCE_EXHAUSTED for the new use cases.
   *
   * See https://docs.google.com/document/d/1FL8p2sbYWqBPL-UvhzI7uXAw4EoLG7Rj6PAOQWZRSOk/edit#
   * for guideline on the rate limiting vs throttling.
   *
   * Maps to:
   * - google.rpc.Code: RESOURCE_EXHAUSTED = 8;
   * - HTTP code: 429 Too Many Requests
   */
  REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED',
  /** Indicates API request was rejected due a conflict with an existing resource. */
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Indicates that the HTTP response cannot be correctly deserialized.
   * This currently is only used in DUST test clients, and not by any real service code.
   */
  UNPARSEABLE_HTTP_ERROR = 'UNPARSEABLE_HTTP_ERROR',
  /**
   * The operation is not implemented or is not supported/enabled in this service.
   *
   * Maps to:
   * - google.rpc.Code: UNIMPLEMENTED = 12;
   * - HTTP code: 501 Not Implemented
   */
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  /**
   * Unrecoverable data loss or corruption.
   *
   * One of the major use cases is to indicate that server failed to validate the integrity of
   * the request. This error can occur when the checksum specified in the `X-Databricks-Checksum`
   * request header (or trailer) doesn't match the actual request content checksum.
   *
   * Note, in case of the severe corruption that results in a malformed request, the server may
   * send a generic `400 Bad Request` response rather than sending this error code.
   *
   * Maps to:
   * - google.rpc.Code: DATA_LOSS = 15;
   * - HTTP code: 500 Internal Server Error
   */
  DATA_LOSS = 'DATA_LOSS',
  /** If the user attempts to perform an invalid state transition on a shard. */
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Unable to perform the operation because the shard was locked by some other operation.
   */
  COULD_NOT_ACQUIRE_LOCK = 'COULD_NOT_ACQUIRE_LOCK',
  /**
   * NOTE: Deprecated, prefer using ALREADY_EXISTS.
   * Unlike ALREADY_EXISTS - this maps to HTTP code 400 Bad Request due to legacy reasons,
   * remapping will be a backwards incompatible change.
   *
   * Operation was performed on a resource that already exists.
   */
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated, prefer using NOT_FOUND - see the note for the RESOURCE_ALREADY_EXISTS,
   * because this pair of codes is related and RESOURCE_ALREADY_EXISTS has bad mapping to the HTTP
   * codes we added new error codes NOT_FOUND and ALREADY_EXISTS, and recommend to use them instead.
   *
   * Operation was performed on a resource that does not exist.
   */
  RESOURCE_DOES_NOT_EXIST = 'RESOURCE_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_BLOCK_SIZE_EXCEEDED = 'MAX_BLOCK_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_READ_SIZE_EXCEEDED = 'MAX_READ_SIZE_EXCEEDED',
  PARTIAL_DELETE = 'PARTIAL_DELETE',
  MAX_LIST_SIZE_EXCEEDED = 'MAX_LIST_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DRY_RUN_FAILED = 'DRY_RUN_FAILED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   * Cluster request was rejected because it would exceed a resource limit.
   */
  RESOURCE_LIMIT_EXCEEDED = 'RESOURCE_LIMIT_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DIRECTORY_NOT_EMPTY = 'DIRECTORY_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DIRECTORY_PROTECTED = 'DIRECTORY_PROTECTED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MAX_NOTEBOOK_SIZE_EXCEEDED = 'MAX_NOTEBOOK_SIZE_EXCEEDED',
  MAX_CHILD_NODE_SIZE_EXCEEDED = 'MAX_CHILD_NODE_SIZE_EXCEEDED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SEARCH_QUERY_TOO_LONG = 'SEARCH_QUERY_TOO_LONG',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SEARCH_QUERY_TOO_SHORT = 'SEARCH_QUERY_TOO_SHORT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST = 'MANAGED_RESOURCE_GROUP_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PERMISSION_NOT_PROPAGATED = 'PERMISSION_NOT_PROPAGATED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DEPLOYMENT_TIMEOUT = 'DEPLOYMENT_TIMEOUT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_CONFLICT = 'GIT_CONFLICT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_UNKNOWN_REF = 'GIT_UNKNOWN_REF',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_SENSITIVE_TOKEN_DETECTED = 'GIT_SENSITIVE_TOKEN_DETECTED',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_URL_NOT_ON_ALLOW_LIST = 'GIT_URL_NOT_ON_ALLOW_LIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  GIT_REMOTE_ERROR = 'GIT_REMOTE_ERROR',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROJECTS_OPERATION_TIMEOUT = 'PROJECTS_OPERATION_TIMEOUT',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  IPYNB_FILE_IN_REPO = 'IPYNB_FILE_IN_REPO',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  INSECURE_PARTNER_RESPONSE = 'INSECURE_PARTNER_RESPONSE',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  MALFORMED_PARTNER_RESPONSE = 'MALFORMED_PARTNER_RESPONSE',
  METASTORE_DOES_NOT_EXIST = 'METASTORE_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DAC_DOES_NOT_EXIST = 'DAC_DOES_NOT_EXIST',
  CATALOG_DOES_NOT_EXIST = 'CATALOG_DOES_NOT_EXIST',
  SCHEMA_DOES_NOT_EXIST = 'SCHEMA_DOES_NOT_EXIST',
  TABLE_DOES_NOT_EXIST = 'TABLE_DOES_NOT_EXIST',
  SHARE_DOES_NOT_EXIST = 'SHARE_DOES_NOT_EXIST',
  RECIPIENT_DOES_NOT_EXIST = 'RECIPIENT_DOES_NOT_EXIST',
  STORAGE_CREDENTIAL_DOES_NOT_EXIST = 'STORAGE_CREDENTIAL_DOES_NOT_EXIST',
  EXTERNAL_LOCATION_DOES_NOT_EXIST = 'EXTERNAL_LOCATION_DOES_NOT_EXIST',
  PRINCIPAL_DOES_NOT_EXIST = 'PRINCIPAL_DOES_NOT_EXIST',
  PROVIDER_DOES_NOT_EXIST = 'PROVIDER_DOES_NOT_EXIST',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  METASTORE_ALREADY_EXISTS = 'METASTORE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  DAC_ALREADY_EXISTS = 'DAC_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  CATALOG_ALREADY_EXISTS = 'CATALOG_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SCHEMA_ALREADY_EXISTS = 'SCHEMA_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  TABLE_ALREADY_EXISTS = 'TABLE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SHARE_ALREADY_EXISTS = 'SHARE_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  RECIPIENT_ALREADY_EXISTS = 'RECIPIENT_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  STORAGE_CREDENTIAL_ALREADY_EXISTS = 'STORAGE_CREDENTIAL_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  EXTERNAL_LOCATION_ALREADY_EXISTS = 'EXTERNAL_LOCATION_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROVIDER_ALREADY_EXISTS = 'PROVIDER_ALREADY_EXISTS',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  CATALOG_NOT_EMPTY = 'CATALOG_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  SCHEMA_NOT_EMPTY = 'SCHEMA_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  METASTORE_NOT_EMPTY = 'METASTORE_NOT_EMPTY',
  /**
   * NOTE: Deprecated and kept to maintain backwards compatibility for public APIs that use it,
   * avoid using it in the new APIs, refer error codes listed in the http://go/error-codes.
   */
  PROVIDER_SHARE_NOT_ACCESSIBLE = 'PROVIDER_SHARE_NOT_ACCESSIBLE',
}

/** Copied from database_table_statuses.proto to decouple SDK packages. */
enum ProvisioningPhase {
  /** The default phase. It should not be reported by any synced tables. */
  PROVISIONING_PHASE_UNSPECIFIED = 'PROVISIONING_PHASE_UNSPECIFIED',
  /** Ingestion phase of the synced table. This is when the synced table is ingesting data from the delta table. */
  PROVISIONING_PHASE_MAIN = 'PROVISIONING_PHASE_MAIN',
  /** Index scan phase of the synced table. This is when the synced table is creating indexes on the ingested data. */
  PROVISIONING_PHASE_INDEX_SCAN = 'PROVISIONING_PHASE_INDEX_SCAN',
  /** Index sort phase of the synced table. This is when the synced table is creating indexes on the ingested data. */
  PROVISIONING_PHASE_INDEX_SORT = 'PROVISIONING_PHASE_INDEX_SORT',
}

/**
 * The state of a synced table.
 * Copied from database_table_statuses.proto to decouple SDK packages.
 */
enum SyncedTableState {
  /** The default state. It should not be reported by any synced tables. */
  SYNCED_TABLE_STATE_UNSPECIFIED = 'SYNCED_TABLE_STATE_UNSPECIFIED',
  /**
   * The synced table has just been created and resources are being provisioned. This is also the
   * catch-all state if there is not a more suitable state to report for the synced table.
   */
  SYNCED_TABLE_PROVISIONING = 'SYNCED_TABLE_PROVISIONING',
  /** The synced table is provisioning resources for the data synchronization pipeline. */
  SYNCED_TABLE_PROVISIONING_PIPELINE_RESOURCES = 'SYNCED_TABLE_PROVISIONING_PIPELINE_RESOURCES',
  /** The synced table is executing the initial data synchronization. */
  SYNCED_TABLE_PROVISIONING_INITIAL_SNAPSHOT = 'SYNCED_TABLE_PROVISIONING_INITIAL_SNAPSHOT',
  /** The synced table is ready to serve data. */
  SYNCED_TABLE_ONLINE = 'SYNCED_TABLE_ONLINE',
  /**
   * The synced table is ready to serve data and is continuously updating. Only shown for synced
   * tables using the "Continuous" sync mode.
   */
  SYNCED_TABLE_ONLINE_CONTINUOUS_UPDATE = 'SYNCED_TABLE_ONLINE_CONTINUOUS_UPDATE',
  /**
   * The synced table is ready to serve data and an active update is in progress. Only shown for
   * synced tables using the "Triggered" sync mode.
   */
  SYNCED_TABLE_ONLINE_TRIGGERED_UPDATE = 'SYNCED_TABLE_ONLINE_TRIGGERED_UPDATE',
  /**
   * The synced table is ready to serve data and there are no active updates. Only shown for synced
   * tables using the "Triggered" sync mode.
   */
  SYNCED_TABLE_ONLINE_NO_PENDING_UPDATE = 'SYNCED_TABLE_ONLINE_NO_PENDING_UPDATE',
  /** The synced table has encountered an internal error and is not available for serving. */
  SYNCED_TABLE_OFFLINE = 'SYNCED_TABLE_OFFLINE',
  /**
   * The synced table is not available for serving because the data synchronization pipeline has
   * failed. Please review the pipeline event logs to troubleshoot.
   */
  SYNCED_TABLE_OFFLINE_FAILED = 'SYNCED_TABLE_OFFLINE_FAILED',
  /**
   * The data synchronization pipeline has encountered an error but the synced table is still
   * available for serving (potentially stale) data. Please review the pipeline event logs to
   * troubleshoot.
   */
  SYNCED_TABLE_ONLINE_PIPELINE_FAILED = 'SYNCED_TABLE_ONLINE_PIPELINE_FAILED',
  /**
   * The synced table is available for serving, and is provisioning resources for a newly started
   * data synchronization pipeline.
   */
  SYNCED_TABLE_ONLINE_UPDATING_PIPELINE_RESOURCES = 'SYNCED_TABLE_ONLINE_UPDATING_PIPELINE_RESOURCES',
}

/** The state of the branch. */
enum BranchStatus_State {
  /** Default value, not used. */
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  /** The branch is being created but is not yet available for querying. */
  INIT = 'INIT',
  /** The branch is being imported and is not yet available for querying. */
  IMPORTING = 'IMPORTING',
  /** The branch is being reset to a specific point in time or LSN and is not yet available for querying. */
  RESETTING = 'RESETTING',
  /** The branch is fully operational and ready for querying. */
  READY = 'READY',
  /** The branch is stored in cost-effective archival storage. Expect slow query response times. */
  ARCHIVED = 'ARCHIVED',
}

enum ComputeInstance_ComputeState {
  COMPUTE_STATE_UNSPECIFIED = 'COMPUTE_STATE_UNSPECIFIED',
  INIT = 'INIT',
  IDLE = 'IDLE',
  ACTIVE = 'ACTIVE',
}

enum ComputeInstance_ComputeType {
  COMPUTE_TYPE_UNSPECIFIED = 'COMPUTE_TYPE_UNSPECIFIED',
  /**
   * Indicates the compute is serving read-write traffic as part of a read-write endpoint. There will only be 1
   * Read-Write compute per endpoint.
   */
  READ_WRITE = 'READ_WRITE',
  /**
   * Indicates the compute is serving read-only traffic; either as part of a read-only endpoint, or as a read-replica
   * of a read-write endpoint. There can be multiple read-only computes per endpoint.
   */
  READ_ONLY = 'READ_ONLY',
  /**
   * Indicates the compute is a hot standby for a read-write endpoint, ready to be promoted to read-write if needed.
   * There can be multiple hot standbys per read-write endpoint and they do not serve traffic unless promoted.
   */
  HOT_STANDBY = 'HOT_STANDBY',
}

/** The state of the compute endpoint. */
enum EndpointStatus_State {
  /** Default value, not used */
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  INIT = 'INIT',
  ACTIVE = 'ACTIVE',
  IDLE = 'IDLE',
  DEGRADED = 'DEGRADED',
}

enum ProvisioningInfo_State {
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  PROVISIONING = 'PROVISIONING',
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
  DELETING = 'DELETING',
  UPDATING = 'UPDATING',
  DEGRADED = 'DEGRADED',
}

enum RequestedClaims_PermissionSet {
  PERMISSION_SET_UNSPECIFIED = 'PERMISSION_SET_UNSPECIFIED',
  READ_ONLY = 'READ_ONLY',
}

/** How the role is authenticated when connecting to Postgres. */
enum Role_AuthMethod {
  AUTH_METHOD_UNSPECIFIED = 'AUTH_METHOD_UNSPECIFIED',
  /** NO_LOGIN means this role cannot be used for interactive access */
  NO_LOGIN = 'NO_LOGIN',
  /** PG_PASSWORD_SCRAM_SHA_256 is a password-based authentication */
  PG_PASSWORD_SCRAM_SHA_256 = 'PG_PASSWORD_SCRAM_SHA_256',
  /**
   * LAKEBASE_OAUTH_V1 is for logging in with the managed identities like
   * the <Databricks> service principal or <Databricks> user.
   */
  LAKEBASE_OAUTH_V1 = 'LAKEBASE_OAUTH_V1',
}

/**
 * The type of the <Databricks> managed identity that this Role represents.
 * Leave empty if you wish to create a regular Postgres role not associated with a <Databricks> identity.
 */
enum Role_IdentityType {
  /** Default value, not used */
  IDENTITY_TYPE_UNSPECIFIED = 'IDENTITY_TYPE_UNSPECIFIED',
  /** A user in a <Databricks> workspace. */
  USER = 'USER',
  /** A service principal in a <Databricks> workspace. */
  SERVICE_PRINCIPAL = 'SERVICE_PRINCIPAL',
  /** A group in a <Databricks> workspace. */
  GROUP = 'GROUP',
}

/** Roles that the DatabaseInstanceRole can be a member of. */
enum Role_MembershipRole {
  /** Indicates that the DatabaseInstanceRole is not a member of any standard, managed roles. */
  MEMBERSHIP_ROLE_UNSPECIFIED = 'MEMBERSHIP_ROLE_UNSPECIFIED',
  /** Indicates membership in DATABRICKS_SUPERUSER, the highest set of privileges exposed to customers. */
  DATABRICKS_SUPERUSER = 'DATABRICKS_SUPERUSER',
}

/** Scheduling policy of the synced table's underlying pipeline. */
enum SyncedTable_SyncedTableSpec_SyncedTableSchedulingPolicy {
  SYNCED_TABLE_SCHEDULING_POLICY_UNSPECIFIED = 'SYNCED_TABLE_SCHEDULING_POLICY_UNSPECIFIED',
  /**
   * Pipeline runs continuously after generating the initial data.
   * Requires the source table to have Change Data Feed (CDF) enabled.
   */
  CONTINUOUS = 'CONTINUOUS',
  /**
   * Pipeline stops after generating the initial data and can be triggered later (manually, through a cron job or through data triggers).
   * Requires the source table to have Change Data Feed (CDF) enabled.
   */
  TRIGGERED = 'TRIGGERED',
  /**
   * Pipeline stops after generating the initial data and can be triggered later (manually, through a cron job or through data triggers).
   * Successive updates always perform a full copy of the source table data (no incremental updates).
   * Does not require the source table to have Change Data Feed (CDF) enabled.
   */
  SNAPSHOT = 'SNAPSHOT',
}

interface Branch {}

interface BranchSpec {}

interface BranchStatus {}

interface Catalog {}

/** The desired state of the Catalog. */
interface Catalog_CatalogSpec {}

/** The observed state of the Catalog. */
interface Catalog_CatalogStatus {}

interface ComputeInstance {}

interface CreateBranchRequest {}

interface CreateCatalogRequest {}

interface CreateDatabaseRequest {}

interface CreateEndpointRequest {}

interface CreateProjectRequest {}

interface CreateRoleRequest {}

interface CreateSyncedTableRequest {}

interface CreateTableRequest {}

/** Database represents a Postgres database within a Branch. */
interface Database {}

interface Database_DatabaseSpec {}

interface Database_DatabaseStatus {}

interface DatabaseCredential {}

/** Databricks Error that is returned by all Databricks APIs. */
interface DatabricksServiceExceptionWithDetailsProto {}

interface DeleteBranchRequest {}

interface DeleteCatalogRequest {}

interface DeleteDatabaseRequest {}

interface DeleteEndpointRequest {}

interface DeleteProjectRequest {}

interface DeleteRoleRequest {}

interface DeleteSyncedTableRequest {}

interface DeleteTableRequest {}

interface DeltaTableSyncInfo {}

/** Request to disable Forward ETL */
interface DisableForwardEtlRequest {}

/** Response to disable Forward ETL */
interface DisableForwardEtlResponse {}

interface Endpoint {}

interface EndpointGroupSpec {}

interface EndpointGroupStatus {}

/** Encapsulates various hostnames (r/w or r/o, pooled or not) for an endpoint. */
interface EndpointHosts {}

/** A collection of settings for a compute endpoint. */
interface EndpointSettings {}

interface EndpointSettings_PgSettingsEntry {}

interface EndpointSpec {}

interface EndpointStatus {}

/** Forward ETL configuration */
interface ForwardEtlConfig {}

/** Database metadata */
interface ForwardEtlDatabase {}

/** Forward ETL metadata response */
interface ForwardEtlMetadata {}

/** Schema metadata */
interface ForwardEtlSchema {}

/** Forward ETL status response */
interface ForwardEtlStatus {}

/** Per-table replication mapping */
interface ForwardEtlTableMapping {}

interface GenerateDatabaseCredentialRequest {}

interface GetBranchRequest {}

interface GetCatalogRequest {}

interface GetComputeInstanceRequest {}

interface GetDatabaseRequest {}

interface GetEndpointRequest {}

/** Request to get Forward ETL metadata */
interface GetForwardEtlMetadataRequest {}

/** Request to get Forward ETL status */
interface GetForwardEtlStatusRequest {}

/** The request message for `GetOperation` method. */
interface GetOperationRequest {}

interface GetProjectRequest {}

interface GetRoleRequest {}

interface GetSyncedTableRequest {}

interface GetTableRequest {}

interface InitialEndpointSpec {}

interface ListBranchesRequest {}

interface ListBranchesResponse {}

interface ListComputeInstancesRequest {}

interface ListComputeInstancesResponse {}

/** List Databases. */
interface ListDatabasesRequest {}

interface ListDatabasesResponse {}

interface ListEndpointsRequest {}

interface ListEndpointsResponse {}

interface ListProjectsRequest {}

interface ListProjectsResponse {}

interface ListRolesRequest {}

interface ListRolesResponse {}

interface NewPipelineSpec {}

/**
 * This resource represents a long-running operation that is the result of a
 * network API call.
 */
interface Operation {}

interface Project {}

interface ProjectCustomTag {}

/** A collection of settings for a compute endpoint. */
interface ProjectDefaultEndpointSettings {}

interface ProjectDefaultEndpointSettings_PgSettingsEntry {}

interface ProjectSpec {}

interface ProjectStatus {}

/** The provisioning state of a resource in Unity Catalog. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface ProvisioningInfo {}

interface RequestedClaims {}

interface RequestedResource {}

/** Role represents a Postgres role within a Branch. */
interface Role {}

/**
 * Attributes that can be granted to a Postgres role. We are only implementing a subset for now, see xref:
 * https://www.postgresql.org/docs/16/sql-createrole.html
 * The values follow Postgres keyword naming e.g. CREATEDB, BYPASSRLS, etc. which is why they don't include typical
 * underscores between words.
 */
interface Role_Attributes {}

interface Role_RoleSpec {}

interface Role_RoleStatus {}

interface SyncedTable {}

interface SyncedTable_SyncedTableSpec {}

interface SyncedTable_SyncedTableStatus {}

/** Progress information of the Synced Table data synchronization pipeline. */
interface SyncedTablePipelineProgress {}

interface SyncedTablePosition {}

/**
 * Table represents a non-synced database table in a Lakebase project.
 * Unlike SyncedTable, this does not have a data synchronization pipeline.
 */
interface Table {}

interface UpdateBranchRequest {}

interface UpdateDatabaseRequest {}

interface UpdateEndpointRequest {}

interface UpdateProjectRequest {}

interface UpdateRoleRequest {}

export {
  EndpointType,
  ErrorCode,
  ProvisioningPhase,
  SyncedTableState,
  BranchStatus_State,
  ComputeInstance_ComputeState,
  ComputeInstance_ComputeType,
  EndpointStatus_State,
  ProvisioningInfo_State,
  RequestedClaims_PermissionSet,
  Role_AuthMethod,
  Role_IdentityType,
  Role_MembershipRole,
  SyncedTable_SyncedTableSpec_SyncedTableSchedulingPolicy,
};

export type {
  Branch,
  BranchSpec,
  BranchStatus,
  Catalog,
  Catalog_CatalogSpec,
  Catalog_CatalogStatus,
  ComputeInstance,
  CreateBranchRequest,
  CreateCatalogRequest,
  CreateDatabaseRequest,
  CreateEndpointRequest,
  CreateProjectRequest,
  CreateRoleRequest,
  CreateSyncedTableRequest,
  CreateTableRequest,
  Database,
  Database_DatabaseSpec,
  Database_DatabaseStatus,
  DatabaseCredential,
  DatabricksServiceExceptionWithDetailsProto,
  DeleteBranchRequest,
  DeleteCatalogRequest,
  DeleteDatabaseRequest,
  DeleteEndpointRequest,
  DeleteProjectRequest,
  DeleteRoleRequest,
  DeleteSyncedTableRequest,
  DeleteTableRequest,
  DeltaTableSyncInfo,
  DisableForwardEtlRequest,
  DisableForwardEtlResponse,
  Endpoint,
  EndpointGroupSpec,
  EndpointGroupStatus,
  EndpointHosts,
  EndpointSettings,
  EndpointSettings_PgSettingsEntry,
  EndpointSpec,
  EndpointStatus,
  ForwardEtlConfig,
  ForwardEtlDatabase,
  ForwardEtlMetadata,
  ForwardEtlSchema,
  ForwardEtlStatus,
  ForwardEtlTableMapping,
  GenerateDatabaseCredentialRequest,
  GetBranchRequest,
  GetCatalogRequest,
  GetComputeInstanceRequest,
  GetDatabaseRequest,
  GetEndpointRequest,
  GetForwardEtlMetadataRequest,
  GetForwardEtlStatusRequest,
  GetOperationRequest,
  GetProjectRequest,
  GetRoleRequest,
  GetSyncedTableRequest,
  GetTableRequest,
  InitialEndpointSpec,
  ListBranchesRequest,
  ListBranchesResponse,
  ListComputeInstancesRequest,
  ListComputeInstancesResponse,
  ListDatabasesRequest,
  ListDatabasesResponse,
  ListEndpointsRequest,
  ListEndpointsResponse,
  ListProjectsRequest,
  ListProjectsResponse,
  ListRolesRequest,
  ListRolesResponse,
  NewPipelineSpec,
  Operation,
  Project,
  ProjectCustomTag,
  ProjectDefaultEndpointSettings,
  ProjectDefaultEndpointSettings_PgSettingsEntry,
  ProjectSpec,
  ProjectStatus,
  ProvisioningInfo,
  RequestedClaims,
  RequestedResource,
  Role,
  Role_Attributes,
  Role_RoleSpec,
  Role_RoleStatus,
  SyncedTable,
  SyncedTable_SyncedTableSpec,
  SyncedTable_SyncedTableStatus,
  SyncedTablePipelineProgress,
  SyncedTablePosition,
  Table,
  UpdateBranchRequest,
  UpdateDatabaseRequest,
  UpdateEndpointRequest,
  UpdateProjectRequest,
  UpdateRoleRequest,
};
