// Code generated by genkit. DO NOT EDIT.

/**
 * LaunchStage represent the lifecycle stage of an API component. Every API
 * component is expected to progress through these stages in the following
 * order: DEVELOPMENT -> PRIVATE_PREVIEW -> PUBLIC_BETA -> PUBLIC_PREVIEW -> GA.
 */
enum LaunchStage {
  /**
   * LAUNCH_STAGE_UNSPECIFIED indicates that the launch stage is inherited
   * from the parent component(s).
   *
   * If the component has multiple parents, it inherits the parent launch stage that
   * is the further along in the DEVELOPMENT -> PRIVATE_PREVIEW -> PUBLIC_PREVIEW -> GA order.
   *
   * Example: A message without an explicit launch stage, used by a GA method
   * and a PRIVATE_PREVIEW method, will inherit the GA launch stage.
   */
  LAUNCH_STAGE_UNSPECIFIED = 'LAUNCH_STAGE_UNSPECIFIED',
  /**
   * DEVELOPMENT represents the initial stage for API components. This stage is
   * intended for internal testing and early validation.
   *
   * - API documentation: disabled
   * - Ecosystem tools:   disabled
   * - Breaking changes:  allowed
   */
  DEVELOPMENT = 'DEVELOPMENT',
  /**
   * PRIVATE_PREVIEW indicates a stage where the API is available for selected
   * customers and early feedback.
   *
   * - API documentation: disabled
   * - Ecosystem tools:   enabled
   * - Breaking changes:  allowed
   */
  PRIVATE_PREVIEW = 'PRIVATE_PREVIEW',
  /**
   * PUBLIC_BETA indicates a stage where the API is available for all customers
   * but stability is not guaranteed.
   *
   * - API documentation: enabled
   * - Ecosystem tools:   enabled
   * - Breaking changes:  allowed
   */
  PUBLIC_BETA = 'PUBLIC_BETA',
  /**
   * PUBLIC_PREVIEW signifies a stage where the API is stable and ready for
   * production use.
   *
   * - API documentation: enabled
   * - Ecosystem tools:   enabled
   * - Breaking changes:  forbidden
   */
  PUBLIC_PREVIEW = 'PUBLIC_PREVIEW',
  /**
   * GA (General Availability) indicates that the API is stable and ready
   * for production use.
   *
   * - API documentation: enabled
   * - Ecosystem tools:   enabled
   * - Breaking changes:  forbidden
   */
  GA = 'GA',
}

export {LaunchStage};
