// Code generated from API definition by Databricks SDK Generator. DO NOT EDIT.

import {z} from 'zod';

export interface CreateCustomOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  /** List of OAuth redirect urls */
  redirectUrls?: string[] | undefined;
  /** Name of the custom OAuth app */
  name?: string | undefined;
  /** This field indicates whether an OAuth client secret is required to authenticate this client. */
  confidential?: boolean | undefined;
  /** Token access policy */
  tokenAccessPolicy?: CreateTokenAccessPolicy | undefined;
  /**
   * OAuth scopes granted to the application.
   * Supported scopes: all-apis, sql, offline_access, openid, profile, email.
   */
  scopes?: string[] | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
}

export interface CreatePublishedOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  /**
   * App id of the OAuth published app integration.
   * For example power-bi, tableau-deskop
   */
  appId?: string | undefined;
  /** Token access policy */
  tokenAccessPolicy?: CreateTokenAccessPolicy | undefined;
}

export interface CreatePublishedOAuthAppIntegrationResponse {
  /** Unique integration id for the published OAuth app */
  integrationId?: string | undefined;
}

export interface CreateTokenAccessPolicy {
  /** access token time to live in minutes */
  accessTokenTtlInMinutes?: number | undefined;
  /**
   * Refresh token time to live in minutes.
   * When single-use refresh tokens are enabled, this represents the TTL of an individual refresh token.
   * If the refresh token is used before it expires, a new one is issued with a renewed individual TTL.
   */
  refreshTokenTtlInMinutes?: number | undefined;
  /**
   * Whether to enable single-use refresh tokens (refresh token rotation).
   * If this feature is enabled, upon successfully getting a new access token using a refresh token, <Databricks> will
   * issue a new refresh token along with the access token in the response and invalidate the old refresh token.
   * The client should use the new refresh token to get access tokens in future requests.
   */
  enableSingleUseRefreshTokens?: boolean | undefined;
  /**
   * Absolute OAuth session TTL in minutes. Effective only when the single-use refresh token feature is enabled.
   * This is the absolute TTL of all refresh tokens issued in one OAuth session. When a new refresh token is issued
   * during refresh token rotation, it will inherit the same absolute TTL as the old refresh token.
   * In other words, this represents the maximum amount of time a user can stay logged in without re-authenticating.
   */
  absoluteSessionLifetimeInMinutes?: number | undefined;
}

export interface CustomOAuthAppIntegration {
  /** ID of this custom app */
  integrationId?: string | undefined;
  /** The client id of the custom OAuth app */
  clientId?: string | undefined;
  /** List of OAuth redirect urls */
  redirectUrls?: string[] | undefined;
  /** The display name of the custom OAuth app */
  name?: string | undefined;
  /** This field indicates whether an OAuth client secret is required to authenticate this client. */
  confidential?: boolean | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  scopes?: string[] | undefined;
  createdBy?: bigint | undefined;
  createTime?: string | undefined;
  creatorUsername?: string | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
}

export interface CustomOAuthAppIntegrationSecret {
  /** Unique integration id for the custom OAuth app */
  integrationId?: string | undefined;
  /** OAuth client-id generated by the <Databricks> */
  clientId?: string | undefined;
  /**
   * OAuth client-secret generated by the <Databricks>.
   * If this is a confidential OAuth app client-secret will be generated.
   */
  clientSecret?: string | undefined;
}

export interface DeleteCustomOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface DeleteCustomOAuthAppIntegrationResponse {}

export interface DeletePublishedOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface DeletePublishedOAuthAppIntegrationResponse {}

export interface GetCustomOAuthAppIntegrationRequest {
  /** The account ID. */
  accountId?: string | undefined;
  /** The OAuth app integration ID. */
  integrationId?: string | undefined;
}

export interface GetPublishedOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  integrationId?: string | undefined;
}

export interface ListCustomOAuthAppIntegrationsRequest {
  accountId?: string | undefined;
  pageToken?: string | undefined;
  pageSize?: number | undefined;
  includeCreatorUsername?: boolean | undefined;
}

export interface ListCustomOAuthAppIntegrationsResponse {
  /** List of Custom OAuth App Integrations defined for the account. */
  apps?: CustomOAuthAppIntegration[] | undefined;
  nextPageToken?: string | undefined;
}

export interface ListPublishedOAuthAppIntegrationsRequest {
  accountId?: string | undefined;
  pageToken?: string | undefined;
  pageSize?: number | undefined;
}

export interface ListPublishedOAuthAppIntegrationsResponse {
  /** List of Published OAuth App Integrations defined for the account. */
  apps?: PublishedOAuthAppIntegration[] | undefined;
  nextPageToken?: string | undefined;
}

export interface ListPublishedOAuthAppsRequest {
  /** The account ID. */
  accountId?: string | undefined;
  /** A token that can be used to get the next page of results. */
  pageToken?: string | undefined;
  /** The max number of OAuth published apps to return in one page. */
  pageSize?: number | undefined;
}

export interface ListPublishedOAuthAppsResponse {
  /** List of Published OAuth Apps. */
  apps?: PublishedOAuthApp[] | undefined;
  /** A token that can be used to get the next page of results. If not present, there are no more results to show. */
  nextPageToken?: string | undefined;
}

export interface PublishedOAuthApp {
  /** Unique ID of the published OAuth app. */
  appId?: string | undefined;
  /** Client ID of the published OAuth app. It is the client_id in the OAuth flow */
  clientId?: string | undefined;
  /** The display name of the published OAuth app. */
  name?: string | undefined;
  /** Description of the published OAuth app. */
  description?: string | undefined;
  /** Whether the published OAuth app is a confidential client. It is always false for published OAuth apps. */
  isConfidentialClient?: boolean | undefined;
  /** Redirect URLs of the published OAuth app. */
  redirectUrls?: string[] | undefined;
  /** Required scopes for the published OAuth app. */
  scopes?: string[] | undefined;
}

export interface PublishedOAuthAppIntegration {
  /** App-id of the published app integration */
  appId?: string | undefined;
  /** Unique integration id for the published OAuth app */
  integrationId?: string | undefined;
  /** Display name of the published OAuth app */
  name?: string | undefined;
  /** Token access policy */
  tokenAccessPolicy?: TokenAccessPolicy | undefined;
  createdBy?: bigint | undefined;
  createTime?: string | undefined;
}

export interface TokenAccessPolicy {
  /** access token time to live in minutes */
  accessTokenTtlInMinutes?: number | undefined;
  /**
   * Refresh token time to live in minutes.
   * When single-use refresh tokens are enabled, this represents the TTL of an individual refresh token.
   * If the refresh token is used before it expires, a new one is issued with a renewed individual TTL.
   */
  refreshTokenTtlInMinutes?: number | undefined;
  /**
   * Whether to enable single-use refresh tokens (refresh token rotation).
   * If this feature is enabled, upon successfully getting a new access token using a refresh token, <Databricks> will
   * issue a new refresh token along with the access token in the response and invalidate the old refresh token.
   * The client should use the new refresh token to get access tokens in future requests.
   */
  enableSingleUseRefreshTokens?: boolean | undefined;
  /**
   * Absolute OAuth session TTL in minutes. Effective only when the single-use refresh token feature is enabled.
   * This is the absolute TTL of all refresh tokens issued in one OAuth session. When a new refresh token is issued
   * during refresh token rotation, it will inherit the same absolute TTL as the old refresh token.
   * In other words, this represents the maximum amount of time a user can stay logged in without re-authenticating.
   */
  absoluteSessionLifetimeInMinutes?: number | undefined;
}

export interface UpdateCustomOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  integrationId?: string | undefined;
  /** List of OAuth redirect urls to be updated in the custom OAuth app integration */
  redirectUrls?: string[] | undefined;
  /** Token access policy to be updated in the custom OAuth app integration */
  tokenAccessPolicy?: CreateTokenAccessPolicy | undefined;
  /**
   * List of OAuth scopes to be updated in the custom OAuth app integration, similar to redirect URIs this will fully
   * replace the existing values instead of appending
   */
  scopes?: string[] | undefined;
  /**
   * Scopes that will need to be consented by end user to mint the access token. If the user does
   * not authorize the access token will not be minted.
   * Must be a subset of scopes.
   */
  userAuthorizedScopes?: string[] | undefined;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface UpdateCustomOAuthAppIntegrationResponse {}

export interface UpdatePublishedOAuthAppIntegrationRequest {
  accountId?: string | undefined;
  integrationId?: string | undefined;
  /** Token access policy to be updated in the published OAuth app integration */
  tokenAccessPolicy?: CreateTokenAccessPolicy | undefined;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface UpdatePublishedOAuthAppIntegrationResponse {}

export const unmarshalCreatePublishedOAuthAppIntegrationResponseSchema: z.ZodType<CreatePublishedOAuthAppIntegrationResponse> =
  z
    .object({
      integration_id: z.string().optional(),
    })
    .transform(d => ({
      integrationId: d.integration_id,
    }));

export const unmarshalCustomOAuthAppIntegrationSchema: z.ZodType<CustomOAuthAppIntegration> =
  z
    .object({
      integration_id: z.string().optional(),
      client_id: z.string().optional(),
      redirect_urls: z.array(z.string()).optional(),
      name: z.string().optional(),
      confidential: z.boolean().optional(),
      token_access_policy: z
        .lazy(() => unmarshalTokenAccessPolicySchema)
        .optional(),
      scopes: z.array(z.string()).optional(),
      created_by: z
        .union([z.number(), z.bigint()])
        .transform(v => BigInt(v))
        .optional(),
      create_time: z.string().optional(),
      creator_username: z.string().optional(),
      user_authorized_scopes: z.array(z.string()).optional(),
    })
    .transform(d => ({
      integrationId: d.integration_id,
      clientId: d.client_id,
      redirectUrls: d.redirect_urls,
      name: d.name,
      confidential: d.confidential,
      tokenAccessPolicy: d.token_access_policy,
      scopes: d.scopes,
      createdBy: d.created_by,
      createTime: d.create_time,
      creatorUsername: d.creator_username,
      userAuthorizedScopes: d.user_authorized_scopes,
    }));

export const unmarshalCustomOAuthAppIntegrationSecretSchema: z.ZodType<CustomOAuthAppIntegrationSecret> =
  z
    .object({
      integration_id: z.string().optional(),
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
    })
    .transform(d => ({
      integrationId: d.integration_id,
      clientId: d.client_id,
      clientSecret: d.client_secret,
    }));

export const unmarshalDeleteCustomOAuthAppIntegrationResponseSchema: z.ZodType<DeleteCustomOAuthAppIntegrationResponse> =
  z.object({});

export const unmarshalDeletePublishedOAuthAppIntegrationResponseSchema: z.ZodType<DeletePublishedOAuthAppIntegrationResponse> =
  z.object({});

export const unmarshalListCustomOAuthAppIntegrationsResponseSchema: z.ZodType<ListCustomOAuthAppIntegrationsResponse> =
  z
    .object({
      apps: z
        .array(z.lazy(() => unmarshalCustomOAuthAppIntegrationSchema))
        .optional(),
      next_page_token: z.string().optional(),
    })
    .transform(d => ({
      apps: d.apps,
      nextPageToken: d.next_page_token,
    }));

export const unmarshalListPublishedOAuthAppIntegrationsResponseSchema: z.ZodType<ListPublishedOAuthAppIntegrationsResponse> =
  z
    .object({
      apps: z
        .array(z.lazy(() => unmarshalPublishedOAuthAppIntegrationSchema))
        .optional(),
      next_page_token: z.string().optional(),
    })
    .transform(d => ({
      apps: d.apps,
      nextPageToken: d.next_page_token,
    }));

export const unmarshalListPublishedOAuthAppsResponseSchema: z.ZodType<ListPublishedOAuthAppsResponse> =
  z
    .object({
      apps: z.array(z.lazy(() => unmarshalPublishedOAuthAppSchema)).optional(),
      next_page_token: z.string().optional(),
    })
    .transform(d => ({
      apps: d.apps,
      nextPageToken: d.next_page_token,
    }));

export const unmarshalPublishedOAuthAppSchema: z.ZodType<PublishedOAuthApp> = z
  .object({
    app_id: z.string().optional(),
    client_id: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    is_confidential_client: z.boolean().optional(),
    redirect_urls: z.array(z.string()).optional(),
    scopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    appId: d.app_id,
    clientId: d.client_id,
    name: d.name,
    description: d.description,
    isConfidentialClient: d.is_confidential_client,
    redirectUrls: d.redirect_urls,
    scopes: d.scopes,
  }));

export const unmarshalPublishedOAuthAppIntegrationSchema: z.ZodType<PublishedOAuthAppIntegration> =
  z
    .object({
      app_id: z.string().optional(),
      integration_id: z.string().optional(),
      name: z.string().optional(),
      token_access_policy: z
        .lazy(() => unmarshalTokenAccessPolicySchema)
        .optional(),
      created_by: z
        .union([z.number(), z.bigint()])
        .transform(v => BigInt(v))
        .optional(),
      create_time: z.string().optional(),
    })
    .transform(d => ({
      appId: d.app_id,
      integrationId: d.integration_id,
      name: d.name,
      tokenAccessPolicy: d.token_access_policy,
      createdBy: d.created_by,
      createTime: d.create_time,
    }));

export const unmarshalTokenAccessPolicySchema: z.ZodType<TokenAccessPolicy> = z
  .object({
    access_token_ttl_in_minutes: z.number().optional(),
    refresh_token_ttl_in_minutes: z.number().optional(),
    enable_single_use_refresh_tokens: z.boolean().optional(),
    absolute_session_lifetime_in_minutes: z.number().optional(),
  })
  .transform(d => ({
    accessTokenTtlInMinutes: d.access_token_ttl_in_minutes,
    refreshTokenTtlInMinutes: d.refresh_token_ttl_in_minutes,
    enableSingleUseRefreshTokens: d.enable_single_use_refresh_tokens,
    absoluteSessionLifetimeInMinutes: d.absolute_session_lifetime_in_minutes,
  }));

export const unmarshalUpdateCustomOAuthAppIntegrationResponseSchema: z.ZodType<UpdateCustomOAuthAppIntegrationResponse> =
  z.object({});

export const unmarshalUpdatePublishedOAuthAppIntegrationResponseSchema: z.ZodType<UpdatePublishedOAuthAppIntegrationResponse> =
  z.object({});

export const marshalCreateCustomOAuthAppIntegrationRequestSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    redirectUrls: z.array(z.string()).optional(),
    name: z.string().optional(),
    confidential: z.boolean().optional(),
    tokenAccessPolicy: z
      .lazy(() => marshalCreateTokenAccessPolicySchema)
      .optional(),
    scopes: z.array(z.string()).optional(),
    userAuthorizedScopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    redirect_urls: d.redirectUrls,
    name: d.name,
    confidential: d.confidential,
    token_access_policy: d.tokenAccessPolicy,
    scopes: d.scopes,
    user_authorized_scopes: d.userAuthorizedScopes,
  }));

export const marshalCreatePublishedOAuthAppIntegrationRequestSchema: z.ZodType =
  z
    .object({
      accountId: z.string().optional(),
      appId: z.string().optional(),
      tokenAccessPolicy: z
        .lazy(() => marshalCreateTokenAccessPolicySchema)
        .optional(),
    })
    .transform(d => ({
      account_id: d.accountId,
      app_id: d.appId,
      token_access_policy: d.tokenAccessPolicy,
    }));

export const marshalCreateTokenAccessPolicySchema: z.ZodType = z
  .object({
    accessTokenTtlInMinutes: z.number().optional(),
    refreshTokenTtlInMinutes: z.number().optional(),
    enableSingleUseRefreshTokens: z.boolean().optional(),
    absoluteSessionLifetimeInMinutes: z.number().optional(),
  })
  .transform(d => ({
    access_token_ttl_in_minutes: d.accessTokenTtlInMinutes,
    refresh_token_ttl_in_minutes: d.refreshTokenTtlInMinutes,
    enable_single_use_refresh_tokens: d.enableSingleUseRefreshTokens,
    absolute_session_lifetime_in_minutes: d.absoluteSessionLifetimeInMinutes,
  }));

export const marshalUpdateCustomOAuthAppIntegrationRequestSchema: z.ZodType = z
  .object({
    accountId: z.string().optional(),
    integrationId: z.string().optional(),
    redirectUrls: z.array(z.string()).optional(),
    tokenAccessPolicy: z
      .lazy(() => marshalCreateTokenAccessPolicySchema)
      .optional(),
    scopes: z.array(z.string()).optional(),
    userAuthorizedScopes: z.array(z.string()).optional(),
  })
  .transform(d => ({
    account_id: d.accountId,
    integration_id: d.integrationId,
    redirect_urls: d.redirectUrls,
    token_access_policy: d.tokenAccessPolicy,
    scopes: d.scopes,
    user_authorized_scopes: d.userAuthorizedScopes,
  }));

export const marshalUpdatePublishedOAuthAppIntegrationRequestSchema: z.ZodType =
  z
    .object({
      accountId: z.string().optional(),
      integrationId: z.string().optional(),
      tokenAccessPolicy: z
        .lazy(() => marshalCreateTokenAccessPolicySchema)
        .optional(),
    })
    .transform(d => ({
      account_id: d.accountId,
      integration_id: d.integrationId,
      token_access_policy: d.tokenAccessPolicy,
    }));
