import {describe, it, expect} from 'vitest';
// The INI module is internal and not exported from the barrel. We import
// directly because these tests verify the parser/writer in isolation.
import {parseIni, formatIni} from '../../src/profiles/ini';
import goIniReference from './testdata/go-ini-reference.json';

/**
 * Cross-validation against gopkg.in/ini.v1 v1.67.1.
 *
 * The reference file was generated by a Go program that parses the same
 * inputs with `ini.LoadSources(ini.LoadOptions{SpaceBeforeInlineComment: true}, ...)`
 * and serializes the section/key results to JSON. Each test case asserts
 * that our parseIni produces identical output to Go's.
 */
interface GoSection {
  name: string;
  keys: {key: string; value: string}[] | null;
}
interface GoTestCase {
  name: string;
  input: string;
  sections?: GoSection[];
  error?: string;
}

describe('parseIni (cross-validated against go-ini)', () => {
  const reference = goIniReference as GoTestCase[];

  const successCases = reference.filter(
    tc => tc.error === undefined || tc.error === ''
  );
  const errorCases = reference.filter(
    tc => tc.error !== undefined && tc.error !== ''
  );

  it.each(successCases)('$name', ({input, sections: goSections}) => {
    const result = parseIni(input);

    // Convert our Map output to the same shape as Go's JSON.
    const ourSections = [...result.entries()].map(([name, keys]) => ({
      name,
      keys:
        keys.size === 0
          ? null
          : [...keys.entries()].map(([k, v]) => ({key: k, value: v})),
    }));

    expect(ourSections).toEqual(goSections);
  });

  it.each(errorCases)('$name (error)', ({input}) => {
    expect(() => parseIni(input)).toThrow();
  });
});

describe('formatIni', () => {
  const formatCases: {
    name: string;
    data: [string, [string, string][]][];
    want: string;
  }[] = [
    {
      name: 'single section',
      data: [['test', [['host', 'https://example.com']]]],
      want: '[test]\nhost = https://example.com\n',
    },
    {
      name: 'key alignment within a section',
      data: [
        [
          'test',
          [
            ['host', 'https://example.com'],
            ['token', 'my-token'],
            ['client_id', 'my-client'],
          ],
        ],
      ],
      want: [
        '[test]',
        'host      = https://example.com',
        'token     = my-token',
        'client_id = my-client',
        '',
      ].join('\n'),
    },
    {
      name: 'blank line between sections',
      data: [
        ['first', [['host', 'https://first.com']]],
        ['second', [['host', 'https://second.com']]],
      ],
      want: [
        '[first]',
        'host = https://first.com',
        '',
        '[second]',
        'host = https://second.com',
        '',
      ].join('\n'),
    },
    {
      name: 'empty section',
      data: [['empty', []]],
      want: '[empty]\n',
    },
  ];

  it.each(formatCases)('$name', ({data, want}) => {
    const iniData = new Map(
      data.map(([name, entries]) => [name, new Map(entries)])
    );
    expect(formatIni(iniData)).toBe(want);
  });

  it('should round-trip through parse and format', () => {
    const original = [
      '[DEFAULT]',
      'host  = https://default.com',
      'token = default-token',
      '',
      '[workspace]',
      'host = https://workspace.com',
    ].join('\n');

    const parsed = parseIni(original);
    const formatted = formatIni(parsed);
    const reparsed = parseIni(formatted);

    // Values should be identical after round-trip.
    for (const [section, keys] of parsed) {
      for (const [key, value] of keys) {
        expect(reparsed.get(section)?.get(key), `${section}.${key}`).toBe(
          value
        );
      }
    }
  });
});
