// Code generated by genkit. DO NOT EDIT.

enum AibiDashboardEmbeddingAccessPolicy_AccessPolicyType {
  ACCESS_POLICY_TYPE_UNSPECIFIED = 'ACCESS_POLICY_TYPE_UNSPECIFIED',
  ALLOW_ALL_DOMAINS = 'ALLOW_ALL_DOMAINS',
  ALLOW_APPROVED_DOMAINS = 'ALLOW_APPROVED_DOMAINS',
  DENY_ALL_DOMAINS = 'DENY_ALL_DOMAINS',
}

enum ClusterAutoRestartMessage_MaintenanceWindow_DayOfWeek {
  DAY_OF_WEEK_UNSPECIFIED = 'DAY_OF_WEEK_UNSPECIFIED',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

enum ClusterAutoRestartMessage_MaintenanceWindow_WeekDayFrequency {
  WEEK_DAY_FREQUENCY_UNSPECIFIED = 'WEEK_DAY_FREQUENCY_UNSPECIFIED',
  FIRST_OF_MONTH = 'FIRST_OF_MONTH',
  SECOND_OF_MONTH = 'SECOND_OF_MONTH',
  THIRD_OF_MONTH = 'THIRD_OF_MONTH',
  FOURTH_OF_MONTH = 'FOURTH_OF_MONTH',
  FIRST_AND_THIRD_OF_MONTH = 'FIRST_AND_THIRD_OF_MONTH',
  SECOND_AND_FOURTH_OF_MONTH = 'SECOND_AND_FOURTH_OF_MONTH',
  EVERY_WEEK = 'EVERY_WEEK',
}

/**
 * ON: Grants all users in all workspaces access to the Personal Compute default policy, allowing all users to create single-machine compute resources.
 * DELEGATE: Moves access control for the Personal Compute default policy to individual workspaces and requires a workspace’s users or groups to be added to the ACLs of that workspace’s Personal Compute default policy before they will be able to create compute resources through that policy.
 */
enum PersonalComputeMessage_PersonalComputeMessageEnum {
  PERSONAL_COMPUTE_MESSAGE_ENUM_UNSPECIFIED = 'PERSONAL_COMPUTE_MESSAGE_ENUM_UNSPECIFIED',
  ON = 'ON',
  DELEGATE = 'DELEGATE',
}

enum RestrictWorkspaceAdminsMessage_Status {
  /** Default value for proto enum */
  STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED',
  /**
   * Default value for existing workspaces
   * Allows WS admins to create OBO tokens for all SPs in the workspace without explicit permissions.
   */
  ALLOW_ALL = 'ALLOW_ALL',
  /**
   * Default value for new workspaces
   * Restrict WS admins to create OBO tokens for SPs in the workspace unless corresponding permissions are provided
   */
  RESTRICT_TOKENS_AND_JOB_RUN_AS = 'RESTRICT_TOKENS_AND_JOB_RUN_AS',
}

interface AibiDashboardEmbeddingAccessPolicy {}

interface AibiDashboardEmbeddingApprovedDomains {}

interface BooleanMessage {}

interface ClusterAutoRestartMessage {}

/**
 * Contains an information about the enablement status judging (e.g. whether the enterprise tier
 * is enabled)
 * This is only additional information that MUST NOT be used to decide whether the setting is
 * enabled or not. This is intended to use only for purposes like showing an error message to
 * the customer with the additional details. For example, using these details we can check
 * why exactly the feature is disabled for this customer.
 */
interface ClusterAutoRestartMessage_EnablementDetails {}

interface ClusterAutoRestartMessage_MaintenanceWindow {}

interface ClusterAutoRestartMessage_MaintenanceWindow_WeekDayBasedSchedule {}

interface ClusterAutoRestartMessage_MaintenanceWindow_WindowStartTime {}

interface GetPublicAccountSettingRequest {}

interface GetPublicAccountUserPreferenceRequest {}

interface GetPublicWorkspaceSettingRequest {}

interface IntegerMessage {}

interface ListAccountSettingsMetadataRequest {}

interface ListAccountSettingsMetadataResponse {}

interface ListAccountUserPreferencesMetadataRequest {}

interface ListAccountUserPreferencesMetadataResponse {}

interface ListWorkspaceSettingsMetadataRequest {}

interface ListWorkspaceSettingsMetadataResponse {}

interface PatchPublicAccountSettingRequest {}

interface PatchPublicAccountUserPreferenceRequest {}

interface PatchPublicWorkspaceSettingRequest {}

interface PersonalComputeMessage {}

interface RestrictWorkspaceAdminsMessage {}

interface Setting {}

interface SettingsMetadata {}

interface StringMessage {}

/**
 * User Preference represents a user-specific setting scoped to an individual user within an account.
 * Unlike workspace or account settings that apply to all users, user preferences allow personal
 * customization (e.g., UI theme, editor preferences) without affecting other users.
 */
interface UserPreference {}

export {
  AibiDashboardEmbeddingAccessPolicy_AccessPolicyType,
  ClusterAutoRestartMessage_MaintenanceWindow_DayOfWeek,
  ClusterAutoRestartMessage_MaintenanceWindow_WeekDayFrequency,
  PersonalComputeMessage_PersonalComputeMessageEnum,
  RestrictWorkspaceAdminsMessage_Status,
};

export type {
  AibiDashboardEmbeddingAccessPolicy,
  AibiDashboardEmbeddingApprovedDomains,
  BooleanMessage,
  ClusterAutoRestartMessage,
  ClusterAutoRestartMessage_EnablementDetails,
  ClusterAutoRestartMessage_MaintenanceWindow,
  ClusterAutoRestartMessage_MaintenanceWindow_WeekDayBasedSchedule,
  ClusterAutoRestartMessage_MaintenanceWindow_WindowStartTime,
  GetPublicAccountSettingRequest,
  GetPublicAccountUserPreferenceRequest,
  GetPublicWorkspaceSettingRequest,
  IntegerMessage,
  ListAccountSettingsMetadataRequest,
  ListAccountSettingsMetadataResponse,
  ListAccountUserPreferencesMetadataRequest,
  ListAccountUserPreferencesMetadataResponse,
  ListWorkspaceSettingsMetadataRequest,
  ListWorkspaceSettingsMetadataResponse,
  PatchPublicAccountSettingRequest,
  PatchPublicAccountUserPreferenceRequest,
  PatchPublicWorkspaceSettingRequest,
  PersonalComputeMessage,
  RestrictWorkspaceAdminsMessage,
  Setting,
  SettingsMetadata,
  StringMessage,
  UserPreference,
};
