// Code generated by genkit. DO NOT EDIT.

/** The name of the base data type. This doesn't include details for complex types such as STRUCT, MAP or ARRAY. */
enum ColumnTypeName {
  BOOLEAN = 'BOOLEAN',
  BYTE = 'BYTE',
  SHORT = 'SHORT',
  INT = 'INT',
  LONG = 'LONG',
  FLOAT = 'FLOAT',
  DOUBLE = 'DOUBLE',
  DATE = 'DATE',
  TIMESTAMP = 'TIMESTAMP',
  STRING = 'STRING',
  BINARY = 'BINARY',
  DECIMAL = 'DECIMAL',
  INTERVAL = 'INTERVAL',
  ARRAY = 'ARRAY',
  STRUCT = 'STRUCT',
  MAP = 'MAP',
  CHAR = 'CHAR',
  NULL = 'NULL',
  USER_DEFINED_TYPE = 'USER_DEFINED_TYPE',
}

enum Disposition {
  FETCH_DISPOSITION_UNSPECIFIED = 'FETCH_DISPOSITION_UNSPECIFIED',
  INLINE = 'INLINE',
  EXTERNAL_LINKS = 'EXTERNAL_LINKS',
}

enum Format {
  FORMAT_UNSPECIFIED = 'FORMAT_UNSPECIFIED',
  JSON_ARRAY = 'JSON_ARRAY',
  ARROW_STREAM = 'ARROW_STREAM',
  CSV = 'CSV',
}

enum ServiceErrorCode {
  UNKNOWN = 'UNKNOWN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  IO_ERROR = 'IO_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  SERVICE_UNDER_MAINTENANCE = 'SERVICE_UNDER_MAINTENANCE',
  WORKSPACE_TEMPORARILY_UNAVAILABLE = 'WORKSPACE_TEMPORARILY_UNAVAILABLE',
  DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED',
  CANCELLED = 'CANCELLED',
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  ABORTED = 'ABORTED',
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
}

/**
 * When `wait_timeout > 0s`, the call will block up to the specified time. If the statement execution doesn't
 * finish within this time, `on_wait_timeout` determines whether the execution should continue or be canceled.
 * When set to `CONTINUE`, the statement execution continues asynchronously and the call returns a statement ID
 * which can be used for polling with :method:statementexecution/getStatement. When set to `CANCEL`,
 * the statement execution is canceled and the call returns with a `CANCELED` state.
 */
enum TimeoutAction {
  TIMEOUT_ACTION_UNSPECIFIED = 'TIMEOUT_ACTION_UNSPECIFIED',
  CONTINUE = 'CONTINUE',
  CANCEL = 'CANCEL',
}

enum StatementStatus_State {
  STATE_UNSPECIFIED = 'STATE_UNSPECIFIED',
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  CLOSED = 'CLOSED',
}

interface CancelStatementRequest {}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface CancelStatementResponse {}

interface ChunkInfo {}

interface ColumnInfo {}

interface ExecuteStatementRequest {}

interface ExternalLink {}

interface ExternalLink_HttpHeadersEntry {}

interface GetResultDataRequest {}

interface GetStatementResultRequest {}

/**
 * * A query execution can be annotated with an optional key-value pair to
 * allow users to attribute the executions by key and optional value to filter by.
 * QueryTag is the user-facing representation.
 */
interface QueryTag {}

/**
 * Contains the result data of a single chunk when using `INLINE` disposition. When using
 * `EXTERNAL_LINKS` disposition, the array `external_links` is used instead to provide
 * URLs to the result data
 * in cloud storage. Exactly one of these alternatives is used. (While the `external_links`
 * array prepares the API to return multiple links in a single response. Currently only a single
 * link is returned.)
 */
interface ResultData {}

/** The result manifest provides schema and metadata for the result set. */
interface ResultManifest {}

/** The schema is an ordered list of column descriptions. */
interface Schema {}

interface ServiceError {}

interface StatementParameter {}

interface StatementResponse {}

/** The status response includes execution state and if relevant, error information. */
interface StatementStatus {}

export {
  ColumnTypeName,
  Disposition,
  Format,
  ServiceErrorCode,
  TimeoutAction,
  StatementStatus_State,
};

export type {
  CancelStatementRequest,
  CancelStatementResponse,
  ChunkInfo,
  ColumnInfo,
  ExecuteStatementRequest,
  ExternalLink,
  ExternalLink_HttpHeadersEntry,
  GetResultDataRequest,
  GetStatementResultRequest,
  QueryTag,
  ResultData,
  ResultManifest,
  Schema,
  ServiceError,
  StatementParameter,
  StatementResponse,
  StatementStatus,
};
