// Code generated from API definition by Databricks SDK Generator. DO NOT EDIT.
import {z} from 'zod';

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum SortSpec_Field {
  /** If unspecified, the server will decide the default field to sort on. */
  FIELD_UNSPECIFIED = 'FIELD_UNSPECIFIED',
  /** Sort by policy name. */
  POLICY_NAME = 'POLICY_NAME',
}

/** A request to create a UsagePolicy. */
export interface CreateUsagePolicyRequest {
  /** A unique identifier for this request. Restricted to 36 ASCII characters. */
  requestId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /** The policy to create. `policy_id` needs to be empty as it will be generated */
  policy?: UsagePolicy | undefined;
}

export interface CustomPolicyTag {
  /**
   * The key of the tag.
   * - Must be unique among all custom tags of the same policy
   * - Cannot be “budget-policy-name”, “budget-policy-id” or "budget-policy-resolution-result" -
   * these tags are preserved.
   */
  key?: string | undefined;
  /** The value of the tag. */
  value?: string | undefined;
}

/** Deletes a usage policy */
export interface DeleteUsagePolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * Structured representation of a filter to be applied to a list of policies. All specified filters
 * will be applied in conjunction.
 */
export interface Filter {
  /**
   * The partial name of policies to be filtered on.
   * If unspecified, all policies will be returned.
   */
  policyName?: string | undefined;
  /**
   * The policy creator user id to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserId?: number | undefined;
  /**
   * The policy creator user name to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserName?: string | undefined;
}

/** Request to get a usage policy */
export interface GetUsagePolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * The limit configuration of the policy.
 * Limit configuration provide a budget policy level cost control by enforcing the limit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface LimitConfig {}

/** Request to list usage policies */
export interface ListUsagePoliciesRequest {
  /** The maximum number of usage policies to return. */
  pageSize?: number | undefined;
  /** A page token, received from a previous `ListUsagePolicies` call. */
  pageToken?: string | undefined;
  /** A filter to apply to the list of policies. */
  filterBy?: Filter | undefined;
  /** The sort specification. */
  sortSpec?: SortSpec | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/** A list of usage policies. */
export interface ListUsagePoliciesResponse {
  policies?: UsagePolicy[] | undefined;
  /** A token that can be sent as `page_token` to retrieve the next page. */
  nextPageToken?: string | undefined;
  /** A token that can be sent as `page_token` to retrieve the previous page. */
  previousPageToken?: string | undefined;
}

export interface SortSpec {
  /** The filed to sort by */
  field?: SortSpec_Field | undefined;
  /** Whether to sort in descending order. */
  descending?: boolean | undefined;
}

/** Updates a UsagePolicy. */
export interface UpdateUsagePolicyRequest {
  /** The policy to update. `creator_user_id` cannot be specified in the request. */
  policy?: UsagePolicy | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /** DEPRECATED. This is redundant field as LimitConfig is part of the UsagePolicy */
  limitConfig?: LimitConfig | undefined;
}

/** Contains the UsagePolicy details (same structure as BudgetPolicy) */
export interface UsagePolicy {
  /** The Id of the policy. This field is generated by <Databricks> and globally unique. */
  policyId?: string | undefined;
  /** The name of the policy. */
  policyName?: string | undefined;
  /** A list of tags defined by the customer. At most 20 entries are allowed per policy. */
  customTags?: CustomPolicyTag[] | undefined;
  /** List of workspaces that this usage policy will be exclusively bound to. */
  bindingWorkspaceIds?: number[] | undefined;
}

export const unmarshalCreateUsagePolicyRequestSchema = z
  .object({
    request_id: z.string().optional(),
    account_id: z.string().optional(),
    policy: z.lazy(() => unmarshalUsagePolicySchema).optional(),
  })
  .transform(d => ({
    requestId: d.request_id,
    accountId: d.account_id,
    policy: d.policy,
  }));

export const unmarshalCustomPolicyTagSchema = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const unmarshalDeleteUsagePolicyRequestSchema = z
  .object({
    policy_id: z.string().optional(),
    account_id: z.string().optional(),
  })
  .transform(d => ({
    policyId: d.policy_id,
    accountId: d.account_id,
  }));

export const unmarshalFilterSchema = z
  .object({
    policy_name: z.string().optional(),
    creator_user_id: z.number().optional(),
    creator_user_name: z.string().optional(),
  })
  .transform(d => ({
    policyName: d.policy_name,
    creatorUserId: d.creator_user_id,
    creatorUserName: d.creator_user_name,
  }));

export const unmarshalGetUsagePolicyRequestSchema = z
  .object({
    policy_id: z.string().optional(),
    account_id: z.string().optional(),
  })
  .transform(d => ({
    policyId: d.policy_id,
    accountId: d.account_id,
  }));

export const unmarshalLimitConfigSchema = z.object({});

export const unmarshalListUsagePoliciesRequestSchema = z
  .object({
    page_size: z.number().optional(),
    page_token: z.string().optional(),
    filter_by: z.lazy(() => unmarshalFilterSchema).optional(),
    sort_spec: z.lazy(() => unmarshalSortSpecSchema).optional(),
    account_id: z.string().optional(),
  })
  .transform(d => ({
    pageSize: d.page_size,
    pageToken: d.page_token,
    filterBy: d.filter_by,
    sortSpec: d.sort_spec,
    accountId: d.account_id,
  }));

export const unmarshalListUsagePoliciesResponseSchema = z
  .object({
    policies: z.array(z.lazy(() => unmarshalUsagePolicySchema)).optional(),
    next_page_token: z.string().optional(),
    previous_page_token: z.string().optional(),
  })
  .transform(d => ({
    policies: d.policies,
    nextPageToken: d.next_page_token,
    previousPageToken: d.previous_page_token,
  }));

export const unmarshalSortSpecSchema = z
  .object({
    field: z.enum(SortSpec_Field).optional(),
    descending: z.boolean().optional(),
  })
  .transform(d => ({
    field: d.field,
    descending: d.descending,
  }));

export const unmarshalUpdateUsagePolicyRequestSchema = z
  .object({
    policy: z.lazy(() => unmarshalUsagePolicySchema).optional(),
    account_id: z.string().optional(),
    limit_config: z.lazy(() => unmarshalLimitConfigSchema).optional(),
  })
  .transform(d => ({
    policy: d.policy,
    accountId: d.account_id,
    limitConfig: d.limit_config,
  }));

export const unmarshalUsagePolicySchema = z
  .object({
    policy_id: z.string().optional(),
    policy_name: z.string().optional(),
    custom_tags: z
      .array(z.lazy(() => unmarshalCustomPolicyTagSchema))
      .optional(),
    binding_workspace_ids: z.array(z.number()).optional(),
  })
  .transform(d => ({
    policyId: d.policy_id,
    policyName: d.policy_name,
    customTags: d.custom_tags,
    bindingWorkspaceIds: d.binding_workspace_ids,
  }));

export const marshalCreateUsagePolicyRequestSchema = z
  .object({
    requestId: z.string().optional(),
    accountId: z.string().optional(),
    policy: z.lazy(() => marshalUsagePolicySchema).optional(),
  })
  .transform(d => ({
    request_id: d.requestId,
    account_id: d.accountId,
    policy: d.policy,
  }));

export const marshalCustomPolicyTagSchema = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const marshalDeleteUsagePolicyRequestSchema = z
  .object({
    policyId: z.string().optional(),
    accountId: z.string().optional(),
  })
  .transform(d => ({
    policy_id: d.policyId,
    account_id: d.accountId,
  }));

export const marshalFilterSchema = z
  .object({
    policyName: z.string().optional(),
    creatorUserId: z.number().optional(),
    creatorUserName: z.string().optional(),
  })
  .transform(d => ({
    policy_name: d.policyName,
    creator_user_id: d.creatorUserId,
    creator_user_name: d.creatorUserName,
  }));

export const marshalGetUsagePolicyRequestSchema = z
  .object({
    policyId: z.string().optional(),
    accountId: z.string().optional(),
  })
  .transform(d => ({
    policy_id: d.policyId,
    account_id: d.accountId,
  }));

export const marshalLimitConfigSchema = z.object({});

export const marshalListUsagePoliciesRequestSchema = z
  .object({
    pageSize: z.number().optional(),
    pageToken: z.string().optional(),
    filterBy: z.lazy(() => marshalFilterSchema).optional(),
    sortSpec: z.lazy(() => marshalSortSpecSchema).optional(),
    accountId: z.string().optional(),
  })
  .transform(d => ({
    page_size: d.pageSize,
    page_token: d.pageToken,
    filter_by: d.filterBy,
    sort_spec: d.sortSpec,
    account_id: d.accountId,
  }));

export const marshalListUsagePoliciesResponseSchema = z
  .object({
    policies: z.array(z.lazy(() => marshalUsagePolicySchema)).optional(),
    nextPageToken: z.string().optional(),
    previousPageToken: z.string().optional(),
  })
  .transform(d => ({
    policies: d.policies,
    next_page_token: d.nextPageToken,
    previous_page_token: d.previousPageToken,
  }));

export const marshalSortSpecSchema = z
  .object({
    field: z.enum(SortSpec_Field).optional(),
    descending: z.boolean().optional(),
  })
  .transform(d => ({
    field: d.field,
    descending: d.descending,
  }));

export const marshalUpdateUsagePolicyRequestSchema = z
  .object({
    policy: z.lazy(() => marshalUsagePolicySchema).optional(),
    accountId: z.string().optional(),
    limitConfig: z.lazy(() => marshalLimitConfigSchema).optional(),
  })
  .transform(d => ({
    policy: d.policy,
    account_id: d.accountId,
    limit_config: d.limitConfig,
  }));

export const marshalUsagePolicySchema = z
  .object({
    policyId: z.string().optional(),
    policyName: z.string().optional(),
    customTags: z.array(z.lazy(() => marshalCustomPolicyTagSchema)).optional(),
    bindingWorkspaceIds: z.array(z.number()).optional(),
  })
  .transform(d => ({
    policy_id: d.policyId,
    policy_name: d.policyName,
    custom_tags: d.customTags,
    binding_workspace_ids: d.bindingWorkspaceIds,
  }));
