// Code generated from API definition by Databricks SDK Generator. DO NOT EDIT.

import {z} from 'zod';

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum SortSpec_Field {
  /** If unspecified, the server will decide the default field to sort on. */
  FIELD_UNSPECIFIED = 'FIELD_UNSPECIFIED',
  /** Sort by policy name. */
  POLICY_NAME = 'POLICY_NAME',
}

/** A request to create a UsagePolicy. */
export interface CreateUsagePolicyRequest {
  /** A unique identifier for this request. Restricted to 36 ASCII characters. */
  requestId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /** The policy to create. `policy_id` needs to be empty as it will be generated */
  policy?: UsagePolicy | undefined;
}

export interface CustomPolicyTag {
  /**
   * The key of the tag.
   * - Must be unique among all custom tags of the same policy
   * - Cannot be “budget-policy-name”, “budget-policy-id” or "budget-policy-resolution-result" -
   * these tags are preserved.
   */
  key?: string | undefined;
  /** The value of the tag. */
  value?: string | undefined;
}

/** Deletes a usage policy */
export interface DeleteUsagePolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * Structured representation of a filter to be applied to a list of policies. All specified filters
 * will be applied in conjunction.
 */
export interface Filter {
  /**
   * The partial name of policies to be filtered on.
   * If unspecified, all policies will be returned.
   */
  policyName?: string | undefined;
  /**
   * The policy creator user id to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserId?: bigint | undefined;
  /**
   * The policy creator user name to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserName?: string | undefined;
}

/** Request to get a usage policy */
export interface GetUsagePolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * The limit configuration of the policy.
 * Limit configuration provide a budget policy level cost control by enforcing the limit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface LimitConfig {}

/** Request to list usage policies */
export interface ListUsagePoliciesRequest {
  /** The maximum number of usage policies to return. */
  pageSize?: number | undefined;
  /** A page token, received from a previous `ListUsagePolicies` call. */
  pageToken?: string | undefined;
  /** A filter to apply to the list of policies. */
  filterBy?: Filter | undefined;
  /** The sort specification. */
  sortSpec?: SortSpec | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/** A list of usage policies. */
export interface ListUsagePoliciesResponse {
  policies?: UsagePolicy[] | undefined;
  /** A token that can be sent as `page_token` to retrieve the next page. */
  nextPageToken?: string | undefined;
  /** A token that can be sent as `page_token` to retrieve the previous page. */
  previousPageToken?: string | undefined;
}

export interface SortSpec {
  /** The filed to sort by */
  field?: SortSpec_Field | undefined;
  /** Whether to sort in descending order. */
  descending?: boolean | undefined;
}

/** Updates a UsagePolicy. */
export interface UpdateUsagePolicyRequest {
  /** The policy to update. `creator_user_id` cannot be specified in the request. */
  policy?: UsagePolicy | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /** DEPRECATED. This is redundant field as LimitConfig is part of the UsagePolicy */
  limitConfig?: LimitConfig | undefined;
}

/** Contains the UsagePolicy details (same structure as BudgetPolicy) */
export interface UsagePolicy {
  /** The Id of the policy. This field is generated by <Databricks> and globally unique. */
  policyId?: string | undefined;
  /** The name of the policy. */
  policyName?: string | undefined;
  /** A list of tags defined by the customer. At most 20 entries are allowed per policy. */
  customTags?: CustomPolicyTag[] | undefined;
  /** List of workspaces that this usage policy will be exclusively bound to. */
  bindingWorkspaceIds?: bigint[] | undefined;
}

export const unmarshalCustomPolicyTagSchema: z.ZodType<CustomPolicyTag> = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const unmarshalListUsagePoliciesResponseSchema: z.ZodType<ListUsagePoliciesResponse> =
  z
    .object({
      policies: z.array(z.lazy(() => unmarshalUsagePolicySchema)).optional(),
      next_page_token: z.string().optional(),
      previous_page_token: z.string().optional(),
    })
    .transform(d => ({
      policies: d.policies,
      nextPageToken: d.next_page_token,
      previousPageToken: d.previous_page_token,
    }));

export const unmarshalUsagePolicySchema: z.ZodType<UsagePolicy> = z
  .object({
    policy_id: z.string().optional(),
    policy_name: z.string().optional(),
    custom_tags: z
      .array(z.lazy(() => unmarshalCustomPolicyTagSchema))
      .optional(),
    binding_workspace_ids: z
      .array(z.union([z.number(), z.bigint()]).transform(v => BigInt(v)))
      .optional(),
  })
  .transform(d => ({
    policyId: d.policy_id,
    policyName: d.policy_name,
    customTags: d.custom_tags,
    bindingWorkspaceIds: d.binding_workspace_ids,
  }));

export const marshalCreateUsagePolicyRequestSchema: z.ZodType = z
  .object({
    requestId: z.string().optional(),
    accountId: z.string().optional(),
    policy: z.lazy(() => marshalUsagePolicySchema).optional(),
  })
  .transform(d => ({
    request_id: d.requestId,
    account_id: d.accountId,
    policy: d.policy,
  }));

export const marshalCustomPolicyTagSchema: z.ZodType = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const marshalFilterSchema: z.ZodType = z
  .object({
    policyName: z.string().optional(),
    creatorUserId: z.bigint().optional(),
    creatorUserName: z.string().optional(),
  })
  .transform(d => ({
    policy_name: d.policyName,
    creator_user_id: d.creatorUserId,
    creator_user_name: d.creatorUserName,
  }));

export const marshalLimitConfigSchema: z.ZodType = z.object({});

export const marshalSortSpecSchema: z.ZodType = z
  .object({
    field: z.enum(SortSpec_Field).optional(),
    descending: z.boolean().optional(),
  })
  .transform(d => ({
    field: d.field,
    descending: d.descending,
  }));

export const marshalUsagePolicySchema: z.ZodType = z
  .object({
    policyId: z.string().optional(),
    policyName: z.string().optional(),
    customTags: z.array(z.lazy(() => marshalCustomPolicyTagSchema)).optional(),
    bindingWorkspaceIds: z.array(z.bigint()).optional(),
  })
  .transform(d => ({
    policy_id: d.policyId,
    policy_name: d.policyName,
    custom_tags: d.customTags,
    binding_workspace_ids: d.bindingWorkspaceIds,
  }));
