// Code generated by genkit. DO NOT EDIT.

enum AnomalyDetectionJobType {
  ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED = 'ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED',
  ANOMALY_DETECTION_JOB_TYPE_NORMAL = 'ANOMALY_DETECTION_JOB_TYPE_NORMAL',
  ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN = 'ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN',
}

/** Status of Anomaly Detection Job Run */
enum AnomalyDetectionRunStatus {
  ANOMALY_DETECTION_RUN_STATUS_UNKNOWN = 'ANOMALY_DETECTION_RUN_STATUS_UNKNOWN',
  ANOMALY_DETECTION_RUN_STATUS_RUNNING = 'ANOMALY_DETECTION_RUN_STATUS_RUNNING',
  ANOMALY_DETECTION_RUN_STATUS_CANCELED = 'ANOMALY_DETECTION_RUN_STATUS_CANCELED',
  ANOMALY_DETECTION_RUN_STATUS_PENDING = 'ANOMALY_DETECTION_RUN_STATUS_PENDING',
  ANOMALY_DETECTION_RUN_STATUS_SUCCESS = 'ANOMALY_DETECTION_RUN_STATUS_SUCCESS',
  ANOMALY_DETECTION_RUN_STATUS_FAILED = 'ANOMALY_DETECTION_RUN_STATUS_FAILED',
  ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED = 'ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED',
  ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR = 'ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR',
}

enum ThresholdType {
  THRESHOLD_TYPE_UNSPECIFIED = 'THRESHOLD_TYPE_UNSPECIFIED',
  THRESHOLD_TYPE_AUTO = 'THRESHOLD_TYPE_AUTO',
  THRESHOLD_TYPE_UNBOUNDED = 'THRESHOLD_TYPE_UNBOUNDED',
  THRESHOLD_TYPE_MANUAL = 'THRESHOLD_TYPE_MANUAL',
}

interface AnomalyDetectionConfig {}

interface ColumnMatcher {}

interface CreateQualityMonitorRequest {}

interface CustomCheckConfiguration {}

interface CustomCheckThresholds {}

interface CustomScalarCheck {}

interface DeleteQualityMonitorRequest {}

interface GetQualityMonitorRequest {}

interface ListQualityMonitorRequest {}

interface ListQualityMonitorResponse {}

interface PercentNullValidityCheck {}

interface QualityMonitor {}

interface RangeValidityCheck {}

interface Threshold {}

interface UniquenessValidityCheck {}

interface UpdateQualityMonitorRequest {}

interface ValidityCheckConfiguration {}

export {AnomalyDetectionJobType, AnomalyDetectionRunStatus, ThresholdType};

export type {
  AnomalyDetectionConfig,
  ColumnMatcher,
  CreateQualityMonitorRequest,
  CustomCheckConfiguration,
  CustomCheckThresholds,
  CustomScalarCheck,
  DeleteQualityMonitorRequest,
  GetQualityMonitorRequest,
  ListQualityMonitorRequest,
  ListQualityMonitorResponse,
  PercentNullValidityCheck,
  QualityMonitor,
  RangeValidityCheck,
  Threshold,
  UniquenessValidityCheck,
  UpdateQualityMonitorRequest,
  ValidityCheckConfiguration,
};
