// Code generated by genkit. DO NOT EDIT.

export enum AnomalyDetectionJobType {
  ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED = 'ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED',
  ANOMALY_DETECTION_JOB_TYPE_NORMAL = 'ANOMALY_DETECTION_JOB_TYPE_NORMAL',
  ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN = 'ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN',
}

/** Status of Anomaly Detection Job Run */
export enum AnomalyDetectionRunStatus {
  ANOMALY_DETECTION_RUN_STATUS_UNKNOWN = 'ANOMALY_DETECTION_RUN_STATUS_UNKNOWN',
  ANOMALY_DETECTION_RUN_STATUS_RUNNING = 'ANOMALY_DETECTION_RUN_STATUS_RUNNING',
  ANOMALY_DETECTION_RUN_STATUS_CANCELED = 'ANOMALY_DETECTION_RUN_STATUS_CANCELED',
  ANOMALY_DETECTION_RUN_STATUS_PENDING = 'ANOMALY_DETECTION_RUN_STATUS_PENDING',
  ANOMALY_DETECTION_RUN_STATUS_SUCCESS = 'ANOMALY_DETECTION_RUN_STATUS_SUCCESS',
  ANOMALY_DETECTION_RUN_STATUS_FAILED = 'ANOMALY_DETECTION_RUN_STATUS_FAILED',
  ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED = 'ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED',
  ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR = 'ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR',
}

export enum ThresholdType {
  THRESHOLD_TYPE_UNSPECIFIED = 'THRESHOLD_TYPE_UNSPECIFIED',
  THRESHOLD_TYPE_AUTO = 'THRESHOLD_TYPE_AUTO',
  THRESHOLD_TYPE_UNBOUNDED = 'THRESHOLD_TYPE_UNBOUNDED',
  THRESHOLD_TYPE_MANUAL = 'THRESHOLD_TYPE_MANUAL',
}

export interface AnomalyDetectionConfig {
  /** Run id of the last run of the workflow */
  lastRunId?: string | undefined;
  /** The status of the last run of the workflow. */
  latestRunStatus?: AnomalyDetectionRunStatus | undefined;
  /** The type of the last run of the workflow. */
  jobType?: AnomalyDetectionJobType | undefined;
  /** List of fully qualified table names to exclude from anomaly detection. */
  excludedTableFullNames?: string[] | undefined;
  customCheckConfigurations?: CustomCheckConfiguration[] | undefined;
  validityCheckConfigurations?: ValidityCheckConfiguration[] | undefined;
}

export interface ColumnMatcher {
  /** Variable name within a custom sql query that this matcher applies to. */
  variableName?: string | undefined;
  /** List of column names (in target tables) to match. */
  columnNames?: string[] | undefined;
}

export interface CreateQualityMonitorRequest {
  qualityMonitor?: QualityMonitor | undefined;
}

export interface CustomCheckConfiguration {
  scalarCheck?: CustomScalarCheck | undefined;
}

export interface CustomCheckThresholds {
  /** Lower bound threshold */
  lowerBound?: Threshold | undefined;
  /** Upper bound threshold */
  upperBound?: Threshold | undefined;
}

export interface CustomScalarCheck {
  /** Name of the custom check */
  checkName?: string | undefined;
  /** Templated SQL query for this check */
  sqlQuery?: string | undefined;
  /** Column matchers to determine which tables to apply this check to */
  columnMatchers?: ColumnMatcher[] | undefined;
  /** Upper/lower thresholds for the output of the query */
  thresholds?: CustomCheckThresholds | undefined;
}

export interface DeleteQualityMonitorRequest {
  /** The type of the monitored object. Can be one of the following: schema. */
  objectType?: string | undefined;
  /** The uuid of the request object. For example, schema id. */
  objectId?: string | undefined;
}

export interface GetQualityMonitorRequest {
  /** The type of the monitored object. Can be one of the following: schema. */
  objectType?: string | undefined;
  /** The uuid of the request object. For example, schema id. */
  objectId?: string | undefined;
}

export interface ListQualityMonitorRequest {
  pageToken?: string | undefined;
  pageSize?: number | undefined;
}

export interface ListQualityMonitorResponse {
  qualityMonitors?: QualityMonitor[] | undefined;
  nextPageToken?: string | undefined;
}

export interface PercentNullValidityCheck {
  /** List of column names to check for null percentage */
  columnNames?: string[] | undefined;
  /** Optional upper bound; we should use auto determined bounds for now */
  upperBound?: number | undefined;
}

export interface QualityMonitor {
  /** The type of the monitored object. Can be one of the following: schema. */
  objectType?: string | undefined;
  /** The uuid of the request object. For example, schema id. */
  objectId?: string | undefined;
  anomalyDetectionConfig?: AnomalyDetectionConfig | undefined;
  /** Validity check configurations for anomaly detection. */
  validityCheckConfigurations?: ValidityCheckConfiguration[] | undefined;
}

export interface RangeValidityCheck {
  /** List of column names to check for range validity */
  columnNames?: string[] | undefined;
  /** Lower bound for the range */
  lowerBound?: number | undefined;
  /** Upper bound for the range */
  upperBound?: number | undefined;
}

export interface Threshold {
  /** Bound value for this threshold. Meaningful only if threshold_type is MANUAL. */
  boundValue?: number | undefined;
  thresholdType?: ThresholdType | undefined;
}

export interface UniquenessValidityCheck {
  /** List of column names to check for uniqueness */
  columnNames?: string[] | undefined;
}

export interface UpdateQualityMonitorRequest {
  /** The type of the monitored object. Can be one of the following: schema. */
  objectType?: string | undefined;
  /** The uuid of the request object. For example, schema id. */
  objectId?: string | undefined;
  qualityMonitor?: QualityMonitor | undefined;
}

export interface ValidityCheckConfiguration {
  /** Can be set by system. Does not need to be user facing. */
  name?: string | undefined;
  percentNullValidityCheck?: PercentNullValidityCheck | undefined;
  rangeValidityCheck?: RangeValidityCheck | undefined;
  uniquenessValidityCheck?: UniquenessValidityCheck | undefined;
}
