// Code generated from API definition by Databricks SDK Generator. DO NOT EDIT.

import {z} from 'zod';

// eslint-disable-next-line @typescript-eslint/naming-convention -- Proto-style nested enum name.
export enum SortSpec_Field {
  /** If unspecified, the server will decide the default field to sort on. */
  FIELD_UNSPECIFIED = 'FIELD_UNSPECIFIED',
  /** Sort by policy name. */
  POLICY_NAME = 'POLICY_NAME',
}

/** Contains the BudgetPolicy details. */
export interface BudgetPolicy {
  /** The Id of the policy. This field is generated by <Databricks> and globally unique. */
  policyId?: string | undefined;
  /**
   * The name of the policy.
   * - Must be unique among active policies.
   * - Can contain only characters from the ISO 8859-1 (latin1) set.
   * - Can't start with reserved keywords such as `databricks:default-policy`.
   */
  policyName?: string | undefined;
  /** A list of tags defined by the customer. At most 20 entries are allowed per policy. */
  customTags?: CustomPolicyTag[] | undefined;
  /**
   * List of workspaces that this budget policy will be exclusively bound to.
   * An empty binding implies that this budget policy is open to any workspace in the account.
   */
  bindingWorkspaceIds?: number[] | undefined;
}

/** A request to create a BudgetPolicy. */
export interface CreateBudgetPolicyRequest {
  /**
   * A unique identifier for this request. Restricted to 36 ASCII characters.
   * A random UUID is recommended.
   * This request is only idempotent if a `request_id` is provided.
   */
  requestId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /**
   * The policy to create. `policy_id` needs to be empty as it will be generated
   * `policy_name` must be provided, custom_tags may need to be provided
   * depending on the cloud provider. All other fields are optional.
   */
  policy?: BudgetPolicy | undefined;
}

export interface CustomPolicyTag {
  /**
   * The key of the tag.
   * - Must be unique among all custom tags of the same policy
   * - Cannot be “budget-policy-name”, “budget-policy-id” or "budget-policy-resolution-result" -
   * these tags are preserved.
   */
  key?: string | undefined;
  /** The value of the tag. */
  value?: string | undefined;
}

/** Deletes a policy */
export interface DeleteBudgetPolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * Structured representation of a filter to be applied to a list of policies. All specified filters
 * will be applied in conjunction.
 */
export interface Filter {
  /**
   * The partial name of policies to be filtered on.
   * If unspecified, all policies will be returned.
   */
  policyName?: string | undefined;
  /**
   * The policy creator user id to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserId?: number | undefined;
  /**
   * The policy creator user name to be filtered on.
   * If unspecified, all policies will be returned.
   */
  creatorUserName?: string | undefined;
}

export interface GetBudgetPolicyRequest {
  /** The Id of the policy. */
  policyId?: string | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/**
 * The limit configuration of the policy.
 * Limit configuration provide a budget policy level cost control by enforcing the limit.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface LimitConfig {}

/** Request to list budget policies. Uses pagination. */
export interface ListBudgetPoliciesRequest {
  /**
   * The maximum number of budget policies to return.
   * If unspecified, at most 100 budget policies will be returned.
   * The maximum value is 1000; values above 1000 will be coerced to 1000.
   */
  pageSize?: number | undefined;
  /**
   * A page token, received from a previous `ListServerlessPolicies` call.
   * Provide this to retrieve the subsequent page.
   * If unspecified, the first page will be returned.
   *
   * When paginating, all other parameters provided to `ListServerlessPoliciesRequest` must match
   * the call that provided the page token.
   */
  pageToken?: string | undefined;
  /** A filter to apply to the list of policies. */
  filterBy?: Filter | undefined;
  /** The sort specification. */
  sortSpec?: SortSpec | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
}

/** A list of policies. */
export interface ListBudgetPoliciesResponse {
  policies?: BudgetPolicy[] | undefined;
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   */
  nextPageToken?: string | undefined;
  /**
   * A token that can be sent as `page_token` to retrieve the previous page.
   * In this field is omitted, there are no previous pages.
   */
  previousPageToken?: string | undefined;
}

export interface SortSpec {
  /** The filed to sort by */
  field?: SortSpec_Field | undefined;
  /** Whether to sort in descending order. */
  descending?: boolean | undefined;
}

/** Updates a BudgetPolicy. */
export interface UpdateBudgetPolicyRequest {
  /**
   * The policy to update. `creator_user_id` cannot be specified in the request. All other fields
   * must be specified even if not changed. The `policy_id` is used to identify the policy to
   * update.
   */
  policy?: BudgetPolicy | undefined;
  /** The account Id of the customer */
  accountId?: string | undefined;
  /** DEPRECATED. This is redundant field as LimitConfig is part of the BudgetPolicy */
  limitConfig?: LimitConfig | undefined;
}

export const unmarshalBudgetPolicySchema: z.ZodType<BudgetPolicy> = z
  .object({
    policy_id: z.string().optional(),
    policy_name: z.string().optional(),
    custom_tags: z
      .array(z.lazy(() => unmarshalCustomPolicyTagSchema))
      .optional(),
    binding_workspace_ids: z.array(z.number()).optional(),
  })
  .transform(d => ({
    policyId: d.policy_id,
    policyName: d.policy_name,
    customTags: d.custom_tags,
    bindingWorkspaceIds: d.binding_workspace_ids,
  }));

export const unmarshalCustomPolicyTagSchema: z.ZodType<CustomPolicyTag> = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const unmarshalListBudgetPoliciesResponseSchema: z.ZodType<ListBudgetPoliciesResponse> =
  z
    .object({
      policies: z.array(z.lazy(() => unmarshalBudgetPolicySchema)).optional(),
      next_page_token: z.string().optional(),
      previous_page_token: z.string().optional(),
    })
    .transform(d => ({
      policies: d.policies,
      nextPageToken: d.next_page_token,
      previousPageToken: d.previous_page_token,
    }));

export const marshalBudgetPolicySchema: z.ZodType = z
  .object({
    policyId: z.string().optional(),
    policyName: z.string().optional(),
    customTags: z.array(z.lazy(() => marshalCustomPolicyTagSchema)).optional(),
    bindingWorkspaceIds: z.array(z.number()).optional(),
  })
  .transform(d => ({
    policy_id: d.policyId,
    policy_name: d.policyName,
    custom_tags: d.customTags,
    binding_workspace_ids: d.bindingWorkspaceIds,
  }));

export const marshalCreateBudgetPolicyRequestSchema: z.ZodType = z
  .object({
    requestId: z.string().optional(),
    accountId: z.string().optional(),
    policy: z.lazy(() => marshalBudgetPolicySchema).optional(),
  })
  .transform(d => ({
    request_id: d.requestId,
    account_id: d.accountId,
    policy: d.policy,
  }));

export const marshalCustomPolicyTagSchema: z.ZodType = z
  .object({
    key: z.string().optional(),
    value: z.string().optional(),
  })
  .transform(d => ({
    key: d.key,
    value: d.value,
  }));

export const marshalFilterSchema: z.ZodType = z
  .object({
    policyName: z.string().optional(),
    creatorUserId: z.number().optional(),
    creatorUserName: z.string().optional(),
  })
  .transform(d => ({
    policy_name: d.policyName,
    creator_user_id: d.creatorUserId,
    creator_user_name: d.creatorUserName,
  }));

export const marshalLimitConfigSchema: z.ZodType = z.object({});

export const marshalSortSpecSchema: z.ZodType = z
  .object({
    field: z.enum(SortSpec_Field).optional(),
    descending: z.boolean().optional(),
  })
  .transform(d => ({
    field: d.field,
    descending: d.descending,
  }));
