// Code generated by genkit. DO NOT EDIT.

/** The granularity for aggregating data into time windows based on their timestamp. */
export enum AggregationGranularity {
  AGGREGATION_GRANULARITY_UNSPECIFIED = 'AGGREGATION_GRANULARITY_UNSPECIFIED',
  /** 5 minutes. */
  AGGREGATION_GRANULARITY_5_MINUTES = 'AGGREGATION_GRANULARITY_5_MINUTES',
  /** 30 minutes. */
  AGGREGATION_GRANULARITY_30_MINUTES = 'AGGREGATION_GRANULARITY_30_MINUTES',
  /** 1 hour. */
  AGGREGATION_GRANULARITY_1_HOUR = 'AGGREGATION_GRANULARITY_1_HOUR',
  /** 1 day. */
  AGGREGATION_GRANULARITY_1_DAY = 'AGGREGATION_GRANULARITY_1_DAY',
  /** 1 week. */
  AGGREGATION_GRANULARITY_1_WEEK = 'AGGREGATION_GRANULARITY_1_WEEK',
  /** 2 weeks. */
  AGGREGATION_GRANULARITY_2_WEEKS = 'AGGREGATION_GRANULARITY_2_WEEKS',
  /** 3 weeks. */
  AGGREGATION_GRANULARITY_3_WEEKS = 'AGGREGATION_GRANULARITY_3_WEEKS',
  /** 4 weeks. */
  AGGREGATION_GRANULARITY_4_WEEKS = 'AGGREGATION_GRANULARITY_4_WEEKS',
  /** 1 month. */
  AGGREGATION_GRANULARITY_1_MONTH = 'AGGREGATION_GRANULARITY_1_MONTH',
  /** 1 year. */
  AGGREGATION_GRANULARITY_1_YEAR = 'AGGREGATION_GRANULARITY_1_YEAR',
}

/** Anomaly Detection job type. */
export enum AnomalyDetectionJobType {
  ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED = 'ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED',
  ANOMALY_DETECTION_JOB_TYPE_NORMAL = 'ANOMALY_DETECTION_JOB_TYPE_NORMAL',
  ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN = 'ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN',
}

/** The data quality monitoring workflow cron schedule pause status. */
export enum CronSchedulePauseStatus {
  CRON_SCHEDULE_PAUSE_STATUS_UNSPECIFIED = 'CRON_SCHEDULE_PAUSE_STATUS_UNSPECIFIED',
  /** The cron schedule is not paused. */
  CRON_SCHEDULE_PAUSE_STATUS_UNPAUSED = 'CRON_SCHEDULE_PAUSE_STATUS_UNPAUSED',
  /** The cron schedule is paused. */
  CRON_SCHEDULE_PAUSE_STATUS_PAUSED = 'CRON_SCHEDULE_PAUSE_STATUS_PAUSED',
}

/** The custom metric type. */
export enum DataProfilingCustomMetricType {
  DATA_PROFILING_CUSTOM_METRIC_TYPE_UNSPECIFIED = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_UNSPECIFIED',
  /** Only depend on the existing columns in the table. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_AGGREGATE = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_AGGREGATE',
  /** Only depend on previously computed aggregate metrics. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_DERIVED = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_DERIVED',
  /** Depend on previously computed aggregate or derived metrics. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_DRIFT = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_DRIFT',
}

/** The status of the data profiling monitor. */
export enum DataProfilingStatus {
  DATA_PROFILING_STATUS_UNSPECIFIED = 'DATA_PROFILING_STATUS_UNSPECIFIED',
  DATA_PROFILING_STATUS_ACTIVE = 'DATA_PROFILING_STATUS_ACTIVE',
  DATA_PROFILING_STATUS_PENDING = 'DATA_PROFILING_STATUS_PENDING',
  DATA_PROFILING_STATUS_DELETE_PENDING = 'DATA_PROFILING_STATUS_DELETE_PENDING',
  DATA_PROFILING_STATUS_ERROR = 'DATA_PROFILING_STATUS_ERROR',
  DATA_PROFILING_STATUS_FAILED = 'DATA_PROFILING_STATUS_FAILED',
}

/** Inference problem type the model aims to solve. */
export enum InferenceProblemType {
  INFERENCE_PROBLEM_TYPE_UNSPECIFIED = 'INFERENCE_PROBLEM_TYPE_UNSPECIFIED',
  /** Classification inference problem. */
  INFERENCE_PROBLEM_TYPE_CLASSIFICATION = 'INFERENCE_PROBLEM_TYPE_CLASSIFICATION',
  /** Regression inference problem. */
  INFERENCE_PROBLEM_TYPE_REGRESSION = 'INFERENCE_PROBLEM_TYPE_REGRESSION',
}

/** The state of the refresh. */
export enum RefreshState {
  MONITOR_REFRESH_STATE_UNKNOWN = 'MONITOR_REFRESH_STATE_UNKNOWN',
  /** The refresh is pending. */
  MONITOR_REFRESH_STATE_PENDING = 'MONITOR_REFRESH_STATE_PENDING',
  /** The refresh is running. */
  MONITOR_REFRESH_STATE_RUNNING = 'MONITOR_REFRESH_STATE_RUNNING',
  /** The refresh is successful. */
  MONITOR_REFRESH_STATE_SUCCESS = 'MONITOR_REFRESH_STATE_SUCCESS',
  /** The refresh has failed. */
  MONITOR_REFRESH_STATE_FAILED = 'MONITOR_REFRESH_STATE_FAILED',
  /** The refresh is cancelled. */
  MONITOR_REFRESH_STATE_CANCELED = 'MONITOR_REFRESH_STATE_CANCELED',
}

/** The trigger of the refresh. */
export enum RefreshTrigger {
  MONITOR_REFRESH_TRIGGER_UNKNOWN = 'MONITOR_REFRESH_TRIGGER_UNKNOWN',
  /** The refresh has been triggered manually. */
  MONITOR_REFRESH_TRIGGER_MANUAL = 'MONITOR_REFRESH_TRIGGER_MANUAL',
  /** The refresh has been triggered from a schedule. */
  MONITOR_REFRESH_TRIGGER_SCHEDULE = 'MONITOR_REFRESH_TRIGGER_SCHEDULE',
  /** The refresh has been triggered from a data change. */
  MONITOR_REFRESH_TRIGGER_DATA_CHANGE = 'MONITOR_REFRESH_TRIGGER_DATA_CHANGE',
}

/** Anomaly Detection Configurations. */
export interface AnomalyDetectionConfig {
  /**
   * The id of the workflow that detects the anomaly.
   * This field will only be returned in the Get/Update response, if the request comes from
   * the workspace where this anomaly detection job is created.
   */
  anomalyDetectionWorkflowId?: number | undefined;
  /** If the health indicator should be shown. */
  publishHealthIndicator?: boolean | undefined;
  /** The type of the last run of the workflow. */
  jobType?: AnomalyDetectionJobType | undefined;
  /** List of fully qualified table names to exclude from anomaly detection. */
  excludedTableFullNames?: string[] | undefined;
  /** Validity check configurations for anomaly detection. */
  validityCheckConfigurations?: ValidityCheckConfiguration[] | undefined;
}

/** Request to cancel a refresh. */
export interface CancelRefreshRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Unique id of the refresh operation. */
  refreshId?: number | undefined;
}

/** Response to cancelling a refresh. */
export interface CancelRefreshResponse {
  /** The refresh to cancel. */
  refresh?: Refresh | undefined;
}

/** Request to create a Monitor. */
export interface CreateMonitorRequest {
  /** The monitor to create. */
  monitor?: Monitor | undefined;
}

/** Request to create a refresh. */
export interface CreateRefreshRequest {
  /** The refresh to create */
  refresh?: Refresh | undefined;
}

/** The data quality monitoring workflow cron schedule. */
export interface CronSchedule {
  /** The expression that determines when to run the monitor. See [examples](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html). */
  quartzCronExpression?: string | undefined;
  /**
   * A Java timezone id. The schedule for a job will be resolved with respect to this timezone.
   * See `Java TimeZone <http://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html>`_ for details.
   * The timezone id (e.g., ``America/Los_Angeles``) in which to evaluate the quartz expression.
   */
  timezoneId?: string | undefined;
  /** Read only field that indicates whether the schedule is paused or not. */
  pauseStatus?: CronSchedulePauseStatus | undefined;
}

/** Data Profiling Configurations. */
export interface DataProfilingConfig {
  /** ID of the schema where output tables are created. */
  outputSchemaId?: string | undefined;
  /**
   * Field for specifying the absolute path to a custom directory to store data-monitoring
   * assets. Normally prepopulated to a default user location via UI and Python APIs.
   */
  assetsDir?: string | undefined;
  /** `Analysis Configuration` for monitoring inference log tables. */
  inferenceLog?: InferenceLogConfig | undefined;
  /** `Analysis Configuration` for monitoring time series tables. */
  timeSeries?: TimeSeriesConfig | undefined;
  /** `Analysis Configuration` for monitoring snapshot tables. */
  snapshot?: SnapshotConfig | undefined;
  /**
   * List of column expressions to slice data with for targeted analysis. The data is grouped by
   * each expression independently, resulting in a separate slice for each predicate and its
   * complements. For example `slicing_exprs=[“col_1”, “col_2 > 10”]` will generate the following
   * slices: two slices for `col_2 > 10` (True and False), and one slice per unique value in
   * `col1`. For high-cardinality columns, only the top 100 unique values by frequency will
   * generate slices.
   */
  slicingExprs?: string[] | undefined;
  /** Custom metrics. */
  customMetrics?: DataProfilingCustomMetric[] | undefined;
  /**
   * Baseline table name.
   * Baseline data is used to compute drift from the data in the monitored `table_name`.
   * The baseline table and the monitored table shall have the same schema.
   */
  baselineTableName?: string | undefined;
  /** The cron schedule. */
  schedule?: CronSchedule | undefined;
  /** Field for specifying notification settings. */
  notificationSettings?: NotificationSettings | undefined;
  /** Whether to skip creating a default dashboard summarizing data quality metrics. */
  skipBuiltinDashboard?: boolean | undefined;
  /**
   * Optional argument to specify the warehouse for dashboard creation. If not specified, the first running
   * warehouse will be used.
   */
  warehouseId?: string | undefined;
  /** Unity Catalog table to monitor. Format: `catalog.schema.table_name` */
  monitoredTableName?: string | undefined;
  /** The data profiling monitor status. */
  status?: DataProfilingStatus | undefined;
  /** The latest error message for a monitor failure. */
  latestMonitorFailureMessage?: string | undefined;
  /** Table that stores profile metrics data. Format: `catalog.schema.table_name`. */
  profileMetricsTableName?: string | undefined;
  /** Table that stores drift metrics data. Format: `catalog.schema.table_name`. */
  driftMetricsTableName?: string | undefined;
  /**
   * Id of dashboard that visualizes the computed metrics.
   * This can be empty if the monitor is in PENDING state.
   */
  dashboardId?: string | undefined;
  /**
   * Represents the current monitor configuration version in use. The version will be represented in a
   * numeric fashion (1,2,3...). The field has flexibility to take on negative values, which can indicate corrupted
   * monitor_version numbers.
   */
  monitorVersion?: number | undefined;
  /** The warehouse for dashboard creation */
  effectiveWarehouseId?: string | undefined;
}

/** Custom metric definition. */
export interface DataProfilingCustomMetric {
  /** Name of the metric in the output tables. */
  name?: string | undefined;
  /** Jinja template for a SQL expression that specifies how to compute the metric. See [create metric definition](https://docs.databricks.com/en/lakehouse-monitoring/custom-metrics.html#create-definition). */
  definition?: string | undefined;
  /**
   * A list of column names in the input table the metric should be computed for.
   * Can use ``":table"`` to indicate that the metric needs information from multiple columns.
   */
  inputColumns?: string[] | undefined;
  /** The output type of the custom metric. */
  outputDataType?: string | undefined;
  /** The type of the custom metric. */
  type?: DataProfilingCustomMetricType | undefined;
}

/** Request to delete a Monitor. */
export interface DeleteMonitorRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
}

/** Request to delete a ronitor. */
export interface DeleteRefreshRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Unique id of the refresh operation. */
  refreshId?: number | undefined;
}

/** Request to get a Monitor. */
export interface GetMonitorRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
}

/** Request to get a refresh. */
export interface GetRefreshRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Unique id of the refresh operation. */
  refreshId?: number | undefined;
}

/** Inference log configuration. */
export interface InferenceLogConfig {
  /** Problem type the model aims to solve. */
  problemType?: InferenceProblemType | undefined;
  /** Column for the timestamp. */
  timestampColumn?: string | undefined;
  /** List of granularities to use when aggregating data into time windows based on their timestamp. */
  granularities?: AggregationGranularity[] | undefined;
  /** Column for the prediction. */
  predictionColumn?: string | undefined;
  /** Column for the label. */
  labelColumn?: string | undefined;
  /** Column for the model identifier. */
  modelIdColumn?: string | undefined;
  /** Column for prediction probabilities */
  predictionProbabilityColumn?: string | undefined;
}

/** Request to list Monitors. */
export interface ListMonitorRequest {
  pageToken?: string | undefined;
  pageSize?: number | undefined;
}

/** Response for listing Monitors. */
export interface ListMonitorResponse {
  monitors?: Monitor[] | undefined;
  nextPageToken?: string | undefined;
}

/** Request to list refreshes. */
export interface ListRefreshRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  pageToken?: string | undefined;
  pageSize?: number | undefined;
}

/** Response for listing refreshes. */
export interface ListRefreshResponse {
  refreshes?: Refresh[] | undefined;
  nextPageToken?: string | undefined;
}

/** Monitor for the data quality of unity catalog entities such as schema or table. */
export interface Monitor {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Anomaly Detection Configuration, applicable to `schema` object types. */
  anomalyDetectionConfig?: AnomalyDetectionConfig | undefined;
  /**
   * Data Profiling Configuration, applicable to `table` object types. Exactly one `Analysis Configuration`
   * must be present.
   */
  dataProfilingConfig?: DataProfilingConfig | undefined;
}

/** Destination of the data quality monitoring notification. */
export interface NotificationDestination {
  /** The list of email addresses to send the notification to. A maximum of 5 email addresses is supported. */
  emailAddresses?: string[] | undefined;
}

/** Settings for sending notifications on the data quality monitoring. */
export interface NotificationSettings {
  /** Destinations to send notifications on failure/timeout. */
  onFailure?: NotificationDestination | undefined;
}

export interface PercentNullValidityCheck {
  /** List of column names to check for null percentage */
  columnNames?: string[] | undefined;
  /** Optional upper bound; we should use auto determined bounds for now */
  upperBound?: number | undefined;
}

export interface RangeValidityCheck {
  /** List of column names to check for range validity */
  columnNames?: string[] | undefined;
  /** Lower bound for the range */
  lowerBound?: number | undefined;
  /** Upper bound for the range */
  upperBound?: number | undefined;
}

/** The Refresh object gives information on a refresh of the data quality monitoring pipeline. */
export interface Refresh {
  /** The type of the monitored object. Can be one of the following: `schema`or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Unique id of the refresh operation. */
  refreshId?: number | undefined;
  /** The current state of the refresh. */
  state?: RefreshState | undefined;
  /** An optional message to give insight into the current state of the refresh (e.g. FAILURE messages). */
  message?: string | undefined;
  /** Time when the refresh started (milliseconds since 1/1/1970 UTC). */
  startTimeMs?: number | undefined;
  /** Time when the refresh ended (milliseconds since 1/1/1970 UTC). */
  endTimeMs?: number | undefined;
  /** What triggered the refresh. */
  trigger?: RefreshTrigger | undefined;
}

/** Snapshot analysis configuration. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface SnapshotConfig {}

/** Time series analysis configuration. */
export interface TimeSeriesConfig {
  /** Column for the timestamp. */
  timestampColumn?: string | undefined;
  /** List of granularities to use when aggregating data into time windows based on their timestamp. */
  granularities?: AggregationGranularity[] | undefined;
}

export interface UniquenessValidityCheck {
  /** List of column names to check for uniqueness */
  columnNames?: string[] | undefined;
}

/** Request to update a Monitor. */
export interface UpdateMonitorRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** The monitor to update. */
  monitor?: Monitor | undefined;
  /**
   * The field mask to specify which fields to update as a comma-separated list.
   * Example value: `data_profiling_config.custom_metrics,data_profiling_config.schedule.quartz_cron_expression`
   */
  updateMask?: string | undefined;
}

/** Request to update a refresh. */
export interface UpdateRefreshRequest {
  /** The type of the monitored object. Can be one of the following: `schema` or `table`. */
  objectType?: string | undefined;
  /**
   * The UUID of the request object. It is `schema_id` for `schema`, and `table_id` for `table`.
   *
   * Find the `schema_id` from either:
   * 1. The [schema_id](https://docs.databricks.com/api/workspace/schemas/get#schema_id) of the `Schemas` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `schema` > go to the `Details` tab > the `Schema ID` field.
   *
   * Find the `table_id` from either:
   * 1. The [table_id](https://docs.databricks.com/api/workspace/tables/get#table_id) of the `Tables` resource.
   * 2. In [Catalog Explorer](https://docs.databricks.com/aws/en/catalog-explorer/) > select the `table` > go to the `Details` tab > the `Table ID` field.
   */
  objectId?: string | undefined;
  /** Unique id of the refresh operation. */
  refreshId?: number | undefined;
  /** The refresh to update. */
  refresh?: Refresh | undefined;
  /** The field mask to specify which fields to update. */
  updateMask?: string | undefined;
}

export interface ValidityCheckConfiguration {
  /** Can be set by system. Does not need to be user facing. */
  name?: string | undefined;
  percentNullValidityCheck?: PercentNullValidityCheck | undefined;
  rangeValidityCheck?: RangeValidityCheck | undefined;
  uniquenessValidityCheck?: UniquenessValidityCheck | undefined;
}
