// Code generated by genkit. DO NOT EDIT.

/** The granularity for aggregating data into time windows based on their timestamp. */
enum AggregationGranularity {
  AGGREGATION_GRANULARITY_UNSPECIFIED = 'AGGREGATION_GRANULARITY_UNSPECIFIED',
  /** 5 minutes. */
  AGGREGATION_GRANULARITY_5_MINUTES = 'AGGREGATION_GRANULARITY_5_MINUTES',
  /** 30 minutes. */
  AGGREGATION_GRANULARITY_30_MINUTES = 'AGGREGATION_GRANULARITY_30_MINUTES',
  /** 1 hour. */
  AGGREGATION_GRANULARITY_1_HOUR = 'AGGREGATION_GRANULARITY_1_HOUR',
  /** 1 day. */
  AGGREGATION_GRANULARITY_1_DAY = 'AGGREGATION_GRANULARITY_1_DAY',
  /** 1 week. */
  AGGREGATION_GRANULARITY_1_WEEK = 'AGGREGATION_GRANULARITY_1_WEEK',
  /** 2 weeks. */
  AGGREGATION_GRANULARITY_2_WEEKS = 'AGGREGATION_GRANULARITY_2_WEEKS',
  /** 3 weeks. */
  AGGREGATION_GRANULARITY_3_WEEKS = 'AGGREGATION_GRANULARITY_3_WEEKS',
  /** 4 weeks. */
  AGGREGATION_GRANULARITY_4_WEEKS = 'AGGREGATION_GRANULARITY_4_WEEKS',
  /** 1 month. */
  AGGREGATION_GRANULARITY_1_MONTH = 'AGGREGATION_GRANULARITY_1_MONTH',
  /** 1 year. */
  AGGREGATION_GRANULARITY_1_YEAR = 'AGGREGATION_GRANULARITY_1_YEAR',
}

/** Anomaly Detection job type. */
enum AnomalyDetectionJobType {
  ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED = 'ANOMALY_DETECTION_JOB_TYPE_UNSPECIFIED',
  ANOMALY_DETECTION_JOB_TYPE_NORMAL = 'ANOMALY_DETECTION_JOB_TYPE_NORMAL',
  ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN = 'ANOMALY_DETECTION_JOB_TYPE_INTERNAL_HIDDEN',
}

/** The data quality monitoring workflow cron schedule pause status. */
enum CronSchedulePauseStatus {
  CRON_SCHEDULE_PAUSE_STATUS_UNSPECIFIED = 'CRON_SCHEDULE_PAUSE_STATUS_UNSPECIFIED',
  /** The cron schedule is not paused. */
  CRON_SCHEDULE_PAUSE_STATUS_UNPAUSED = 'CRON_SCHEDULE_PAUSE_STATUS_UNPAUSED',
  /** The cron schedule is paused. */
  CRON_SCHEDULE_PAUSE_STATUS_PAUSED = 'CRON_SCHEDULE_PAUSE_STATUS_PAUSED',
}

/** The custom metric type. */
enum DataProfilingCustomMetricType {
  DATA_PROFILING_CUSTOM_METRIC_TYPE_UNSPECIFIED = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_UNSPECIFIED',
  /** Only depend on the existing columns in the table. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_AGGREGATE = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_AGGREGATE',
  /** Only depend on previously computed aggregate metrics. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_DERIVED = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_DERIVED',
  /** Depend on previously computed aggregate or derived metrics. */
  DATA_PROFILING_CUSTOM_METRIC_TYPE_DRIFT = 'DATA_PROFILING_CUSTOM_METRIC_TYPE_DRIFT',
}

/** The status of the data profiling monitor. */
enum DataProfilingStatus {
  DATA_PROFILING_STATUS_UNSPECIFIED = 'DATA_PROFILING_STATUS_UNSPECIFIED',
  DATA_PROFILING_STATUS_ACTIVE = 'DATA_PROFILING_STATUS_ACTIVE',
  DATA_PROFILING_STATUS_PENDING = 'DATA_PROFILING_STATUS_PENDING',
  DATA_PROFILING_STATUS_DELETE_PENDING = 'DATA_PROFILING_STATUS_DELETE_PENDING',
  DATA_PROFILING_STATUS_ERROR = 'DATA_PROFILING_STATUS_ERROR',
  DATA_PROFILING_STATUS_FAILED = 'DATA_PROFILING_STATUS_FAILED',
}

/** Inference problem type the model aims to solve. */
enum InferenceProblemType {
  INFERENCE_PROBLEM_TYPE_UNSPECIFIED = 'INFERENCE_PROBLEM_TYPE_UNSPECIFIED',
  /** Classification inference problem. */
  INFERENCE_PROBLEM_TYPE_CLASSIFICATION = 'INFERENCE_PROBLEM_TYPE_CLASSIFICATION',
  /** Regression inference problem. */
  INFERENCE_PROBLEM_TYPE_REGRESSION = 'INFERENCE_PROBLEM_TYPE_REGRESSION',
}

/** The state of the refresh. */
enum RefreshState {
  MONITOR_REFRESH_STATE_UNKNOWN = 'MONITOR_REFRESH_STATE_UNKNOWN',
  /** The refresh is pending. */
  MONITOR_REFRESH_STATE_PENDING = 'MONITOR_REFRESH_STATE_PENDING',
  /** The refresh is running. */
  MONITOR_REFRESH_STATE_RUNNING = 'MONITOR_REFRESH_STATE_RUNNING',
  /** The refresh is successful. */
  MONITOR_REFRESH_STATE_SUCCESS = 'MONITOR_REFRESH_STATE_SUCCESS',
  /** The refresh has failed. */
  MONITOR_REFRESH_STATE_FAILED = 'MONITOR_REFRESH_STATE_FAILED',
  /** The refresh is cancelled. */
  MONITOR_REFRESH_STATE_CANCELED = 'MONITOR_REFRESH_STATE_CANCELED',
}

/** The trigger of the refresh. */
enum RefreshTrigger {
  MONITOR_REFRESH_TRIGGER_UNKNOWN = 'MONITOR_REFRESH_TRIGGER_UNKNOWN',
  /** The refresh has been triggered manually. */
  MONITOR_REFRESH_TRIGGER_MANUAL = 'MONITOR_REFRESH_TRIGGER_MANUAL',
  /** The refresh has been triggered from a schedule. */
  MONITOR_REFRESH_TRIGGER_SCHEDULE = 'MONITOR_REFRESH_TRIGGER_SCHEDULE',
  /** The refresh has been triggered from a data change. */
  MONITOR_REFRESH_TRIGGER_DATA_CHANGE = 'MONITOR_REFRESH_TRIGGER_DATA_CHANGE',
}

/** Anomaly Detection Configurations. */
interface AnomalyDetectionConfig {}

/** Request to cancel a refresh. */
interface CancelRefreshRequest {}

/** Response to cancelling a refresh. */
interface CancelRefreshResponse {}

/** Request to create a Monitor. */
interface CreateMonitorRequest {}

/** Request to create a refresh. */
interface CreateRefreshRequest {}

/** The data quality monitoring workflow cron schedule. */
interface CronSchedule {}

/** Data Profiling Configurations. */
interface DataProfilingConfig {}

/** Custom metric definition. */
interface DataProfilingCustomMetric {}

/** Request to delete a Monitor. */
interface DeleteMonitorRequest {}

/** Request to delete a ronitor. */
interface DeleteRefreshRequest {}

/** Request to get a Monitor. */
interface GetMonitorRequest {}

/** Request to get a refresh. */
interface GetRefreshRequest {}

/** Inference log configuration. */
interface InferenceLogConfig {}

/** Request to list Monitors. */
interface ListMonitorRequest {}

/** Response for listing Monitors. */
interface ListMonitorResponse {}

/** Request to list refreshes. */
interface ListRefreshRequest {}

/** Response for listing refreshes. */
interface ListRefreshResponse {}

/** Monitor for the data quality of unity catalog entities such as schema or table. */
interface Monitor {}

/** Destination of the data quality monitoring notification. */
interface NotificationDestination {}

/** Settings for sending notifications on the data quality monitoring. */
interface NotificationSettings {}

interface PercentNullValidityCheck {}

interface RangeValidityCheck {}

/** The Refresh object gives information on a refresh of the data quality monitoring pipeline. */
interface Refresh {}

/** Snapshot analysis configuration. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface SnapshotConfig {}

/** Time series analysis configuration. */
interface TimeSeriesConfig {}

interface UniquenessValidityCheck {}

/** Request to update a Monitor. */
interface UpdateMonitorRequest {}

/** Request to update a refresh. */
interface UpdateRefreshRequest {}

interface ValidityCheckConfiguration {}

export {
  AggregationGranularity,
  AnomalyDetectionJobType,
  CronSchedulePauseStatus,
  DataProfilingCustomMetricType,
  DataProfilingStatus,
  InferenceProblemType,
  RefreshState,
  RefreshTrigger,
};

export type {
  AnomalyDetectionConfig,
  CancelRefreshRequest,
  CancelRefreshResponse,
  CreateMonitorRequest,
  CreateRefreshRequest,
  CronSchedule,
  DataProfilingConfig,
  DataProfilingCustomMetric,
  DeleteMonitorRequest,
  DeleteRefreshRequest,
  GetMonitorRequest,
  GetRefreshRequest,
  InferenceLogConfig,
  ListMonitorRequest,
  ListMonitorResponse,
  ListRefreshRequest,
  ListRefreshResponse,
  Monitor,
  NotificationDestination,
  NotificationSettings,
  PercentNullValidityCheck,
  RangeValidityCheck,
  Refresh,
  SnapshotConfig,
  TimeSeriesConfig,
  UniquenessValidityCheck,
  UpdateMonitorRequest,
  UpdateRefreshRequest,
  ValidityCheckConfiguration,
};
